- docs/.vitepress/config.mjs
- docs/first_steps.md
- docs/index.md
- docs/installation.md
- examples/hello-world/index.ts
- examples/hello-world/package.json
**Related Tasks**: [Guide doc: Running sandbox](https://app.asana.com/0/1205170694555856/1205457666696801/f), [Guide doc: Contracts](https://app.asana.com/0/1205170694555856/1205457666696803/f)
This PR is the sequel to my comment https://github.com/trilitech/jstz/pull/31#issuecomment-1743045018. 
```sh
```
> Docs: Getting Started

- docs/.vitepress/config.mjs
- docs/api/index.md
- docs/api/ledger.md
**Related Tasks**: [API doc: Ledger](https://app.asana.com/0/1205170694555856/1205457666696797/f)
**Dependencies**:  #36, #35  
This PR an API reference and quick start for the `Ledger` runtime API
```sh
```
> Docs: Ledger

- examples/hello-world/package.json
- flake.nix
- nix/jstz.nix
- package-lock.json
- package.json
Currently running `nix build` in NixOS yields and error due to some issues with `clang`. 
This PR addresses the above issue by ensuring the `jstz_kernel` package uses `clang` (from `llvmPackages_16`). 
Additionally, this PR takes the opportunity to package our NPM packages using Nix. 
```sh
nix build
```
> Nix: Fix `nix build` for NixOS

- docs/.vitepress/config.mjs
- docs/api/headers.md
- docs/api/index.md
**Related Tasks**: [API doc: Headers](https://app.asana.com/0/1205170694555856/1205457666696787/f)
This PR an API reference and quick start for the `Headers` runtime API
```sh
```
> Docs: Headers

- docs/.vitepress/config.mjs
- docs/api/index.md
- docs/api/response.md
**Related Tasks**: [API doc: Response](https://app.asana.com/0/1205170694555856/1205457666696785/f)
**Dependencies**: #47 
This PR an API reference and quick start for the `Response` runtime API
```sh
```
> Docs: Response

- .gitignore
- .prettierignore
- examples/fa2/README.md
- examples/fa2/fa2.ts
- examples/fa2/package.json
- examples/fa2/src/index.ts
- examples/fa2/test/actor.ts
- examples/fa2/test/index.ts
- examples/fa2/tsconfig.json
- examples/hello-world/package.json
- examples/hello-world/tsconfig.json
- package-lock.json
- package.json
- packages/jstz-types/index.d.ts
- packages/jstz/index.js
- packages/jstz/package.json
- tsconfig.json
**Related Tasks**: [M8: Demo Script](https://app.asana.com/0/1205170694555856/1205170694556034/f)
This PR adds the FA2 contract used in the demo to the developer success team.
Additionally adds documentation for building, deploying and testing the contract.
Follow the build, deploy and demo instructions in the FA2 [README](https://github.com/trilitech/jstz/blob/ajob410%40examples/fa2/examples/fa2/README.md).
> Examples: FA2

- Cargo.lock
- nix/jstz.nix
Bumps the commit hash of `boa_engine` to the latest version on our fork. 
```sh
nix build
```
> Nix: Bump `boa_engine`

- jstz_cli/src/repl.rs
The CLI repl does not support the `await` keyword at the lop level.
This PR turns the bug into a feature by adding the following behaviour
* If the repl command returns a promise the. repl will block until the promise is resolved and returns the fulfilment value of the promise
* The result of the last run command, or the fulfilment value in the case of a promise, is stored in a variable `_` for easy reuse.
**Related Tasks**: [REPL: Resolve promises automatically](https://app.asana.com/0/1205170694555856/1205666947698889/f)
```javascript
cargo run -- repl
> Contract.create("export default () => { console.log(`Hello from ${Ledger.selfAddress} 👋`); return new Response() }");
> new Request(`tezos://${_}`);
> Contract.call(_);
```
> Cli Repl: Automatically resolve promises and add last result variable

- .github/dependabot.yml
**Related Tasks**: [Setup dependabot](https://app.asana.com/0/1205170694555856/1205712852000863/f)
This PR configures dependabot, a helpful GitHub bot that will create PRs that bump our package versions. 
This will ensure our packages will be up to date, not contain any known vulnerabilities, etc
> Git: Configure dependabot

- docs/.vitepress/config.mjs
- docs/api/index.md
- docs/api/request.md
**Related Tasks**: [API doc: Request](https://app.asana.com/0/1205170694555856/1205457666696783/f)
This PR an API reference and quick start for the `Request` runtime API
```sh
```
> Docs: Request

- README.md
> Updated definition of JSTZ

- docs/index.md
> Updated definition of JSTZ and corrected spelling mistake

- README.md
> corrected spelling mistake

- CONTRIBUTING.md
- docs/.vitepress/config.mjs
- docs/first_steps.md
- docs/index.md
Removes references to Tezos 2.0.
> Docs: Remove references to Tezos 2.0

- .gitignore
- jstz_cli/src/logs/mod.rs
- jstz_cli/src/logs/trace.rs
- jstz_cli/src/main.rs
https://app.asana.com/0/1205170694555918/1205507584925473
Adds trace command to the CLI - works similarly to ./view-console.sh.
`cargo run -- logs trace`
> Cli: Trace

- docs/.vitepress/config.mjs
- docs/api/console.md
- docs/api/index.md
- jstz_api/src/console.rs
**Related Tasks**: [API doc: Console](https://app.asana.com/0/1205170694555856/1205457666696793/f)
This PR documents the `Console` API.
`npm run docs:dev`
> Docs: Console

- Cargo.lock
- jstz_cli/src/account/account.rs
- jstz_cli/src/deploy.rs
- jstz_cli/src/jstz.rs
- jstz_cli/src/run.rs
- jstz_node/Cargo.toml
- jstz_node/src/main.rs
- jstz_node/src/services/accounts.rs
- jstz_node/src/services/mod.rs
- jstz_proto/src/context/account.rs
[Fetching Nonce from `jstz-node`](https://app.asana.com/0/1205770721173531/1205815667794073/f)
This PR provides an endpoint in jstz-node for reading nonce of an account. In the CLI it provides an API for reading this nonce, removes nonce from the Account config and instead fetches the nonce from the node.
```
jstz deploy < examples/counter.js
jstz run <address>
```
> Node: Fetching Nonce from jstz-node

- jstz_proto/src/executor/contract.rs
https://app.asana.com/0/1205770721173533/1205771213627956
The transactions should only be committed if they were successful. This PR modifies on_success method in jstz_proto executor, and checks status code received in a JsValue before committing transactions to KV storage. If transactions were unsuccessful, it rolls them back.
TODO
> Proto: Only commit transactions if they were successful

- docs/.vitepress/config.mjs
- docs/bridge.md
- jstz_cli/src/bridge/deposit.rs
**Related Tasks**: [Guide doc: Deposits](https://app.asana.com/0/1205770721173531/1205770721324127/f)
This PR:
- Adds some output for running `jstz bridge deposit`
- Adds a quick start for jstz's asset bridge and depositing using the CLI. 
Documentation is kept short as this is likely to change in the future. 
```sh
```
> Docs: Asset bridge and deposits

- jstz_cli/src/account/mod.rs
- jstz_cli/src/jstz.rs
- jstz_cli/src/main.rs
- jstz_node/src/services/accounts.rs
- jstz_proto/src/context/account.rs
https://app.asana.com/0/1205770721173533/1205771213624622
This PR adds code getter as a 'jstz account code' command. It also adds an endpoint for getting the code to the Jstz node.
```
jstz deploy --name cntr < counter.js
jstz run "tezos://cntr/"
jstz account code --account cntr
```
> Node: Code getter

- jstz_cli/src/account/mod.rs
- jstz_cli/src/jstz.rs
- jstz_node/src/services/accounts.rs
- jstz_proto/src/context/account.rs
https://app.asana.com/0/1205770721173533/1205771213624626
This PR adds ledger getter as a 'jstz account balance' command. It also adds an endpoint for getting the balance to the Jstz node.
```
jstz deploy --name cntr < counter.js
jstz run "tezos://cntr/"
jstz account balance
jstz account balance --account cntr
```
> Node: Ledger getter

- .envrc
- .gitignore
Allows the Flake to build in parallel when used in direnv.
> direnv: Faster flake

- examples/encoding.js
- jstz_api/src/encoding/global.rs
- jstz_api/src/encoding/mod.rs
- packages/jstz-types/index.d.ts
> API: global atob/btoa functions

- Cargo.lock
- Cargo.toml
- crates/jstz_api/src/url/mod.rs
- crates/jstz_api/tests/wpt.rs
- crates/jstz_cli/Cargo.toml
- crates/jstz_cli/src/main.rs
- crates/jstz_cli/src/repl.rs
- crates/jstz_cli/src/run.rs
- crates/jstz_core/Cargo.toml
- crates/jstz_core/src/runtime.rs
- crates/jstz_kernel/Cargo.toml
- crates/jstz_proto/Cargo.toml
- crates/jstz_proto/src/error.rs
- crates/jstz_proto/src/executor/contract.rs
- crates/jstz_proto/src/operation.rs
- examples/loop.js
- nix/jstz.nix
This pr adds a global gas limit to jstz operations.
**Related Tasks**: [Add Gas To Transactions](https://app.asana.com/0/1205770721173531/1205771213629383/f) 
* Boa's existing instruction count used as a basic gas model
* Gas can be limited through the run contract transaction (default is `usize::MAX`)
* repl is always supplied with maximum amount of gas
``` bash
cargo run --bin jstz -- deploy < examples/loop.js
tz4_loop=`pbpaste` # copy new address to clipboard
cargo run --bin jstz -- run  "tezos://`tz4_loop`?iterations=10" $tz4 --gas-limit 500 # OK, we've got enough gas
cargo run --bin jstz -- run  "tezos://`tz4_loop`?iterations=100" $tz4 --gas-limit 500 # Error: GasLimitExceeded
```
> Proto: Coarse gas model

- docs/api/encoding.md
- docs/api/index.md
- docs/api/text_decoder.md
- docs/api/text_encoder.md
**Related issue**: closes #90 closes #111 closes #125 
```sh
```
> Doc: encoding API documentation

- crates/jstz_api/src/console.rs
- crates/jstz_node/src/services/logs/mod.rs
This PR addresses some comments in the last PR of the same name, which I merged without actually pushing the changes 🤦
> Health: Fix Panics (low hanging fruit)

- .github/workflows/ci.yml
- Cargo.lock
- crates/jstz_cli/Cargo.toml
- crates/jstz_cli/src/repl.rs
https://app.asana.com/0/1205770721173533/1205771213627876
This PR adds syntax highlighting of Javascript in REPL. So far, the highlighting works so that the user write a code and after hitting enter it gets highlighted. Future PRs may change it so that it gets highlighted as it is written.
Additionally this PR changes the CI pipeline to remove the currently not working prettier check.
Writing something in repl (cargo run --bin jstz -- repl).
> CLI: Syntax highlighting

- crates/jstz_api/src/js_log.rs
- crates/jstz_proto/src/executor/contract.rs
- crates/jstz_proto/src/lib.rs
- crates/jstz_proto/src/request_logger.rs
[Add request logs](https://app.asana.com/0/1205770721173533/1206350698277900) 
This is the first step of the persistent logs feature as shown below: 
1. add request logs 
Before we store sf logs in the DB, we need to add logs indicating the start and end of smart function request.
2. define a sqlite db schmea, modify the jstz node to read the request logs in the kernel.log and flush both the request logs and the sf logs to the sqlite db
3. Add new endpoints to jstz node to enable fetching logs from the sqlite db #329
This PR adds logs before and after the smart function call to kernel.log.
e.g.
```
[JSTZ:SMART_FUNCTION:REQUEST_START] {"type":"Start","contract_address":{"Tz4":"tz49JARegq9s2CUcctLqmtapSK5jQ7E6kbrs"},"request_id":"6e6dbb8cd0d42bf132d7ce4577042654371dc9f00322c3baeff28a38ac641e …
```
> Proto: Add request logs

- Cargo.lock
- crates/jstz_cli/Cargo.toml
- crates/jstz_cli/src/repl.rs
- package-lock.json
https://app.asana.com/0/1205770721173533/1205771213627876
This PR adds instant highlighting in REPL. This instead of highlighting Javascript after hitting enter, highlights the code as it is written.
Writing something in repl (cargo run --bin jstz -- repl).
> CLI: Instant highlighting

- docs/.vitepress/config.mjs
- docs/api/index.md
- docs/api/url_pattern.md
**Related issue**: [Docs: URLPattern](https://github.com/trilitech/jstz/issues/101)
```sh
```
> docs: URL Pattern API

- .github/workflows/ci.yml
- examples/fa2/tsconfig.json
- examples/hello-world/tsconfig.json
- package-lock.json
- package.json
- packages/jstz-types/tsconfig.json
- packages/jstz/tsconfig.json
- tsconfig.json
Bumps prettier to 3.2.4 and re-enables the CI formatting (after formatting using prettier 3.2.4)
> chore(deps/npm): bump prettier from 3.1.1 to 3.2.4

- crates/jstz_cli/src/account.rs
- crates/jstz_cli/src/bridge/mod.rs
- crates/jstz_cli/src/logs/mod.rs
- crates/jstz_cli/src/logs/trace.rs
- crates/jstz_cli/src/main.rs
- crates/jstz_cli/src/sandbox/mod.rs
This PR simply improves the help messages of the existing commands. It additionally adds some emojis to the help messages.
```
cargo run --bin jstz -- help
```
> feat(cli): improve help messages and add emojis 😀

- Cargo.lock
- crates/jstz_api/src/js_log.rs
- crates/jstz_cli/Cargo.toml
- crates/jstz_cli/src/account.rs
- crates/jstz_cli/src/bridge/deposit.rs
- crates/jstz_cli/src/bridge/mod.rs
- crates/jstz_cli/src/config.rs
- crates/jstz_cli/src/deploy.rs
- crates/jstz_cli/src/kv.rs
- crates/jstz_cli/src/logs/mod.rs
- crates/jstz_cli/src/logs/trace.rs
- crates/jstz_cli/src/main.rs
- crates/jstz_cli/src/repl/mod.rs
- crates/jstz_cli/src/run.rs
- crates/jstz_cli/src/sandbox/daemon.rs
- crates/jstz_cli/src/sandbox/mod.rs
- crates/jstz_cli/src/term/logger.rs
- crates/jstz_cli/src/term/mod.rs
- crates/jstz_crypto/src/secret_key.rs
**Dependencies**: #361 
This PR adds debug logging and improves the overall log output of the CLI. Logging levels can be configured 
using the `JSTZ_LOG` environment variable.
All debug logs for commands should contain:
- The command and all flags / positional arguments
- The config on load and save, additionally the config file contents for debugging deserialization errors
- Any additional command-specific logs
> feat(cli): improve logging for commands

- crates/jstz_cli/src/docs.rs
- crates/jstz_cli/src/main.rs
- crates/jstz_cli/src/term/browser.rs
- crates/jstz_cli/src/term/mod.rs
**Dependencies**: #365 
This PR adds the `docs` command to the `jstz` CLI, which opens a browser page (from the terminal) to the `jstz` docs (hosted on github pages)
```
cargo run --bin jstz -- docs
```
> feat(cli): add `docs` command

- Cargo.lock
- crates/jstz_cli/Cargo.toml
- crates/jstz_cli/src/sandbox/daemon.rs
- crates/jstz_cli/src/term/logger.rs
- crates/jstz_rollup/src/bridge.rs
- crates/jstz_rollup/src/lib.rs
- crates/jstz_rollup/src/main.rs
**Dependencies**: #369 
`jstz sandbox start` now outputs:
```
__________
\  jstz  /
)______(
|""""""|_.-._,.---------.,_.-._
|      | | |               | | ''-.
|      |_| |_             _| |_..-'
|______| '-' `'---------'` '-'
)""""""(
/________\
`'------'`
.------------.
/______________\
0.1.0 https://github.com/trilitech/jstz
octez-node is listening on: http://127.0.0.1:18731
octez-smart-rollup-node is listening on: http://127.0.0.1:8932
jstz-node is listening on: http://127.0.0.1:8933
Tezos bootstrap accounts:
+---------------------------------------------------+---------------+--------------+
| Address                                           | XTZ Balance   | CTEZ Balance |
+===================================================+===============+==============+
| (bootstrap1) …
```
> feat(cli): add banner and useful user information to `sandbox start`

- crates/jstz_cli/src/sandbox/daemon.rs
**Dependencies**: #376 
Caches the `identity.json` file generated by `octez-node identity generate`. Improves performance of `sandbox start`. 
```
JSTZ_LOG=debug cargo run --bin jstz -- sandbox start
```
After running twice, you'll see a cache hit on the `identity.json`. You can then observe this in `~/.jstz/octez-node-identity.json`.
> perf(cli): cache `identity.json` when initializing `octez-node`

- docs/installation.md
Updated jstz docs/Installation.md with the latest installation steps.
> docs: update jstz installation doc

- crates/jstz_cli/src/jstz.rs
- crates/jstz_node/src/lib.rs
The logging was broken due to the refactoing / sandbox changes
Fix the url and the broadcaster
> Fix logging

- CONTRIBUTING.md
- crates/jstz_api/src/http/header.rs
- crates/jstz_api/src/kv.rs
- crates/jstz_cli/src/deploy.rs
- crates/jstz_cli/src/repl/debug_api/account.rs
- crates/jstz_cli/src/repl/mod.rs
- crates/jstz_cli/src/run.rs
- crates/jstz_node/src/services/accounts.rs
- crates/jstz_node/src/services/logs/db.rs
- crates/jstz_node/src/services/logs/mod.rs
- crates/jstz_proto/src/api/ledger.rs
- crates/jstz_proto/src/api/mod.rs
- crates/jstz_proto/src/api/smart_function.rs
- crates/jstz_proto/src/context/account.rs
- crates/jstz_proto/src/executor/mod.rs
- crates/jstz_proto/src/executor/smart_function.rs
- crates/jstz_proto/src/js_logger.rs
- crates/jstz_proto/src/operation.rs
- crates/jstz_proto/src/receipt.rs
- crates/jstz_proto/src/request_logger.rs
This PR renames any type or variable that refers to a smart function as a contract
```bash
git grep "\(C\|c\)"ontract
```
> Sam.finch/api/purge contracts

- Cargo.lock
- crates/jstz_cli/Cargo.toml
- crates/jstz_cli/src/run.rs
[Spinner](https://app.asana.com/0/1205770721173531/1206394772057380/f) 
Add a spinner when running sf
https://github.com/trilitech/jstz/assets/128799322/0272e14b-8689-4884-a399-e3fc05cb2f92
> CLI: Add spinner to jstz run 

- examples/deploy.js
- examples/display_request.js
- examples/fa2/README.md
- examples/fa2/src/index.ts
- examples/fa2/test/actor.ts
- examples/fa2/test/index.ts
- examples/headers.js
- examples/hello_world.js
- examples/nested_transactions.js
- examples/revert_transaction.js
- packages/jstz-types/index.d.ts
**Related Tasks**: [Update & Review existing examples](https://app.asana.com/0/1205770721173531/1206345416213100/f)
This PR updates the examples and the TypeScript jstz-types definitions so they should now work with the current version of jstz
Run the sandbox and deploy / run all the smart functions in examples/ :)
> fix(examples): update examples

- crates/jstz_cli/src/deploy.rs
- crates/jstz_cli/src/error.rs
- crates/jstz_cli/src/run.rs
- crates/jstz_proto/src/executor/smart_function.rs
- examples/error.js
https://tezos-dev.slack.com/archives/C061SSDBN69/p1708355347065219
The fix is simply to ensure that on a error after running `Script::invoke_handler`, we rollback the transaction.
This ensures the transaction is always well-balanced. 
```
$ cargo run --bin jstz -- deploy examples/error.js -n dev
% cargo run --bin jstz -- run tezos://<address>/
Running function at tezos://tz1WA5uGRMroDYXcr22gSCRrJ2QB9rWSP1Ne/...
✕  ERROR  TypeError: cannot convert 'null' or 'undefined' to object
````
> fix(proto): handle exceptions from smart functions

- Cargo.lock
- crates/jstz_core/Cargo.toml
- crates/jstz_core/src/runtime.rs
- examples/date.js
**Related Tasks**: [Enable datetime API](https://app.asana.com/0/1205770721173531/1205770721333457/f) 
```
jstz deploy examples/date.js -n dev --name date
jstz run tezos://date/ -n dev
```
> feat(core): add support for datetime hooks

- crates/jstz_cli/src/config.rs
Currently the octez path is stored as a string which defaults to "" (which is a bit strange).
Missing fields in the config will cause the sandbox to refuse to work.
**Related Tasks**: [Fix jstz configuration defaults](https://app.asana.com/0/1205770721173531/1206345416213107/f)
* `octez_path` is now stored as an option.
* Config fields equal to their default values are no longer stored and may be omitted making the config less fragile.
[Add jstz config command.](https://app.asana.com/0/1205770721173531/1206614216286655/f)
> feat(cli): use path for octez binaries and default missing config fields

- crates/jstz_cli/sandbox-params.json
- crates/octez/src/node.rs
This PR simply bumps the octez version used by the sandbox
Running the sandbox
> chore(deps/octez): bump octez version to be540a2

- docs/cli.md
[update cli doc](https://app.asana.com/0/1205770721173531/1206651719355746/f)
Updated the `cli.md`
#404
> Doc: update cli.md

- crates/jstz_cli/src/account.rs
- crates/jstz_cli/src/config.rs
- crates/jstz_cli/src/deploy.rs
- crates/jstz_cli/src/run.rs
- crates/jstz_cli/src/sandbox/daemon.rs
- crates/jstz_cli/src/sandbox/mod.rs
- crates/jstz_cli/src/utils.rs
https://app.asana.com/0/1205770721173533/1206577693474286
This PR includes account login and sandbox start in deploy. Additionally it simplifies messages and fixes a few bugs with config not being saved.
jstz deploy examples/counter.js
> feat(cli): deployment streamlined

- crates/jstz_cli/src/main.rs
https://app.asana.com/0/home/1205763124046660/1206577693474288
This adds space between commands and orders them.
jstz help
> feat(cli): help grouping

- crates/jstz_node/Dockerfile
- crates/jstz_node/src/services/logs/db.rs
- crates/jstz_rollup/Dockerfile
- crates/jstz_rollup/entrypoint.sh
- docker-compose.yml
**Related Tasks**: [Launch jstz on weeklynet](https://app.asana.com/0/1205770721173531/1206248430016623/f)
This PR makes several minor changes to the docker files (and the jstz-node) to run jstz in our GCP setup
Follow https://www.notion.so/trilitech/Runbook-Dogfooding-9d5b08c4f605497ba9093dac1c4de1d3?pvs=4
> build(docker): fix docker build for node and rollup

- examples/500_counter.js
- examples/500_nested_counter.js
- examples/async_500_counter.js
- examples/async_counter.js
- examples/async_error_counter.js
- examples/console.test.js
- examples/error_counter.js
- examples/error_nested_counter.js
- examples/fib.js
- examples/ledger.test.js
- examples/print_method.js
- examples/url.test.js
Adds all the updated and new examples I used during our QA testing
See QA testing document
> feat(examples): add all examples used by me in QA

- crates/jstz_cli/src/deploy.rs
- crates/jstz_cli/src/run.rs
**Related Tasks**: [Auto-login for `jstz run` not working](https://app.asana.com/0/1205770721173531/1206703424903111/f)
When not logged in:
```sh
jstz run tezos://non-existent/
```
> fix(cli): fix auto-login for `jstz run`

- crates/jstz_proto/src/executor/smart_function.rs
- examples/async_error.js
**Related Tasks**: [CLI hangs when running an async smart function that raises an error](https://app.asana.com/0/1205770721173531/1206703424903136/f), [Nested transaction isn't rolled back on failed async smart functions](https://app.asana.com/0/1205770721173531/1206682403155951/f) 
```sh
jstz sandbox start -d
jstz deploy --name async-error examples/async_error.js
jstz run tezos://async-error/
```
> fix(proto): rollback the transaction on rejected smart function promises

- crates/jstz_cli/src/bridge/deposit.rs
- crates/jstz_cli/src/config.rs
- crates/jstz_cli/src/sandbox/consts.rs
- crates/jstz_cli/src/sandbox/daemon.rs
- crates/jstz_cli/src/utils.rs
https://app.asana.com/0/1205770721173533/1206712613344550
https://app.asana.com/0/1205770721173533/1206712613344544
https://app.asana.com/0/1205770721173533/1206703424903095
These PR fixes several issues with jstz bridge - requiring -n dev flag,supporting bootstrap aliases, being able to deposit to a bootstrap account. It additionally improves error messages and does a small refactoring.
```
jstz bridge depost --from bootstrap1 --to alan --amount 1000000
```
> fix(cli): bridge network + errors fix

- scripts/install-jstz-cli.sh
https://app.asana.com/0/1205770721173533/1206736406986497
This PR adds an install script to  pull the docker CLI container from ghcr and prints a message to add an alias to bashrc or zshrc.
run install_docker_cli.sh
> feat(installation): docker install script

- docs/installation.md
https://app.asana.com/0/1205770721173533/1206736406986502
This PR adds documentation for simple installation using the installation script.
> feat(docs): installation from docker

- scripts/install-jstz-cli.sh
Adds weeklynet network config to the installer script
Having deleted / moved your `~/.jstz/config.json`, run:
```
source scripts/install-jstz-cli.sh
```
> feat: installer configures weeklynet

- .github/workflows/ci.yml
- .github/workflows/deploy-teztnet.yml
- .github/workflows/docker.yml
This PR fixes a bug in the deploy teztnets workflow + switches our versioning scheme to `YYYYMMDD` for automated weeklynet builds
> ci: deploy teztnets improvements

- crates/jstz_cli/sandbox-params.json
**Related Tasks**: #465 
This PR simply bumps the octez version used by the sandbox
Building octez from sources using the commit sha: ddfbb8d6
```sh
cd tezos && git checkout ddfbb8d6
nix-build -j auto
```
Running the sandbox (ensuring your config points to the newly built binaries)
> chore(deps/octez): bump octez to ddfbb8d6

- .github/ISSUE_TEMPLATE/bug.md
Simply adds a GitHub issue template for a bug report
> feat: add bug report template

- Cargo.lock
- Cargo.toml
- Makefile
- crates/jstz_crypto/src/signature.rs
- crates/jstz_node/Cargo.toml
- crates/jstz_node/src/lib.rs
- crates/jstz_sdk/Cargo.toml
- crates/jstz_sdk/src/lib.rs
- examples/dashboard/.gitignore
- examples/dashboard/index.html
- examples/dashboard/package.json
- examples/dashboard/src/main.tsx
- examples/dashboard/tsconfig.json
- examples/dashboard/tsconfig.node.json
- examples/dashboard/vite.config.ts
- package-lock.json
- package.json
- packages/jstz-sdk/index.ts
- packages/jstz-sdk/package.json
- packages/jstz-sdk/tsconfig.json
This PR adds:
- A wasm-based crate `jstz_sdk`, that compiles to a wasm-based JavaScript library (using `make build-sdk-wasm-pkg`)
- A TypeScript package `@tezos/jstz-sdk` which wraps around the wasm library
- An example `dashboard` app that uses the SDK (which you can run using `npm run dev`)
```
make build-sdk-wasm-pkg
cd examples/dashboard
npm run dev
```
> feat: add jstz-sdk package

- scripts/install-jstz-cli.sh
> feat: update installer for 2024-03-20 testnet

- crates/jstz_proto/src/context/account.rs
- crates/jstz_proto/src/executor/smart_function.rs
- crates/jstz_proto/src/operation.rs
- examples/fa2/src/index.ts
- `fa2`: prevent re-minting & log balances
- prefer `impl Display` over `impl ToString`
> fa2: log balance

- examples/headers.js
- examples/kv.js
- examples/response.js
Adds all the updated and new examples I used during our QA testing
See QA testing document
> feat(examples): sam's examples from qa

- scripts/install-jstz-cli.sh
The changes primarily update the rollup endpoint, the network name, and updates jstz to a more recent build (last
built this Wednesday). 
In order to use a build from the jstz-dev organisation, we'd first need to transfer our self-hosted GitHub runner (for building the images). 
```sh
source ./scripts/install-jstz-cli.sh
```
> chore: update installer to latest release and configure to use ghostnet

- Cargo.lock
- Cargo.toml
- crates/jstz_crypto/src/error.rs
- crates/jstz_crypto/src/hash.rs
- crates/jstz_crypto/src/lib.rs
- crates/jstz_crypto/src/public_key_hash.rs
- crates/jstz_crypto/src/secret_key.rs
- crates/jstz_crypto/src/signature.rs
- crates/jstz_kernel/src/inbox.rs
- crates/jstz_kernel/src/lib.rs
- crates/jstz_node/Cargo.toml
- flake.lock
- nix/jstz.nix
> feat(deps): bump to tezedge 0.6.0 pre-release

- docs/api/smart_function.md
programatically -> programmatically
> docs(api): update smart_function.md

- .github/ISSUE_TEMPLATE/api_doc.md
- README.md
- crates/jstz_cli/src/docs.rs
This PR changes existing links to the trilitech.github.io/jstz page to the new organisation's jstz-dev.github.io/jstz page
```sh
git grep -r trilitech.github.io
```
> fix: update doc links to point to jstz-dev.github.io

- .github/workflows/ci.yml
- Makefile
**Dependencies**: #535 
**Related Tasks**: [jstz-43](https://linear.app/tezos/issue/JSTZ-43/enable-unit-tests-on-ci)
A small PR to enable unit tests on CI. 
There are limitations to this, namely only _Rust_ unit tests are run (not LIGO ones). 
Green CI ✅ 🚀
> ci: run unit tests (for Rust)

- .github/workflows/ci.yml
- Makefile
- README.md
- codecov.yml
**Dependencies**: #536 
**Related Tasks**: [jstz-51](https://linear.app/tezos/issue/JSTZ-51/enable-code-coverage-in-ci)
Does what it says on the tin ☝️
> ci: add Codecov integration

- crates/jstz_cli/src/sandbox/daemon.rs
Jstz node endpoint should be reachable now.
> fix(sandbox): add yield point to join task

- .github/workflows/ci.yml
- Makefile
- crates/jstz_api/src/encoding/text_decoder.rs
- crates/jstz_api/src/encoding/text_encoder.rs
- crates/jstz_api/src/file/imp.rs
- crates/jstz_api/src/file/mod.rs
- crates/jstz_api/tests/wpt.rs
- crates/jstz_core/src/host.rs
- crates/jstz_core/src/kv/outbox.rs
- crates/jstz_core/src/kv/transaction.rs
- crates/jstz_core/src/runtime.rs
- crates/jstz_core/tests/transaction_test.rs
- crates/jstz_kernel/src/inbox.rs
- crates/jstz_kernel/src/lib.rs
- crates/jstz_node/src/services/logs/mod.rs
- crates/jstz_proto/src/executor/fa_deposit.rs
- crates/jstz_wpt/src/lib.rs
- crates/jstz_wpt/src/main.rs
- crates/jstz_wpt/src/serve.rs
- nix/crates.nix
Currently we use an oddly specific `clippy` configuration which doesn't encourage best
practices.
This PR simply uses the default configuration (hooked up with `nix`)
Green CI 🚀 
or running:
```sh
nix build .#checks.aarch64-darwin.cargo-clippy
```
> ci: use default clippy config with Nix

- crates/jstz_proto/src/executor/smart_function.rs
- crates/jstz_proto/src/executor/withdraw.rs
- scripts/pre-commit-hook.sh
Adds linting to pre-commit hook
> chore(pre-commit-hook): add linting to pre-commit hook

- crates/jstz_api/src/http/request.rs
- crates/jstz_api/src/http/response.rs
- crates/jstz_proto/src/api/smart_function.rs
- crates/jstz_proto/src/executor/mod.rs
- crates/jstz_proto/src/executor/smart_function.rs
Implements withdraw native from smart function call. 
```
cargo test -p jstz_proto api::smart_function
```
> feat(withdrawal): implement native withdrawal in smart function calls

- crates/jstzd/src/task/directory.rs
- crates/jstzd/src/task/endpoint.rs
- crates/jstzd/src/task/octez_client.rs
[Task](https://linear.app/tezos/issue/JSTZ-131/implement-octezclientcommand)
blocking #577 
add command for octez client. 
added unit test for command
added unit test for directory
> Leo client command

- flake.nix
Required to build and expose jstz sdk in javascript.
```
make build-sdk-wasm-pkg
```
> feat(nix): add wasm-pack for building jstz sdk

- Cargo.lock
- crates/jstzd/src/task/mod.rs
- crates/jstzd/src/task/octez_client.rs
- crates/jstzd/src/task/octez_node.rs
- crates/jstzd/tests/octez_client_test.rs
- crates/jstzd/tests/octez_node_test.rs
- crates/octez/Cargo.toml
- crates/octez/src/async_node.rs
- crates/octez/src/endpoint.rs
- crates/octez/src/lib.rs
- crates/octez/src/node_config.rs
Closes JSTZ-116.
[JSTZ-116](https://linear.app/tezos/issue/JSTZ-116/implement-octeznode)
Implement the suggestion in https://github.com/jstz-dev/jstz/pull/588#discussion_r1803429789. Also moved `Endpoint` to crate octez.
All existing tests should pass.
> feat(jstzd): use Endpoint in octez node config

- crates/jstzd/src/protocol/mod.rs
- crates/jstzd/src/task/child_wrapper.rs
- crates/jstzd/src/task/directory.rs
- crates/jstzd/src/task/mod.rs
- crates/jstzd/src/task/octez_baker.rs
- crates/jstzd/src/task/octez_client.rs
- crates/jstzd/src/task/octez_node.rs
- crates/jstzd/tests/octez_baker_test.rs
- crates/jstzd/tests/octez_client_test.rs
- crates/jstzd/tests/utils.rs
[Octez baker](https://linear.app/tezos/issue/JSTZ-117/implement-octezbaker)
* moved the child_wrapper into a separate file
* implement baker config builder
* implement baker node and the task trait
* baker node integration test
* baker config builder unit test
* test for child wrapper
> octez baker

- crates/jstzd/src/task/octez_node.rs
- crates/jstzd/tests/octez_client_test.rs
- crates/jstzd/tests/utils.rs
- crates/octez/src/async/directory.rs
improve the directory by implementing `From<&Directory>` instead of `TryFrom<&Directory>`
add unit tests
> refactor(jstzd): implement From<PathBuf> for Direcotry

- crates/jstzd/src/task/octez_node.rs
- crates/octez/src/async/node.rs
> refactor(octez): remove async from node

- crates/jstzd/tests/octez_client_test.rs
- crates/jstzd/tests/protocol_test.rs
- crates/jstzd/tests/utils.rs
- crates/octez/src/async/protocol.rs
Part of JSTZ-149.
[JSTZ-149](https://linear.app/tezos/issue/JSTZ-149/implement-protocol)
Integration tests for `ProtocolParameters`. Also added a few missing bits in previous PRs.
* Integration test: one new test case
```sh
$ cargo test --test protocol_test
running 1 test
< ...baker logs >
test protocol_parameters ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 5.37s
```
> test(jstzd): integration test for protocol params

- crates/octez/src/async/bootstrap.rs
- crates/octez/src/async/protocol.rs
Part of JSTZ-149.
[JSTZ-149](https://linear.app/tezos/issue/JSTZ-149/implement-protocol)
Replace `try_from` with de/serialize implementation for BootstrapAccount as done in #576.
```sh
$ cargo test --lib async::bootstrap::tests::deserialize_bootstrap_account
running 6 tests                                                                                                                                                       
test r#async::bootstrap::tests::deserialize_bootstrap_account_value_out_of_range ... ok                                              
test r#async::bootstrap::tests::deserialize_bootstrap_account ... ok              
test r#async::bootstrap::tests::deserialize_bootstrap_account_invalid_balance_type ... ok
test …
```
> fix(octez): implement de/serialize for bootstrap account

- crates/jstzd/tests/octez_client_test.rs
- crates/jstzd/tests/sandbox-params.json
- crates/octez/src/async/client.rs
call contract:
[leounoki-jstz-139](https://linear.app/tezos/issue/JSTZ-139/implement-octezclientcall-contract)
transfer:
[leounoki-jstz-138](https://linear.app/tezos/issue/JSTZ-138/implement-octezclienttransfer)
This PR implements the private method `transfer` and a public method `call_contract` on top of the transfer.
Unit tests for transfer options builder and integration test for call_contract
> feat(jstzd): call contract

- crates/jstzd/tests/protocol_test.rs
- crates/octez/src/async/protocol.rs
Completes JSTZ-149.
[JSTZ-149](https://linear.app/tezos/issue/JSTZ-149/implement-protocol)
Adds two checks for bootstrap accounts in the parameter set:
* there must be at least one bootstrap account
* at least one bootstrap account needs to have at least 6000 tez
Adding these two specific checks here because the error message from octez client is pretty useless. I think these are pitfalls that users might easily run into and it would definitely help if we catch the errors before the parameter file goes to the octez executables. The issue probably not going to happen using the template parameter file included in jstz because we will put some well funded accounts there, but it can occur when users use their own parameter file as the base.
```sh
$ cargo test …
```
> feat(octez): add checks for bootstrap accounts in parameters

- Cargo.lock
- crates/jstz_api/Cargo.toml
- crates/jstz_api/src/kv.rs
- crates/jstz_node/openapi.json
- crates/jstz_node/src/services/accounts.rs
Implements OpenAPI for `AccountsService`
Adds `utoipa::path` annotation to `AccountsService` handlers.
Generate updated openapi schema
This PR does not make changes to the logic. OpenAPI schema can be checked with
```
cargo test -p jstz_node api_doc_regression
```
> Jstz-157: implement openapi for accounts service

- Cargo.lock
- crates/jstz_node/src/config.rs
- crates/jstz_node/src/lib.rs
- crates/jstzd/Cargo.toml
- crates/jstzd/src/task/jstz_node.rs
- crates/jstzd/src/task/mod.rs
- crates/jstzd/tests/jstz_node_test.rs
[JSTZ-190: implement task for `JstzNode`](https://linear.app/tezos/issue/JSTZ-190/implement-task-for-jstznode)
Next step:
[spwan rollup node](https://linear.app/tezos/issue/JSTZ-164/spawn-octezrollupnode-in-jstzd)
[JSTZ-165: Spawn `JstzNode` in Jstzd](https://linear.app/tezos/issue/JSTZ-165/spawn-jstznode-in-jstzd)
* add health check endpoint to jstz node `/ping`
* add jstz_node config
* implement task for jstz_node
* add integration test
> JSTZD: implement Task for jstz node

- crates/jstzd/src/task/jstzd.rs
- crates/jstzd/tests/jstzd_test.rs
Part of JSTZ-121.
Added route `/shutdown` to `JstzdServer` that turns off everything on request. This closes the server as well. Not quite sure if this is always the case, but it seems that the server shuts down itself after replying to the `PUT /shutdown` request, so such requests get a response rather than fail.
* Integration test: updated `crates/jstzd/tests/jstzd_test.rs` to use the shutdown endpoint and check if calling `stop` afterwards gives errors
> feat(jstzd): implement shutdown endpoint in jstzd server

- .github/workflows/generate-node-client.yml
Removes client generation from pull requests that was missed in [previous PR](https://github.com/jstz-dev/jstz/pull/644)
> fix(ci): remove generate client from pr

- crates/octez/src/async/node_config.rs
Implement `Serialize` for `OctezNodeConfig ` so that it can be dumped in JSON.
Added unit tests.
> feat(octez): implement serialize for octez node config

- crates/octez/src/async/protocol.rs
> feat(octez): serialise protocol

- crates/octez/src/async/baker.rs
> feat(octez): serialise baker config

- crates/octez/src/async/endpoint.rs
> feat(octez): implement deserialize for endpoint

- crates/octez/src/async/baker.rs
Deserialize baker path through FromStr.
> feat(octez): deserialise baker path

- crates/octez/src/async/node_config.rs
Deserialize OctezNodeHistoryMode through FromStr.
> feat(octez): implement deserialize for OctezNodeHistoryMode

- crates/octez/src/async/directory.rs
Refactoring the direcotry in preparation for [the symlink task](https://linear.app/tezos/issue/JSTZ-207/symlink-for-rollup-preimages)
Implemented AsRef<OsStr> for Direcotry. 
there's already a blanket implementation in the standard library that converts any AsRef<OsStr> into a PathBuf so i could remove implementing for the external library PathBuf.
added unit test
> JSTZD: implement AsRef<OsStr> for direcotry

- crates/jstz_node/stainless.yml
Missed updating stainless config in the previous PR
Updates stainless config
> feat(node): update stainless for hash endpoint

- crates/jstzd/src/task/octez_rollup.rs
[use symlink instead of copy for rollup preimages](https://linear.app/tezos/issue/JSTZ-207/symlink-for-rollup-preimages)
* Use symlink instead of copying all the preimages
the rollup test passess meaning the preimages are used correctly
> feat(jstzd): use symlink for rollup

- crates/jstzd/src/config.rs
- crates/jstzd/src/task/jstzd.rs
[use jstz kernel in config](https://linear.app/tezos/issue/JSTZ-238/use-jstz-rollup-kernel-in-configrs)
* move some of the const values in config.rs 
* replace the dummy rollup with jstz rollup
add unit test to check if the rollup config is correctly set
```
cargo test --package jstzd --lib -- config::tests::build_config --exact --show-output
```
> feat(jstzd): add jstz rollup to config

- crates/octez/src/async/file.rs
Implement `Display` and `Serialize` for `FileWrapper`. This allows log file paths of nodes to be serialised along with jstzd config.
* Unit test: new test cases added
```sh
$ cargo test --lib async::file::tests::serialize
running 2 tests
test r#async::file::tests::serialize_file ... ok
test r#async::file::tests::serialize_tempfile ... ok
test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 104 filtered out; finished in 0.01s
$ cargo test --lib async::file::tests::display
running 2 tests
test r#async::file::tests::display_tempfile ... ok
test r#async::file::tests::display_file ... ok
test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 104 filtered out; finished in 0.00s
```
> feat(octez): serialize file wrapper

- crates/octez/src/async/file.rs
Implement partialeq for file wrapper. This is required for #714.
> feat(octez): implement partialeq for file wrapper

- crates/octez/src/async/client.rs
Write octez-client logs to a log file instead of stdout/stderr.
Ran jstzd locally and did not see any octez-client logs.
> feat(octez): write client log to file

- crates/jstz_core/src/kv/transaction.rs
in preparation for [adding new account type](https://linear.app/tezos/issue/JSTZ-257/introduce-new-account-type)
implement `or_insert_with` for Entry in transaction.rs. this will be used later when adding a new account type. 
Note:
I implemented `or_insert_with` that takes a function rather than `or_insert` to avoid having to initialize the default value for lazy evaluation
added unit tests
> feat(jstz_core): implement or_insert_with for entry

- crates/jstzd/src/task/jstzd.rs
Part of JSTZ-248.
[JSTZ-248](https://linear.app/tezos/issue/JSTZ-248/revise-jstz-cli-so-that-it-works-with-jstzd)
Change keys in the serialised form of jstzd config to snake case for consistency since keys to all other config values are in snake case.
* Unit test: added one test case
> feat(jstzd): change jstzd config keys to snake case

- crates/jstz_node/src/services/logs/broadcaster.rs
- crates/jstz_node/src/services/logs/db.rs
- crates/jstz_node/src/services/logs/mod.rs
[task link](https://linear.app/tezos/issue/JSTZ-266/use-newaddress-for-jstz-node)
introduce the new address type in jstz node
this should be tested after the run command is fixed
> jstz_node: migrate to new_address

- crates/jstzd/src/config.rs
- crates/octez/src/async/node_config.rs
Closes JSTZ-276.
[JSTZ-276](https://linear.app/tezos/issue/JSTZ-276/run-octez-node-in-rolling-mode-by-default)
Set the default history mode for octez node in jstzd to `rolling:15`. This makes octez node keep a bit more context and should reduce the chance of the rollup node falling into degraded mode when it takes too much time loading the kernel. With the current sandbox parameters, octez node should keep data within a 2-minute window with `rolling:15`, which should be sufficient for the rollup node.
Some changes are made to the octez crate. I put them in this PR as well since those are trivial getter implementations.
* Unit test: added tests
```sh
$ cargo test --lib config::tests::patch_octez_node_config
running 1 test
test config::tests::patch_octez_node_config ... ok
test result: ok. …
```
> feat(jstzd): set default history mode for octez node

- crates/jstz_node/openapi.json
- crates/jstz_node/src/services/accounts.rs
- crates/jstz_node/src/services/operations.rs
- crates/jstz_node/stainless.yml
- crates/jstz_proto/src/context/new_account.rs
This PR flattens the client apis for better UX and discoverability.
Once merged, the [Next PR](https://github.com/jstz-dev/jstz-client/pull/15) should be merged on jstz-client.
* Update `stainless.yml` with a flatter api and model structure. The methods will be generated under the Resource and bounded to the specified http endpoint
* Added a get account endpoint for completeness 
Generated code can be [inspected here](https://github.com/jstz-dev/jstz-client/pull/15) although its not particularly helpful because I mistakenly merged the histories eagerly while testing.
> feat(client): flatten client api

- docs/.vitepress/config.mjs
- docs/api/ledger.md
- docs/api/url.md
- docs/jstzd.md
- docs/quick_start.md
* add jstzd doc
* update from tz1 to KT1 accordingly
> Update jstz doc

- crates/jstz_node/stainless.yml
- package-lock.json
- packages/sdk/index.ts
- packages/sdk/package.json
> fix(client-lib): use http instead of https by default

- docs/installation.md
- docs/quick_start.md
update docs.
use --contianer in quick start
update installtaion
> docs: update installation

- Cargo.lock
- Makefile
- crates/jstz_cli/src/account.rs
- crates/jstz_cli/src/bridge/withdraw.rs
- crates/jstz_cli/src/deploy.rs
- crates/jstz_cli/src/main.rs
- crates/jstz_cli/src/run.rs
- crates/jstz_cli/src/utils.rs
- crates/jstz_kernel/src/lib.rs
- crates/jstz_mock/Cargo.toml
- crates/jstz_mock/src/host.rs
- crates/jstz_proto/src/api/smart_function.rs
- crates/jstz_proto/src/executor/fa_deposit.rs
- crates/jstz_proto/src/executor/smart_function.rs
- examples/get-tez/index.ts
- examples/show-tez/package-lock.json
- examples/show-tez/package.json
- examples/show-tez/src/index.ts
- examples/show-tez/tsconfig.json
- examples/show-tez/webpack.config.js
* Add show-tez cli app
* Fixes bug where account is not debited when smart function is created with initial amount
* Make headers optional in cli response
> Demo: show tez demo and chores

- crates/jstz_cli/src/sandbox/mod.rs
- docs/.vitepress/theme/style.css
- docs/installation.md
- docs/quick_start.md
- examples/get-tez/index.ts
- examples/show-tez/package-lock.json
- examples/show-tez/package.json
- examples/show-tez/src/index.ts
- packages/cli/main/package.json
Deploying latest bug fix for eng monthly demo
* Bump jstzd version in cli
* Tag commit
> feat(release): 0.1.1-alpha.0

- docs/quick_start.md
So that users can just copy and paste
> fix(doc): update kt1 address in quick start

- crates/jstzd/src/config.rs
- crates/jstzd/src/task/jstzd.rs
Closes JSTZ-299.
[JSTZ-299](https://linear.app/tezos/issue/JSTZ-299/add-more-bootstrap-accounts)
Added more bootstrap accounts in jstzd so that jstzd is consistent with the old sandbox. There are 6 bootstrap accounts: `bootstrap0` to `bootstrap5`. Each account has 100k tez initially.
Note that in this PR the account `activator` is replaced by `bootstrap0`. The rollup activator account is still `bootstrap1`.
* Unit test: updated existing tests
* Manual run: ran jstzd locally and observed the new bootstrap accounts
> feat(jstzd): add more bootstrap accounts

- crates/jstz_api/tests/wpt.rs
- crates/jstz_api/tests/wptreport.json
Enable test suites for Blob ([interface](https://w3c.github.io/FileAPI/#dfn-Blob), [class](https://nodejs.org/docs/v22.13.1/api/buffer.html#class-blob)).
```sh
```
> feat(wpt): enable blob tests

- docs/quick_start.md
Reviewing the quickstart
Some review comments and clarifications for the quickstart and some updates based on going through it today. I kept most of the style.
Run the docs with `npm run docs:dev` and view http://localhost:5173/jstz/quick_start.html in a browser.
> fix(docs): review and edit quickstart

- crates/jstz_proto/src/api/smart_function.rs
- crates/jstz_proto/src/executor/smart_function.rs
[task link](https://linear.app/tezos/issue/JSTZ-300/add-support-for-no-op)
This PR decouples the transfer and the execturion of sf via the `/-/noop` url path.
`run tezos://KT1.../-/noop` now enables just handling the transfer (if any) without executing the sf
check the URL path and skip the execution if the `noop` is in the path.
added unit tests to check the noop  behaviour
cargo test -p jstz-proto
> Leounoki jstz 300/request noop

- docs/.vitepress/config.mjs
- docs/accounts.md
This is a pretty basic topic but I thought it was needed. Just basic info on accounts that we can add to as the functionality expands.
> feat(docs): basic topic on accounts

- docs/api/kv.md
- docs/functions/data_storage.md
Just some clarifications around data storage based on research and experimentation.
- Clarify KV reference topic in the API
- Add info on accessing keys and subkeys via the CLI
-
> fix(docs): clarify info about data storage

- crates/jstz_cli/src/bridge/deposit.rs
Part of JSTZ-399.
[JSTZ-399](https://linear.app/tezos/issue/JSTZ-399/make-sure-that-cli-config-works-when-users-switch-between-native-and)
Previously, for deposit commands, CLI always called octez client to perform corresponding operations. This does not work with the containerised sandbox because it's a bit troublesome keeping track of the octez base directory that contains necessary data, so a `container` flag in the sandbox config was created and CLI goes through the exposed jstzd endpoint to tell octez client in the container to perform such operations. This gets a bit messy and difficult to maintain.
Make CLI deposit command always go through jstzd in the dev environment to mitigate the issue above.
Ran the sandbox (both in the host environment and in a container) locally and …
> fix(cli): always deposit through jstzd in sandbox

- crates/jstzd/src/task/jstzd.rs
Part of JSTZ-399.
[JSTZ-399](https://linear.app/tezos/issue/JSTZ-399/make-sure-that-cli-config-works-when-users-switch-between-native-and)
Normally, when it comes to layer 1 operations, CLI always calls octez-client to perform them. This does not work with the containerised sandbox because it's a bit troublesome keeping track of the octez base directory that contains necessary data, so a container flag in the sandbox config was created and CLI goes through the exposed jstzd endpoint to tell octez client in the container to perform such operations. This gets a bit messy and difficult to maintain.
Create a new endpoint in jstzd server that resolves L1 account aliases in the sandbox. This allows CLI to get L1 account aliases in the sandbox without having to call octez-client.
```
GET …
```
> feat(jstzd): resolve L1 account aliases

- README.md
Current installation instructions require you to build from source.
Update installation instructions to show that you can now install via npm.
> fix(docs): update install to use npm

- crates/jstz_cli/src/main.rs
- docs/.vitepress/config.mjs
- docs/api/ledger.md
- docs/cli.md
- docs/transfer.md
[task](https://linear.app/tezos/issue/JSTZ-340/update-transfer-api-doc)
> docs(proto,cli): update docs for transfer

- docs/quick_start.md
- examples/get-tez/index.ts
- examples/show-tez/src/index.ts
Per request, some clarifications to the quickstart and comments in the example applications that it uses
> fix(doc): clarifications to the quickstart and samples

- crates/jstz_node/openapi.json
- crates/jstz_node/src/config.rs
- crates/jstz_proto/src/executor/mod.rs
- crates/jstz_proto/src/operation.rs
just renaming the 
`ReealLargePayloadOperation` to `RevealLargePayload` for consistency
> rename rlp operation

- examples/zod/index.ts
- examples/zod/package-lock.json
- examples/zod/package.json
- examples/zod/tsconfig.json
simply adds example large smart function that uses zod. 
This smart function was used in the demo.
> add example smart function

- crates/jstz_cli/src/config.rs
- crates/jstz_cli/src/sandbox/container.rs
Completes JSTZ-421.
[JSTZ-421](https://linear.app/tezos/issue/JSTZ-421/clean-up-sandbox-config)
Remove `SandboxConfig`. Some other things are marked with `allow(unused)` or `_` for now just to keep this PR simple. Those things will be cleaned up later.
The sandbox still works locally.
> refactor(cli): remove sandbox config

- crates/jstz_runtime/src/runtime.rs
We need to pass arguments (eg. Request) to the default handler
* Make default handler global so that the returned `Promise` can be translated into `async`
* Add arguments to handler
* Make `init_test_setup!` more flexible by allow bounded variables to be optional
`cargo nextest run -p jstz_runtime --features skip-wpt`
> feat(runtime): support args in call default handler

- crates/jstz_runtime/src/ext/jstz_console/mod.rs
- crates/jstz_runtime/src/ext/jstz_kv/mod.rs
- crates/jstz_runtime/src/lib.rs
- crates/jstz_runtime/src/runtime.rs
- crates/jstz_runtime/src/sys/interfaces/headers.rs
- crates/jstz_runtime/src/sys/interfaces/request.rs
- crates/jstz_runtime/src/sys/interfaces/response.rs
Accidentally missed this commit + updating new tests to use the updated macro
> feat(runtime): make binded properties optional in init_test_setup!

- crates/jstz_proto/README.md
add README on how large smart function works . 
The original design doc is [here](https://docs.google.com/document/d/1iualFbxEMdvxLW2xQeq7-8Batxu4eBL3s5bomrqkIy4/edit?usp=sharing)
> docs(proto): add README

- crates/jstz_cli/src/account.rs
- crates/jstz_cli/tests/account.rs
Completes JSTZ-486.
[JSTZ-486](https://linear.app/tezos/issue/JSTZ-486/overwrite-accounts-with-cli)
Add one flag `--force` to CLI account creation. This allows users to overwrite a known account alias. For example,
```sh
$ jstz account create foo
...
User created with address: tz1g3cNkswYeUCL9E5ZCuKhLiLSd1jb2r75d
$ jstz account create foo
✕  ERROR  The account 'foo' already exists. Please choose another name.
$ jstz account create foo --force
...
User created with address: tz1hqQUmReRZcWvKqNnCxdjPiaxja14xB5SQ
```
Updated the relevant integration test.
> feat(cli): force account creation

- crates/jstz_cli/src/main.rs
quick fix on the CLI `run` and `transfer` command
> fix(cli): update emoji

- crates/jstz_runtime/src/ext/jstz_console/mod.rs
- crates/jstz_runtime/src/ext/jstz_fetch/mod.rs
- crates/jstz_runtime/src/ext/jstz_kv/mod.rs
- crates/jstz_runtime/src/lib.rs
- crates/jstz_runtime/src/runtime.rs
- crates/jstz_runtime/tests/wpt.rs
Makes the purpose of Protocol clearer
Renames `Protocol` to `ProtocolContext`
Only renames
> chore(runtime): rename Protocol to ProtocolContext

- crates/jstz_core/src/kv/transaction.rs
While debugging some tests, I found a fatal error in our transaction implementation. 
Namely it was possible to access snapshot indices that should've been committed (resulting in an 
index out of bounds panic)
The fix is to ensure the snapshot indices are correctly rolledback before inserting the updated snapshot index
when committing. 
To reproduce the error, apply this patch and run the test below:
```patch
diff --git a/crates/jstz_core/src/kv/transaction.rs b/crates/jstz_core/src/kv/transaction.rs
index 91912b65..d47ceeae 100644
--- a/crates/jstz_core/src/kv/transaction.rs
+++ b/crates/jstz_core/src/kv/transaction.rs
@@ -366,13 +366,13 @@ where {
if let Some(prev_ctxt) = self.stack.last_mut() {
// TODO: These clones are probably uncessary since the entry of btree will always be …
```
> fix(core): ensure transaction snapshot idxs are correctly removed on commit

- crates/jstz_node/src/services/accounts.rs
Part of JSTZ-601.
[JSTZ-601](https://linear.app/tezos/issue/JSTZ-601/expose-runtime-db-with-jstz-node-api)
Jstz node API needs to return data from runtime db when jstz node runs in sequencer mode.
Updated the handler of `/accounts/<address>/kv` such that it returns data from the runtime db when jstz node runs in sequencer mode.
> feat(sequencer): read kv from db

- crates/octez/src/async/node_config.rs
Part of JSTZ-709.
[JSTZ-709](https://linear.app/tezos/issue/JSTZ-709/set-activator-account-properly)
We need a mechanism to rotate bootstrap accounts while making sure that octez node can still activate the protocol successfully.
Added one option `sandbox_config_path` to `OctezNodeRunOptions` to allow users to customise their sandbox. Octez node has this option `--sandbox` for `octez-node run`. This option accepts a path to a json file that records some fundamental config values. This will allow us to customise the sandbox environment, including altering the activator account.
* Unit testing: updated relevant tests.
* Manual testing: ran octez node with a designated path and observed that it could activate the protocol and proceed with a different activator account.
> feat(octez): set run node option 'sandbox'

- crates/jstz_proto/src/runtime/v2/oracle/oracle.rs
Closes https://linear.app/tezos/issue/JSTZ-701/fn-respond 
Adds mechanism to respond to oracle requests
Responding involves sending response via the one shot sender channel. In addition, the oracle request must be cleaned up from storage and the sender removed from internal sender state.
`cargo nextest run -p jstz_proto oracle --features v2_runtime --nocapture`
> feat(oracle): add respond

- crates/jstz_proto/src/runtime/v2/oracle/oracle.rs
Closes https://linear.app/tezos/issue/JSTZ-532/implement-requestqueue 
Needed to GC stale requests
This PR extends the senders map with a timeout value. The field has been renamed to `active_requests` and value has been re-typed to `ReqeustMetadata`. 
We use the fact that BTreeMap is an ordered Map and that RequestId is created in an incremental order. This guarantees that the order of request ids determines the order of timeouts. Hence, the first entry of the BTreeMap will be next request to time out.
Expose `gc_timeout_requests` which will garbage collect timed out requests. Senders which are drop will send a cancellation to receivers which will cause fetch to return timeout
`make test-v2`
> feat(orace): support timeout queue

- README.md
- docs/alpha-tester.md
> propose more BC features to the alpha tester examples

- docs/installation.md
Just to clarify the install instructions. They seem to work for me.
> fix(docs): update and clarify install and build instructions

- crates/jstz_node/src/services/operations.rs
The inject inbox endpoint in jstz node stopped working since it was not updated in #1234 and #1263.
Updated the endpoint handler `inject_inbox_messages` so that it works again.
Built jstz node locally and confirmed that the endpoint worked again.
> fix(jstz_node): fix inject inbox

- crates/jstz_utils/src/inbox_builder.rs
Nightly TPS test [failed](https://github.com/jstz-dev/jstz/actions/runs/17059803849/job/48364400091) from [61e9964](https://github.com/jstz-dev/jstz/commit/61e99648954c67fd718b5ea70e18e0ff00a13d3b).
Updated the inbox builder such that it does not build one "start of level" message at the very beginning.
Ran the TPS test locally and confirmed that it worked normally.
> fix(bench): do not init inbox builder with start level

- crates/jstz_node/src/storage_sync.rs
Part of: [JSTZ-812](https://linear.app/tezos/issue/JSTZ-812/implement-storageupdate-consumer-in-jstz-node)
Next PR: #1291 
We need to shutdown the jstz node in case storage sync dies, this PR is a preparation step for it.
* Adds a death signal so that the caller can know when storage sync dies
* Implement a future to `StorageSync` so that when `StorageSync` dies it resolves (check #1291  on how it's used)
unit tests
```
cargo test --package jstz_node --lib --features v2_runtime -- test::server_dies_when_storage_sync_dies --exact --show-output
```
>  feat(jstz_node): add death signal to storage sync

- crates/jstz_node/src/lib.rs
- crates/jstz_node/src/storage_sync.rs
Close: [JSTZ-812](https://linear.app/tezos/issue/JSTZ-812/implement-storageupdate-consumer-in-jstz-node)
The next step is to enable it for sequencer.
* Integrates the stroage sync to jstz node on default mode
* When storage sync fails, jstz node server stops as well
Unit test:
```
cargo nextest run -p jstz_node --lib --features v2_runtime
```
Manually tested by running the example counter sf and checking the kv. 
```
cargo run --bin jstz run jstz://KT1MHBBWr86UevdoSy3J8asShrTc4SDFapoG/increment --network dev -t
cargo run --bin jstz kv get -a KT1MHBBWr86UevdoSy3J8asShrTc4SDFapoG myNumber -n dev
```
where the jstzd config is
```
{
"octez_rollup": {
"history_mode": "archive"
},
"jstz_node" : {
"storage_sync": true
}
}
```
> feat(jstz_node): integrate storage sync

- crates/jstz_node/src/lib.rs
Closes: [899](https://linear.app/tezos/issue/JSTZ-899/integrate-storage-sync-for-sequencer)
The sequencer should be able to sync storage updates even when running in RISC-V mode. Currently, storage syncing only works on default mode. This PR extends the functionality so that kernel storage update events can be consumed by the sequencer in RISC-V mode as well.
* Added support for storage sync in sequencer RISC-V mode.
* The sequencer now listens for kernel storage update events and applies them to its local state `storage_sync_db`.
Note: the StoreWrapper continues to read from runtime_db, not storage_sync_db. The eventual synchronization between the sequencer’s debug_file and runtime_db will be handled separately once RISC-V integration is complete.
Testing
* Existing unit tests have been …
>  feat(sequencer): enable storage sync

- crates/jstz_node/src/sequencer/inbox/mod.rs
The sequencer inbox monitor was processing the msgs in the wrong order, this PR fixes it.
* Fix the process_inbox_message to respect the inbox msgs order 
* Fixed the test to test for operation order 
Fixed existing unit tests
> fix(sequencer): process inbox msgs in order

- crates/jstz_proto/src/runtime/v2/fetch/fetch_handler.rs
Closes https://linear.app/tezos/issue/JSTZ-848/withdrawal-gives-unexpected-error 
Updates the error message for withdrawals. The error is expected because withdrawals are unsupported in RISC-V
```
$ jstz bridge deposit --from bootstrap1 --to test --amount 10 --network dev     
Deposited 10 XTZ from bootstrap1 to test
$ jstz bridge withdraw --to tz1PDC1CYZgaQjw7ayooQu8iycSYNfigsY2A --amount 1 -n dev
Withdrawals are not supported yet
```
> chore: rewrite withdraw unsupported message

- crates/jstz_cli/src/network.rs
- crates/jstz_cli/tests/network.rs
Part of JSTZ-783.
[JSTZ-783](https://linear.app/tezos/issue/JSTZ-783/support-jstz-network-addupdatedelete)
Updated network commands so that they properly handle the reserved `dev` network.
* list: print one row for `dev` and ignore any "custom" dev network in the config file
* add, update, delete: fail when the network name is `dev`
* Integration test: updated relevant tests
> fix(cli): handle dev network in network commands
