examples/deploy.js
examples/hello_world.js
examples/hello_world_requests.js
jstz_core/src/native.rs
jstz_proto/src/api/contract.rs
jstz_proto/src/api/ledger.rs
packages/jstz-types/index.d.ts

**Related Tasks**: [Refactor `Ledger.createContract`](https://app.asana.com/0/1205170694555856/1205622486240777/fl), [Make `Ledger.selfAddress` a property](https://app.asana.com/0/1205170694555856/1205622486240783/f)
**Dependencies**: #37, #36, #35 
This PR contains three minor refactors:
1. Make `Ledger.selfAddress` a readonly property 
2. Move `Ledger.createContract` to `Contract.create`
3. Make `Ledger.createContract` asynchronous (permits us to interrupt the contract running, useful for later interop + scheduling features + more consistent w/ `Contract.call`). 
```sh
eval `./scripts/sandbox.sh`
tz4="tz492MCfwp9V961DhNGmKzD642uhU8j6H5nB"
cat examples/hello_world_requests.js | jstz deploy-contract --self-address $tz4 --balance 42
contract=tz4...
jstz run-contract --referer $tz4 …
```

Proto/Api: Ledger Refactor

---

Cargo.lock
jstz_cli/Cargo.toml
jstz_cli/src/sandbox/daemon.rs
jstz_core/src/kv/mod.rs
jstz_core/src/kv/value.rs
jstz_kernel/src/inbox.rs
jstz_kernel/src/lib.rs

https://app.asana.com/0/1205170694555918/1205581410505410
This PR deprecates SetTicketer external message. It creates an installer kernel using a setup-file with the KT1 address obtained after originating the rollup kernel.
cargo run --bin jstz -- sandbox start

CLI: Deprecating SetTicketer

---

Cargo.lock
jstz_cli/Cargo.toml
jstz_cli/src/sandbox/daemon.rs

Following #54, the sandbox no-longer works due a panic in `jstz_kernel`.
This panic occurs due to a deserialization error. The root of this error was serializing the KT1 bridge address
as a tz4 address. 
```sh
cargo run -- sandbox start
```

Bugfix: Incorrect `bridge_address` encoding

---

jstz_core/src/kv/transaction.rs
jstz_core/src/kv/value.rs

`dyn Value` currently implements all the methods from `dyn Any`. We can avoid having to implement these methods and simplify the api by adding an `as_any` method that casts from `Value` to  `dyn Any`. 
add the `as_any` and `as_any_mut` methods to the `Value` trait
ran the hello world example and confirmed that it works

Refactor dyn Value

---

examples/print_body.js
jstz_cli/src/deploy.rs
jstz_cli/src/main.rs
jstz_cli/src/run.rs
jstz_cli/src/utils.rs

This pr makes it easier to deploy contracts and attach request bodies from files.
This PR changes the interface for a single argument from each of two commands
* `jstz deploy --contract-code` 
- If the supplied argument is a file the code will be read from that file
- if the supplied argument is not a file the code will be the argument itself
- if the argument is not supplied the code will be read from a pipe
- if there is no piped data an error is raised
- This is now a positional argument
* `jstz run --data` 
- If the supplied argument is a file the request body will be read from that file
- if the supplied argument is not a file the request body will be the argument itself
- if the argument is not supplied the body will be read from a pipe
- if there is no piped data no body will be …

Cli: Allow data from pipes and files

---

jstz_cli/src/account/account.rs
jstz_cli/src/account/mod.rs
jstz_cli/src/config.rs
jstz_cli/src/deploy.rs
jstz_cli/src/main.rs
jstz_cli/src/repl.rs
jstz_cli/src/run.rs
jstz_crypto/src/secret_key.rs
jstz_proto/src/context/account.rs
jstz_proto/src/operation.rs

https://app.asana.com/0/1205170694555918/1205647566435497
[https://app.asana.com/0/1205170694555918/1205670949626073](url)
[https://app.asana.com/0/1205170694555918/1205670949626067](url)
This PR adds support for signing operations using a secret key and Login/WhoAmI commands for setting the current account.
`cargo run -- account create alan`
`cargo run -- account create login alan`
`cargo run -- account whoami`
`cargo run -- deploy --function_code "console.log('Hello');"`
`cargo run -- run $url`

Cli: Operation signing + `login` and `whoami`

---

Cargo.lock
jstz_cli/Cargo.toml
jstz_cli/src/config.rs
jstz_cli/src/deploy.rs
jstz_cli/src/jstz.rs
jstz_cli/src/main.rs
jstz_cli/src/run.rs

**Related Tasks**: [Reading response from durable storage on smart function call](https://app.asana.com/0/1205170694555856/1205647566435499/f)
**Dependencies**: #64, #77, #66 
This PR permits CLI users to read the responses to signed operations (e.g. `run` or `deploy`)
in their terminal without tailing the `kernel.log` file. 
```sh
cargo run --bin jstz -- deploy index.js
// expected output will contain address of the smart function just deployed
addr=tz4...
cargo run --bin jstz -- run "tezos://$addr/"
// expected output will contain response from running the smart function
```

Cli: Responses

---

jstz_api/src/console.rs

In the context of the following example:
```typescript
function pythagoreanTriples(limit = 100) {
for (let x = 2; x <= limit; ++x) {
console.group(`x = ${x}`);
for (let y = 1; y < x; ++y) {
console.group(`y = ${y}`);
for (let z = x; z < x + y; ++z) {
console.log(`trying z = ${z}`);
if (x * x + y * y === z * z) {
console.log(`Success! ${x}^2 + ${y}^2 = ${z}^2`);
break;
}
}
console.groupEnd();
}
console.groupEnd();
}
}
```
Running `pythagoreanTriples(5)` prints:
```
[🪵] group: x = 2
[🪵] group: y = 1
[🪵] trying z = 2
[🪵] group: x = 3
[🪵] group: y = 1
[🪵] trying z = 3
[🪵] group: y = 2
[🪵] trying z = 3
[🪵] trying z = 4
[🪵] group: x = 4
[🪵] group: y = 1
[🪵] trying z = 4
[🪵] group: y = 2
[🪵] trying z = 4
[🪵] trying z = 5
[🪵] group: y = 3
[🪵] trying z = 4
[🪵] trying z = 5
[🪵] Success! 4^2 + 3^2 = …
```

Bugfix: Fix `console.group` indentation

---

jstz_cli/src/account/mod.rs
jstz_cli/src/config.rs
jstz_cli/src/main.rs

https://app.asana.com/0/1205170694555918/1205670949626073
https://app.asana.com/0/1205170694555918/1205670949626069
https://app.asana.com/0/1205170694555918/1205670949626067
https://app.asana.com/0/1205170694555918/1205670949626063
https://app.asana.com/0/1205170694555918/1205647566435495
This PR adds support for account management in the CLI. It supports login, logout, whoami, account create, account delete and account list commands. Additionally it adds support for these aliases in run/deploy commands. The current account together with the created accounts is stored in the `~/.jstz/config.json` config under "accounts". 
```
cargo run -- account create alan
cargo run -- account list
cargo run -- account delete alan
cargo run -- account list
cargo run -- account create alan
cargo run -- …
```

CLI Enhancements: Account management

---

jstz_api/src/console.rs
jstz_cli/src/repl.rs

Updates the repl and the console to print javascript objects in a readable format.
**Related issue**: [fix [Object object] ](https://app.asana.com/0/1205770721173531/1205771213624781/f)
```sh
nix develop
>> let x = {foo: 42}
>> x
{
foo: 42
}
>> console.log(x)
[🪵] {
[🪵]  foo: 42
[🪵] }
```

Api: Multiline logging

---

jstz_proto/src/operation.rs

Following from #76, when verifying the nonce, we do not increment it. 
This results in `InvalidNonce` errors when executing consecutive operations from a given account
This PR simply introduces a 1-liner fix that increments the nonce when running `verify_nonce`. 
```sh
cargo run --bin jstz -- account create alistair
cargo run --bin jstz -- login alistair
cargo run --bin jstz -- deploy examples/hello_world.js # Expected to be Ok
cargo run --bin jstz -- deploy examples/hello_world.js # Expected to be Ok
```

Bugfix: Fix missing `nonce.increment()`

---

Cargo.lock
jstz_cli/Cargo.toml
jstz_cli/src/account/account.rs
jstz_cli/src/account/mod.rs
jstz_cli/src/config.rs
jstz_cli/src/deploy.rs
jstz_cli/src/main.rs
jstz_cli/src/repl.rs
jstz_cli/src/run.rs

https://app.asana.com/0/1205770721173533/1205782954387583
https://app.asana.com/0/1205770721173533/1205770721319114
This PR makes several changes to the CLI commands, primarily for account abstraction:
- long version of list command `list -l`
- Account is now split into Owned and Alias enum options
- `jstz account create —function-code <CODE>` option for adding code to accounts
- Run and Deploy have --name option for using an alias instead of contract address
```
cargo run --bin jstz -- list
cargo run --bin jstz -- list -l
cargo run --bin jstz -- account create alan --function-code "`cat examples/counter.js`"
cargo run --bin jstz -- login alan
cargo run --bin jstz -- deploy --name counter_function
cargo run --bin jstz -- run --name counter_function
```

CLI Enhancements: Account abstraction

---

flake.nix
nix/jstz.nix

**Related Tasks**: [Fix openssl nixos issue](https://app.asana.com/0/1205770721173531/1205782959048378/f)
Currently running `cargo build` on a pure Linux environment (e.g. the one provided by nixos) gives the following error:
```
$ cargo run --bin jstz
Compiling blst v0.3.10
Compiling openssl-sys v0.9.93
error: failed to run custom build command for `openssl-sys v0.9.93`
Caused by:
process didn't exit successfully: `/home/xavierm02/Workspace/jstz/target/debug/build/openssl-sys-a99f684bd376fccf/build-script-main` (exit status: 101)
--- stdout
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR …
```

Nix: Fix openssl issue

---

docs/.vitepress/config.mjs
docs/api/contract.md
docs/api/index.md

This PR adds documentation for the `Contract` API
Documentation is kept short as the API is likely to change in the future.
```bash
```

Docs: Contract API

---

Cargo.lock
jstz_node/Cargo.toml
jstz_node/src/main.rs
jstz_node/src/services/logs/broadcaster.rs
jstz_node/src/services/logs/mod.rs
jstz_node/src/services/mod.rs
jstz_node/src/tailed_file.rs

This PR adds a log stream service that is responsible for reading the kernel.log file and broadcasting to the clients through SSE. 
**Related task**: [Name](https://app.asana.com/0/1205770721173533/1205770721347923)
First, we can start updating the kernel log file by running:
```
cargo run --bin jstz sandbox start
```
Run the jstz node with the path to the kernel file
```
cargo run --bin jstz-node --  --kernel-file-path logs/kernel.log
```
Now clients can read the logs by
```
curl http://localhost:8933/logs/foo/stream
```
```sh
```

Node: Initial implementation of `/logs/<sf>/stream`

---

jstz_cli/Cargo.toml
jstz_cli/src/debug_api/account.rs
jstz_cli/src/debug_api/mod.rs
jstz_proto/src/context/account.rs

[Host jstz API - AccountAPI](https://app.asana.com/0/1205770721173533/1205824789729520)
This PR adds support for Account host API in repl and functions 'balance','set_balance','code','set_code'.
```sh
nix develop
>> jstz.Account.balance("<address>")
>> jstz.Account.set_balance("<address>", 47)
>> jstz.Account.code("<address>")
>> jstz.Account.set_code("<address>", "console.log('Woohoo, this is a code.');")
```
- [ x] Changes follow the existing code style (use `make fmt-check` to check)
- [x ] Testing instructions have been added to PR

Cli enhancements: Host jstz APIs - Account API

---

Cargo.lock
jstz_api/Cargo.toml
jstz_api/src/lib.rs
jstz_api/src/urlpattern.rs
jstz_cli/src/repl.rs
jstz_core/src/value.rs
jstz_proto/src/executor/contract.rs
packages/jstz-types/index.d.ts

**Related issue**:  [🚧 API: URLPattern #100](https://github.com/trilitech/jstz/issues/100)
**Dependencies**: [urlpattern](https://github.com/denoland/rust-urlpattern)
This PR uses `urlpattern` crate (which was created by Deno developers) to implement `URLPattern`.
The underlying crate, and thus `URLPattern` as defined here (and also Deno) has difference with the [URL Pattern specified](https://urlpattern.spec.whatwg.org/#dom-urlpattern-urlpattern): it does not support the `ignoreCase` option. [There is an open PR](https://github.com/denoland/rust-urlpattern/pull/34) in `urlpattern` to support it, but it is already quite old, and not sure if it will be supported.
A single `NativeClass` is introduced (for `URLPattern`). For the other components (`URLPatternInit`, `URLPatternInput`, …

Api: URL Pattern API implementation

---

jstz_core/src/native.rs
jstz_core/src/value.rs

`JsValue` and `JsNativeObject<T>` were missing `JsInto` implementations (useful, for example, to lift `JsFunction` objects to Rust functions)
Added `JsInto` implementations for `JsValue` and `JsNativeObject<T>`

Implement IntoJs for JsValue and JsNativeObject

---

jstz_core/src/iterators.rs

I accidentally broke the tests. I hadn't realized doc examples were tested, and I assumed CI would catch broken tests.
Mark iterators.rs code examples as `ignore` for now, so tests pass.

Ignore broken iterators.rs doc examples for now

---

crates/jstz_cli/src/sandbox/daemon.rs

Currently running `sandbox start` gets stuck on:
```
Configuring sandbox... done
Initializing octez-node configuration... done
Generating identity... done
Starting node... done
```
This is because the paths for the sandbox parameter files changed.
This PR simply fixes the paths to the parameter files (and any other broken paths)
```sh
cargo run --bin jstz -- sandbox start
```

fix(cli): fix paths in sandbox

---

flake.nix

Not all architectures in Clang support `-mcpu`. Therefore it is better to not use those machine-specific flags at all when cross-compiling to other architectures.

Fix Darwin CC flags dilemma when targeting WASM and other architectures

---

Cargo.lock
crates/jstz_cli/Cargo.toml
crates/jstz_cli/src/config.rs
crates/jstz_cli/src/jstz.rs
crates/jstz_cli/src/logs/mod.rs
crates/jstz_cli/src/logs/trace.rs
crates/jstz_cli/src/main.rs

This PR Implements `jstz logs trace <sf>`, allowing users to listen to logs from a given sf on cli
Additionally, i've added an extra field in the cli config that specifies the host of jstz node. The default should be localhost (e.g.
```
{
...
"jstz_node_host": "127.0.0.1",
"jstz_node_port": 8933,
```
[Task link](https://app.asana.com/0/1205770721173533/1205770721347936)
Deploy a function,
run `jstz logs trace <sf>` to connect to the jstz node and run the function
https://github.com/trilitech/jstz/assets/128799322/9d162569-d85f-4d50-bda0-aff45ec46101

Cli: implement `jstz logs trace <sf>`

---

crates/jstz_api/src/console.rs
crates/jstz_api/src/encoding/text_decoder.rs
crates/jstz_api/src/encoding/text_encoder.rs
crates/jstz_api/src/http/header.rs
crates/jstz_api/src/http/request.rs
crates/jstz_api/src/http/response.rs
crates/jstz_api/tests/wpt.rs
crates/jstz_cli/src/sandbox/daemon.rs
crates/jstz_core/src/error.rs
crates/jstz_core/src/kv/mod.rs
crates/jstz_core/src/kv/value.rs
crates/jstz_core/src/realm.rs
crates/jstz_node/src/services/logs/mod.rs
crates/jstz_proto/src/error.rs
crates/jstz_proto/src/executor/contract.rs

This PR replaces several uses of `.expect()` and `.unwrap()` which could cause the rollup to panic. 
**Related Tasks**: [Analyze all possible panics](https://app.asana.com/0/1205770721173531/1206072089048483/f)
Calls to `.expect` and `.unwrap` are replaced wherever possible by converting to a result.  This reduces instances where the rollup may panic.
* Focus is on the areas where the rollup kernel would panic, `jstz_cli` and `jstz_node` may still panic.
* Panics caused by a programmer error in rust (such as interactions with `HostDefined` are not addressed. 
* There is no claim that this is exhaustive. Only the easy fixes have been addressed.

Health: Fix panics (low hanging fruit)

---

crates/jstz_node/src/main.rs
crates/jstz_node/src/services/accounts.rs
crates/jstz_node/src/services/logs/mod.rs
crates/jstz_node/src/services/mod.rs
crates/jstz_node/src/services/operations.rs
crates/jstz_node/src/tailed_file.rs

* There was a bug where the file read buffer wasn't sought to the end of the log file as expected.
* Previously the LogsService didn't follow the `configure` style (in `jstz_node/src/main.rs`) in order to limit the visibility of the `broadcaster` struct. However this isn't that big of an issue given each endpoint can only access one data anyway.
* Refactors the jstz-node service by introducing the `Service` trait
* Fix the issue with the file seek problem 
Ran the jstz-node services. 
The following screenrecords shows that the logging service works as expected and doesn't read the old content of the file anymore.
https://github.com/trilitech/jstz/assets/128799322/f12156d5-dcd9-4340-bc06-dbdb1ff6e22e

Node: Fix file read and refactor

---

crates/jstz_api/src/idl.rs
crates/jstz_api/src/lib.rs
crates/jstz_api/src/stream/mod.rs
crates/jstz_api/src/stream/readable/mod.rs
crates/jstz_api/src/stream/readable/underlying_source.rs
crates/jstz_api/src/stream/tmp.rs
crates/jstz_api/src/todo.rs
crates/jstz_cli/src/repl.rs
crates/jstz_core/src/js_fn.rs
crates/jstz_core/src/lib.rs
crates/jstz_core/src/native.rs
crates/jstz_core/src/value.rs

Implemented `UnderlyingSource`, and added a trivial `ReadableStream` constructor that only transforms its first input into an `UnderlyingSource`.
A few other things were added to make this possible / easier:
- A wrapper type `JsFn<T, I, O>` for `JsFunction` that allows to be more explicit about the JS function we expect to have, and to automatically handle the `TryFromJs` and `IntoJs` conversion for inputs and outputs.
- A `Todo` placeholder type for types from the spec that have not been defined yet.
- Type aliases that allow referring to some types by their WebIDL names.
```sh
>> new ReadableStream()
thread 'main' panicked at 'not yet implemented', jstz_api/src/stream/readable/mod.rs:39:9
```
```sh
>> new …
```

Implemented `UnderlyingSource` and added a trivial `ReadableStream` constructor

---

Cargo.lock
crates/jstz_api/Cargo.toml
crates/jstz_api/src/js_log.rs
crates/jstz_cli/src/logs/mod.rs
crates/jstz_cli/src/logs/trace.rs

https://app.asana.com/0/1205770721173531/1205770721347940/f
This PR adds log filtering by levels (LOG, INFO, WARN, ERROR) to the jstz-cli. The newly added optional --level or -l flag takes one of the log levels and stream logs with that level of logs or higher precedence. 
If the --level flag is not mentioned, then all the available types of logs are streamed.
1. Started jstz sandbox and a jstz node.
2. Deployed `examples/logs.js` contract.
3. Ran `cargo run --bin jstz logs trace <address> --level warn` in a separate tab.
4. Ran the contract.
1. With `--level`
```
$ cargo run --bin jstz logs trace tz4MRUzq2DD3dzx2F6sCeeD1kfpK9ejgBsz6 --level warn
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep …
```

cli: filter logs by --level

---

Cargo.toml

This PR fixes the build warning:
```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```
Sets `workspace.resolver` to `"2"`
```
make build
```

Health: Use version 2 for `workspace.resolver`

---

crates/jstz_api/src/http/header.rs
crates/jstz_api/src/http/request.rs
crates/jstz_api/src/http/response.rs
crates/jstz_api/src/url/search_params.rs
crates/jstz_api/tests/wptreport.json
crates/jstz_core/src/iterators.rs
crates/jstz_core/src/native.rs

**Related issue**: [API: Make Headers more spec compliant](https://github.com/trilitech/jstz/issues/260)
This fixes the following spec compliance problems with Headers:
- Headers should be iterable
- Headers constructor should accept undefined
- Headers constructor should accept iterables
- Headers sequence constructor should throw when sequence elements aren't pairs
- Headers constructor, append, and set should normalize values
- Headers constructor, append, and set should convert values to strings
- "invalidĀ" (for example) should be an invalid header name or value (constructor, append, set should throw)
There are still some known spec compliance problems, I will document them in a next PR.
`cargo test`

API: Make Headers more spec compliant

---

crates/jstz_cli/src/deploy.rs
crates/jstz_cli/src/jstz.rs
crates/jstz_cli/src/run.rs
crates/jstz_cli/src/sandbox/mod.rs
crates/jstz_node/src/main.rs
crates/jstz_node/src/services/operations.rs
crates/octez/src/rollup.rs

**Related Tasks**: [Proxy external messages from `jstz-node` to the rollup node](https://app.asana.com/0/1205770721173531/1206249753769937/f) 
This PR introduces a proxy for external inbox messages to the jstz rollup using the `jstz-node`. This avoids
the CLI directly communicating with the `octez-node`. 
The only direct`octez-node` dependencies are in the sandbox (not removable for now) and L1 account deposits. 
This PR adds a `POST` endpoint to the `/operations` service, permitting the injection of operations via the `jstz-node` instead of using the `octez-node`. 
**Note**: There seems to be an issue with the JSON serialization and deserialization of BLS signatures with `actix-web`, this could be fixed by #320. For now we just directly pass bytes, but in future (when implementing IDL …

Node: Proxy external inbox messages via `jstz-node`

---

.github/workflows/ci.yml
.gitignore
Makefile
crates/jstz_cli/Cargo.toml
crates/jstz_cli/build.rs
crates/jstz_cli/src/config.rs
crates/jstz_cli/src/sandbox/daemon.rs

**Related Tasks**: [Removing dependence on jstz source location in CLI](https://app.asana.com/0/1205770721173531/1206345416248634/f)
This PR introduces a Rust build script that removes the need for `jstz_path` in the CLI.
This introduces an inadvertent semantic changes -- the `/logs` directory used by jstz CLI will be created in the current working directory:
- if you run `cargo run --bin jstz` in the root directory for the jstz repository, this should have no effect, but 
- if you run `cargo run --bin jstz` in a subdirectory `A`, this will create `A/logs` directory
In future, the `logs` directory will be in `/tmp` once we start the `jstz-node` automatically when running `jstz sandbox start`. 
Running the sandbox and checking various features still work

Cli: Remove `jstz_path` from CLI config

---

crates/jstz_crypto/src/secret_key.rs

Workaround for bug in `SecretKeyEd25519` (de)serialisation in currently released `tezos_crypto_rs`

feat(crypto): fix tz1 account creation

---

Cargo.lock
crates/jstz_cli/Cargo.toml
crates/jstz_cli/src/account/account.rs
crates/jstz_cli/src/account/mod.rs
crates/jstz_cli/src/bridge/deposit.rs
crates/jstz_cli/src/bridge/mod.rs
crates/jstz_cli/src/config.rs
crates/jstz_cli/src/deploy.rs
crates/jstz_cli/src/error.rs
crates/jstz_cli/src/jstz.rs
crates/jstz_cli/src/kv.rs
crates/jstz_cli/src/logs/mod.rs
crates/jstz_cli/src/logs/trace.rs
crates/jstz_cli/src/main.rs
crates/jstz_cli/src/repl/mod.rs
crates/jstz_cli/src/run.rs
crates/jstz_cli/src/sandbox/daemon.rs
crates/jstz_cli/src/sandbox/mod.rs
crates/jstz_cli/src/term/emoji.rs
crates/jstz_cli/src/term/mod.rs
crates/jstz_cli/src/term/styles.rs
crates/jstz_cli/src/utils.rs

Improves CLI error reporting
This PR:
1. Introduces an `error.rs` file that defines the CLI's result + error type (anyhow w/ internal constructors such as `UserError`).
2. Updates the rest of the CLI to use this error module.
3. Improves various error messages in the CLI
Running a selection of commands with erroneous outputs

feat(cli): separate errors into 'user errors' and 'internal errors'

---

commitlint.config.js

A lot of our dependabot PR's don't pass our CI due to our commitlint rules -- namely most of the commit msg bodies exceed 100 characters per a line (primarily due to the inclusion of links in the commit msg). 
This PR extends the limit to 200 characters, which should be sufficient.

ci(commitlint): extend `body-max-line-length` to 200

---

Cargo.lock
crates/jstz_cli/Cargo.toml
crates/jstz_cli/src/account.rs
crates/jstz_cli/src/config.rs

**Dependencies**: #364 
This PR improves our current interactive prompts (for the account commands) by:
- Using a standardized library (dialoguer)
- Adds functionality to the prompts (account generation for `login`)

feat(cli): use `dialoguer` for interactive prompts (`login` & `delete`)

---

crates/jstz_cli/src/sandbox/daemon.rs
crates/jstz_node/src/main.rs

Executing the jstz_node binary outside of sandbox environment leads to a panic. This problem arises when spawning the broadcaster future that expects to be called inside the `LocalSet`, a set of task executed on the same thread.
This PR fixes the issue by replacing the tokio's runtime with the #[actix_web::main].
run the jstz_node binary as well as the sandbox to see if it works.

Node: fix running the server in main

---

Cargo.lock
crates/jstz_cli/Cargo.toml
crates/jstz_cli/src/jstz.rs
crates/jstz_node/src/services/operations.rs

This PR fixes a known issue about `jstz-node` -- namely that `POST /operations` accepts bytes as opposed to a `SignedOperation`. 
This was due to an issue with the serializer and deserializer for `SignedOperation` while it was using tz4 addresses (from `tezos_crypto_rs`). Following #352, we now use tz1 addresses (which have a working serializer & deserializer 😊). 
With the sandbox + jstz node running:
```sh
cargo run --bin jstz -- deploy examples/counter.js
```
Inspect the jstz-node logs for a `POST /operations` call.

fix(node): Allow JSON `SignedOperations` for `POST /operations`

---

Cargo.lock
crates/jstz_cli/Cargo.toml
crates/jstz_cli/src/completions.rs
crates/jstz_cli/src/main.rs

**Related Tasks**: [Shell autocompletions for CLI](https://app.asana.com/0/1205770721173531/1206472793750873/f)
This PR adds a `completions` command to `jstz`, which prints the autocompletions for the CLI to stdout
Since we don't yet globally install jstz as a binary, it's a bit finicky to test locally. 
For zsh:
```sh
autoload -U compinit && compinit
source <(cargo run --bin jstz -- completions --shell=zsh)
compdef _jstz ./target/debug/jstz
```
To use the completions, you must use `./target/debug/jstz [Tab]` ([Tab] denotes you pressing tab). I've not been able to get this to work with `cargo run --bin jstz -- ...`
For other shells:
https://github.com/clap-rs/clap/issues/2488#issuecomment-864576617

feat(cli): add `completions` command to jstz

---

crates/jstz_api/src/js_log.rs
crates/jstz_api/src/kv.rs
crates/jstz_cli/src/repl/debug_api/account.rs
crates/jstz_cli/src/repl/debug_api/kv.rs
crates/jstz_cli/src/repl/js_logger.rs
crates/jstz_cli/src/repl/mod.rs
crates/jstz_core/src/error.rs
crates/jstz_core/src/host.rs
crates/jstz_core/src/kv/mod.rs
crates/jstz_core/src/kv/transaction.rs
crates/jstz_core/src/runtime.rs
crates/jstz_core/tests/transaction_test.rs
crates/jstz_kernel/src/lib.rs
crates/jstz_proto/src/api/contract.rs
crates/jstz_proto/src/api/ledger.rs
crates/jstz_proto/src/context/account.rs
crates/jstz_proto/src/executor/contract.rs
crates/jstz_proto/src/js_logger.rs
crates/jstz_proto/src/request_logger.rs
examples/nested_counter.js
examples/nested_transactions.js

**Related Tasks**: [Support nested transactions in `jstz_proto`](https://app.asana.com/0/1205770721173531/1206345416213104/f) 
This PR adds the long awaited support for nested transactions in `jstz_proto`, permitting _atomic synchronous nested smart function calls_. 
Myself and @alanmarkoTrilitech discovered some issues with the old implementation of nested transactions -- namely the use of lifetimes caused issues if we used `Rc<RefCell<_>>` for a pointer to the parent transaction. 
There were two possible solutions to this:
- Wrapping all snapshot values in `Rc<RefCell<_>>`, thus eliminating most lifetimes from the transaction API
- Using the transactional stack design from https://www.notion.so/trilitech/Transactional-Storage-4c4a4b173145498dbbb61448e505ee16?pvs=4
This PR implements the …

feat(core,proto,kernel,cli): nested transactions

---

crates/jstz_api/src/stream/mod.rs
crates/jstz_api/src/stream/queuing_strategy/builtin.rs
crates/jstz_api/src/stream/queuing_strategy/high_water_mark.rs
crates/jstz_api/src/stream/queuing_strategy/mod.rs
crates/jstz_api/src/stream/queuing_strategy/size.rs
crates/jstz_api/src/stream/readable/mod.rs
crates/jstz_api/src/stream/readable/underlying_source.rs
crates/jstz_core/src/js_fn.rs
crates/jstz_core/src/value.rs

This implements part of the [queuing strategy](https://streams.spec.whatwg.org/#qs-api) section of the Stream WebAPI. The main goal was to implement `CountQueuingStrategy`, but since most of the code could be shared through simple macros, most of `ByteLengthQueuingStrategy` is also implemented (with the only remaining being finishing the implementation of its size algorithm).
```sh
nix develop
>> new CountQueuingStrategy()
✕  ERROR  Uncaught TypeError: CountQueuingStrategy constructor: At least 1 argument required, but only 0 passed
>> new CountQueuingStrategy(1)
✕  ERROR  Uncaught TypeError: Missing required highWaterMark property
>> new CountQueuingStrategy({})
✕  ERROR  Uncaught TypeError: Missing required highWaterMark property
>> strat = new …
```

feat: implemented `CountQueuingStrategy`

---

crates/jstz_cli/src/deploy.rs
crates/jstz_proto/src/api/smart_function.rs
crates/jstz_proto/src/context/account.rs
crates/jstz_proto/src/executor/smart_function.rs
crates/jstz_proto/src/operation.rs
examples/deploy.js

Currently if we deploy a contract it is not checked whether it parses or not. This means the kernel panics when the contract is called.  This PR fixes that by raising an error when the contract is deployed. 
**Related Tasks**: [Add check to see if JS parses when deploying contract](https://app.asana.com/0/1205770721173531/1205770721309638/f)
* Introduces a new type `ParsedCode` as a witness that the code has been parsed.
* Changes the deployment logic to uses ParsedCode and not String.
* Updates the CLI to pass ParsedCode not strings so that we can perform the checks before deploying.
```bash
echo "fn default(request: Request) -> Response { response::new() }" | jstz deploy # parse error
jstz deploy --name test_deploy examples/deploy.js
jstz run tezos://test_deploy
```

fix: check smart function code parses before continuing

---

crates/jstz_node/src/services/logs/mod.rs

Cargo build fails outside of nix shell due to an issue with clippy::collapsible-match
'-'->'_'.
Cargo build

fix(node): collapsible match fix

---

Cargo.lock
crates/jstz_cli/Cargo.toml
crates/jstz_cli/src/logs/mod.rs
crates/jstz_cli/src/logs/trace.rs
crates/jstz_cli/src/main.rs
crates/jstz_cli/src/run.rs

[run --trace](https://app.asana.com/0/1205770721173531/1206394772057371/f)
Show the log trace when running the contract.
I also turned off the spinner immediately in case the trace is enabled as it clash with other texts
jstz run <url> --trace 
https://github.com/trilitech/jstz/assets/128799322/baca0c4f-ca9f-422b-8b6e-3151ae0a0e8b

Cli: enable run --trace

---

crates/jstz_cli/src/config.rs

Patch for (#422)[https://github.com/trilitech/jstz/pull/422]  to handle upstream config changes.
This PR assigns default values if the `networks` or `sandbox_logs_dir` fields are missing. These were omitted from the previous PR when merging with `main`
```bash
echo "{}" > ~/.jstz/config.json
jstz login sam
cat ~/.config.json
```

fix(cli): fixup new keys

---

crates/jstz_cli/src/account.rs

In help for account code there is this emoji - 🧑‍💻 which however gets diplayed as two emojis 🧑‍ 💻 which breaks the text alignment in help.
This PR changes 🧑‍💻 to 💻.
jstz account help

fix(cli): remove double emojis in account code 🧑‍💻=🧑‍ 💻 -> 💻

---

crates/jstz_cli/src/repl/mod.rs

**Related Tasks**: [`SmartFunction.create()` does not work in REPL](https://app.asana.com/0/1205770721173531/1206695470748493/f)
This PR fixes the `TransactionStackEmpty` error when interacting with `Kv`, `Ledger` or `SmartFunction` in the REPL
```sh
jstz repl
>> Kv.get("foobar")
```

fix(cli): add `tx.begin()` in the REPL

---

crates/jstz_api/src/encoding/text_decoder.rs
crates/jstz_api/src/encoding/text_encoder.rs
crates/jstz_api/src/file/blob.rs
crates/jstz_api/src/file/file.rs
crates/jstz_api/src/http/header.rs
crates/jstz_api/src/http/request.rs
crates/jstz_api/src/http/response.rs
crates/jstz_api/src/stream/queuing_strategy/builtin.rs
crates/jstz_api/src/stream/readable/mod.rs
crates/jstz_api/src/url/mod.rs
crates/jstz_api/src/url/search_params.rs
crates/jstz_api/src/urlpattern.rs
crates/jstz_core/src/iterators.rs
crates/jstz_core/src/native.rs

**Related Tasks**: [Panics in URL / URLSearchParams](https://app.asana.com/0/1205770721173531/1206682403279323/f)
This PR fixes the `NativeClass` constructor method, namely the `constructor` doesn't have the `this` value to hand until the `JsNativeObject` is built. 
This was causes dereferencing panics since the *target* was being passed as `this`. The _target_ is the `JsValue` that is used e.g. for `new Animal`, the `JsValue` would be `Animal`. This obviously doesn't have the same Rust type as the `Self::Instance` type. 
The solution is to split the constructor into a *data* constructor and an *object* constructor.
This panic'd previously
```sh
jstz repl
>> const url = new URL("http://example.com/?");
>> url.searchParams.delete("param1")
>> url.search
null
```

fix(core): fix native class constructor method

---

docs/quick_start.md
examples/get-tez/package.json
package-lock.json
package.json

Currently following the quick start guide command-for-command doesn't work (you get an npm error for
compiling the get-tez smart function)
Changes the quick start guide to:
- Instruct the user to clone the `jstz` repository
- Install npm dependencies for deploying the get-tez smart function
Additionally I removed the `-d` for the sandbox start since this flag doesn't work for the docker installation. 
```sh
```
and following the quick start instructions

docs: add instructions for cloning get-tez example and installing dependencies

---

docs/quick_start.md

Fixes missing quote in the `jstz run` command in the quick start guide
```sh
```

docs: fix missing quote in quick start

---

crates/jstz_cli/src/main.rs

`jstz cli` completions work great, but prevent the shel from completing filenames.
This PR enables filename completions for arguments that require filenames.
**Related Tasks**: [Cli completions do not work for filenames](https://app.asana.com/0/1205770721173531/1206712599227133/f) 
Adds clap directives for completion of filenames for `jstz deploy` and `jstz run --data`
```bash
jstz deploy examples/<tab>
jstz run "tezos://some-function" --data somefile.j<tab>
```

feat(cli): completions for filename arguments

---

.github/workflows/ci.yml
.github/workflows/deploy-teztnet.yml
.github/workflows/docker.yml
crates/jstz_cli/Dockerfile

**Related Tasks**: #465 
This PR modifies the Dockerfile for the CLI to use the tezos/tezos image as the source of truth
for the `sandbox-params.json` file -- this will ensure that we don't run into #465 again.
Additionally, the CI is reconfigured to permit us to manually build the docker images on request. 
CI changes aren't possible to test locally (but the changes consist of re-ordering jobs + adding a manual `workflow_dispatch` event handler)
To test the docker changes, run:
```sh
make build-cli-kernel
docker build . -f crates/jstz_cli/Dockerfile -t jstz:latest --build-arg OCTEZ_TAG=master_ddfbb8d6_20240312193411 --build-arg KERNEL_PATH=crates/jstz_cli/jstz_kernel.wasm
alias jstz="docker run --rm -v \"/tmp:/tmp\" -v \"/Users/ajob410/.jstz:/root/.jstz\" -v \"\$PWD:\$PWD\" -w \"\$PWD\" …
```

fix(ci): use the tezos/tezos image as the source of truth for `sandbox-params.json`

---

scripts/install-jstz-cli.sh

This PR addresses issue #472 and #473. It respects ZDOTDIR variable if set and only reloads the configuration file if the shell is matching SHELL value, in order to not break previous prompt.
run the install script

fix(scripts): zdotdir + config file loading

---

crates/jstz_rollup/src/rollup.rs
docs/installation.md

Prevents a few different cryptic errors when starting up (all of which appear as 'file not found'), namely:
- octez binaries can't be found, despite having been copied into `jstz` directory - they have to be in `PATH`
- kernel.log file not created, which causes the `TailedFile::init` to fall over. Ensure we create it earlier in the process
delete your `~/.jstz` folder, and try starting the sandbox with/without this change

Sandbox: improve startup robustness

---

crates/jstz_cli/src/sandbox/daemon.rs

`jstz sandbox start`. Observe that, with the patch, the left hand 'spinner icon' is never stuck

fix(sandbox): spinner should spin continuously

---

crates/jstz_cli/src/run.rs
crates/jstz_proto/src/executor/smart_function.rs
examples/benchmark.js

please check the google doc [here](https://docs.google.com/document/d/1xOllQhKrkHBpx3acthXUZ1Qc8uq4Jyn7Utgjg66zKi4/edit)
[asana task](https://app.asana.com/0/1205770721173531/1207085786191010/f) 
Tested the instruction limit required to run `benchmark.js` where n is the number of times fa2 token is transferred.
Set the instruction limit to `550000` based on the following result:
<b style="font-weight:normal;" id="docs-internal-guid-fb5cbdf7-7fff-9b87-881f-c6f6f11caca1"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Result:</span></ …

Set instruction limit

---

.github/workflows/ci.yml
Cargo.lock
crates/jstz_core/Cargo.toml

Remove blst from crate graph
Prevent `blst` coming back into the crate tree, as this breaks building jstz for riscv on mac.
`cargo tree | grep blst`
See https://github.com/trilitech/jstz/actions/runs/9080566889/job/24952362135 for an example of the new check failing

fix(deps): remove blst from crate tree

---

Cargo.lock
crates/jstz_kernel/src/inbox.rs
crates/jstz_node/Cargo.toml
crates/jstz_node/src/services/operations.rs
crates/octez/Cargo.toml
crates/octez/src/rollup.rs

https://app.asana.com/0/1205770721173533/1207223543435817
When a rollup is deployed on a network where other rollups are deployed, such as ghostnet, it receives external messages from all rollups. In the current implementation, this results in "Failed to parse external message error". This PR add external message frame where it is possible to specify the smart rollup address and thus only consume the messages directed at jstz.
Start sandbox, deploy and run a smart function.

feat(kernel): external messages

---

crates/jstz_core/src/host.rs
crates/jstz_core/src/runtime.rs
crates/jstz_kernel/src/lib.rs
crates/jstz_proto/src/executor/mod.rs
crates/jstz_proto/src/executor/smart_function.rs

Hide `'static` requirements from top-level entry function
Significantly simplifies integration of jstz with parts of the sdk/riscv work. The requirement is used by jstz to play fast & loose with lifetimes internally, and is effectively an implementation detail which can be hidden away.

feat(kernel): hide 'static requirements

---

crates/jstz_cli/src/config.rs

Improve the error message
[Task](https://app.asana.com/0/1205770721173531/1206703424903101/f)
improve the error message that gets thrown when sandbox isn't running
Run:
```
jstz account balance -n dev
```
Before:
```
✕  ERROR  error sending request for url (http://127.0.0.1:8933/accounts/tz1dbGzJfjYFSjX8umiRZ2fmsAQsk8XMH1E9/balance): error trying to connect: tcp connect error: Connection refused (os error 61)
```
After:
```
✕  ERROR  The sandbox is not running. Please run `jstz sandbox start`.
```

Cli: Improve error message when sandbox isn't running

---

crates/jstz_api/src/http/response.rs

Currently when creating a response object, you _must_ give non-null body, despite the prototype of the constructor being:
```
new (body?: BodyInit | null, init?: ResponseInit): Response;
```
If `null` is given for `body`, then the following error is reported:
```
>> new Response(null)
✕  ERROR  Uncaught TypeError: value is not an ArrayBuffer object
```
```sh
>> new Response(null)
{
}
```

feat: add support for `null` or `undefined` bodies in `new Response` constructor

---

CONTRIBUTING.md
README.md
crates/jstz_cli/Cargo.toml

Update regressed docs.
* Removes dependency on custom octez distribution in `CONTRIBUTING.md`
* Adds default-run to jstz cli `Cargo.toml`. This defaults the `cargo run` to target `jstz` which is the assumption in the docs
* Small code formatting fix

Fix doc: Bring contributing doc up to date

---

crates/jstz_cli/src/jstz.rs

CLI should be able to handle 404 error
[Task](https://app.asana.com/0/1205770721173531/1206703424649696/f)
The get_code function didn't handle the case for 404 response. I've added an error message for this. 
Additionally, I noticed `get_balance` didn't handle this as well so i fixed that too.

Handle jstz client 404 error

---

crates/jstz_cli/src/sandbox/daemon.rs

Fixes the advertised octez node rpc endpoint to point to the correct RPC port
`--net-addr` arg configures the [p2p endpoint of the node.](https://tezos.gitlab.io/user/node-configuration.html#listening-ports) whereas `--rpc-addr`[ configures the RPC endpoint](https://tezos.gitlab.io/developer/rpc.html#activating-rpc).  I think the intent was to advertise the rpc endpoint.
When running sandbox, jstz will advertise the rpc endpoint to be  `http://localhost:18730` insteand of ` http://localhost:18731`. 
`./<octez-client> -E http://localhost:18730 rpc list` should work

fix(sandbox): advertise octez-node rpc port instead of network port

---

crates/jstz_cli/src/sandbox/daemon.rs
crates/jstz_rollup/src/main.rs
crates/octez/src/thread.rs

This PR kills zombie octez processes started by the sandbox if the sandbox errors out or is killed before it reaches the main' `handle.join()`
Introduces a `Sandbox` struct that is responsible for performing the clean up of octez threads and reverting the config file in the event of error.  FWIW, there is definitely more that can be done to come up with a better solution but I have restrained myself from refactoring everything.
1. Apply the following patch to `main` branch to introduce a panic after the octez processes have started. 
```rust
diff --git a/crates/jstz_cli/src/sandbox/daemon.rs b/crates/jstz_cli/src/sandbox/daemon.rs
index 2962a9d..a9dc52b 100644
--- a/crates/jstz_cli/src/sandbox/daemon.rs
+++ b/crates/jstz_cli/src/sandbox/daemon.rs
@@ -573,6 +573,7 @@ pub async fn …
```

fix(octez): properly drop octez threads when done

---

crates/jstz_cli/src/sandbox/daemon.rs
crates/jstz_node/src/lib.rs
crates/jstz_node/src/main.rs
crates/octez/src/thread.rs

Fix bug introduced in the https://github.com/jstz-dev/jstz/pull/525 . The octez threads were not shutting down. When jstz node is shutdown, we should terminate the sandbox.
Additionally, this PR ensures that all processes are killed when any one process is killed.
1. Start sandbox then kill it after it is fully loaded.
2. Start sanbox then kill octez or jstz processes via `kill <pid>`

fix(sandbox): fix sandbox not shutting down on ctrl+c

---

Cargo.lock
crates/jstz_mock/Cargo.toml
crates/jstz_mock/src/mock.rs
crates/jstz_proto/Cargo.toml
crates/jstz_proto/src/context/mod.rs
crates/jstz_proto/src/context/ticket_table.rs
crates/jstz_proto/src/error.rs

The TicketTable keeps track of tickets (except the tez ticket) sent to the jstz rollup to facilitate permissionless deposit/withdrawal of bridged assets to/from jstz. Unlike L1, tickets can only be added or removed and not created or transferred between accounts. This means that tickets can only be used to bridge assets created on L1 to jstz, and not vice versa.
`cargo test -p jstz_proto ticket`

feat(ticket-table): implement ticket table

---

crates/jstz_crypto/src/signature.rs

I experienced a kernel panic when testing out a smart function locally. 
The offending line was an `.unwrap()` when verifying signatures, due to an invalid signature.
Note: I'm not too sure how an invalid signature occurred, I suspect a mismatch between serde versions on the CLI and 
built WASM kernel used in the sandbox. 
I haven't been able to reproduce the panic 😔 So no tests, but the improvement is clear

fix(crypto): prevent panic in `Signature::verify` due to invalid signatures

---

Makefile
flake.nix
nix/overlay.nix
package-lock.json
rust-toolchain.toml

**Related Tasks**: [jstz-42](https://linear.app/tezos/issue/JSTZ-42/code-coverage-infrastructure-local)
We want to track code coverage as a metric. This task is the first of many to achieve this. 
Future work includes:
- Enabling unit tests on our CI
- Integrating the coverage report output with CodeCov
- Enabling integration tests on our CI (w/ coverage reports as well)
This PR integrates with `cargo-llvm-cov` to add code coverage to jstz's crates. The coverage report
is only generated based on data from _unit tests_ (we will add support for integration tests later). 
Reload your nix shell and run:
```sh
make cov
```

test(cov): add llvm-cov

---

Cargo.lock
Cargo.toml
crates/jstz_api/Cargo.toml
crates/jstz_cli/Cargo.toml
crates/jstz_core/Cargo.toml
crates/jstz_crypto/Cargo.toml
crates/jstz_kernel/Cargo.toml
crates/jstz_mock/Cargo.toml
crates/jstz_node/Cargo.toml
crates/jstz_proto/Cargo.toml
crates/jstz_rollup/Cargo.toml
crates/jstz_sdk/Cargo.toml
crates/jstz_wpt/Cargo.toml
crates/octez/Cargo.toml
flake.nix

This PR
- Attempts to unify and standardise the Cargo.toml files used through the project
- Order the dependencies alphabetically. 
In the future it would be nice to use `cargo-sort` and have a CI check to keep it consistent but currently it https://github.com/DevinR528/cargo-sort/issues/54
- Hoist up dependencies to the main Cargo.toml and use the workspace dependency inheritance to align versions and provide a way to cache Cargo dependencies (as used in #542 )
In future, 
- External dependencies must be added to the root `Cargo.toml` (unless not supported as a workspace dependencies, such as _optional_ dependencies)
- Internal crates are referred to using `{ path = <crate path> }`
Check everything builds and passes tests :) 
```sh
make build
make test
```

chore: standardise Cargo.toml files

---

crates/jstz_kernel/src/inbox.rs
crates/jstz_mock/src/mock.rs
crates/jstz_proto/src/context/ticket_table.rs
crates/jstz_proto/src/error.rs
crates/jstz_proto/src/executor/fa_deposit.rs
crates/jstz_proto/src/executor/mod.rs
crates/jstz_proto/src/operation.rs
crates/jstz_proto/src/receipt.rs

Handles the execution of an `FaDeposit` operation within the protocol. This PR does not "plug" the execution into the kernel yet but the tests should provide enough confidence of its correctness,. The plugging will be done in a follow up PR.
The `execute` handler takes an `FaDeposit` as input and produces a `Receipt` as output where the content type is `FaDepositReceiptContent`.  
When executing an FA deposit, the deposit could either be routed to user account or a proxy smart function. 
1. If the former, tickets will be added directly to the user account. 
2. If the latter, the proxy smart function is first executed, targeting the endpoint `POST /-/deposit` with body `{  receiver: ..., amount: ... , ticketHash: ... }` as described in the [Ticket Transport …

feat(fa-deposit): handle fa deposit execution in proto

---

contracts/jstz_native_bridge.mligo
contracts/jstz_native_bridge.tz
contracts/test/test_jstz_native_bridge.mligo
crates/jstz_cli/src/bridge/deposit.rs
crates/jstz_cli/src/bridge/mod.rs
crates/jstz_cli/src/main.rs
crates/jstz_cli/src/sandbox/daemon.rs
crates/jstz_rollup/src/bridge.rs
crates/octez/src/client.rs

Fixes broken bridge deposit command. 
Closes: [JSTZ-71 ](https://linear.app/tezos/issue/JSTZ-71/fix-jstz-deposit)
1. This fix required that the native bridge contract stores the jstz smart rollup address. 
2. Ctez references have been removed 
```
cargo run -- sandbox start
```
```
cargo run -- bridge deposit --from bootstrap1 --to bob --amount 100
```
```
cargo run -- account balance  -a bob
```
```
grep -rwi "ctez" crates/
```

fix(bridge): fix bridge deposit

---

.github/workflows/ci.yml
flake.nix

**Related Tasks**: [jstz-66](https://linear.app/tezos/issue/JSTZ-66/update-ci-to-use-nix-flake-instead-of-actions-environment)
**Dependencies**: #543 #542 
Does what it says on the tin. 
Future work includes:
- Building docs using Nix
- Linting Rust code using Nix (currently we rely on `make lint` which will pull its own dependencies)
- Using self-hosted runners for better cache locality + exposing the cache to devs (for local environments). `magic-nix-cache` isn't very good and will often drop cached dependencies in favour of space
Green CI 🚀

ci: use nix flake for environment

---

crates/jstz_core/tests/transaction_test.rs
crates/jstz_proto/src/context/account.rs
crates/jstz_proto/src/executor/deposit.rs

This PR makes small changes to Account deposit mainly for consistency and safety: 
* renames `deposit` to `add_balance`
* adds overflow check to `add_balance`

fix(account): rename deposit to add balance and add overflow check

---

Cargo.lock
Cargo.toml
crates/jstz_core/Cargo.toml
crates/jstz_core/src/error.rs
crates/jstz_core/src/kv/mod.rs
crates/jstz_core/src/kv/outbox.rs
crates/jstz_core/src/kv/transaction.rs

This PR omplements the lower level transactional outbox queue api
Part of [JSTZ-27](https://linear.app/tezos/issue/JSTZ-27/implement-outbox) 
The kernel is only allowed to write 100 messages per level. Luckily, the kernel sdk to expose an [OutboxQueue](https://gitlab.com/tezos/tezos/-/blob/master/src/kernel_sdk/sdk/src/outbox.rs#L108) which decouples enqueuing outbox messages and writing to the outbox, allowing a much high upper limit of outbox messages to be persisted as long as they are flushed (ideally, every level). However, the `OutboxQueue` is eager to write to persistent storage on message enqueue which makes it difficult to rollback and doesn't fit our transaction model. 
Instead, we define an outbox queue for each snapshot that adheres to the transaction rules. Furthermore, an …

feat(outbox): implement outbox queue on transaction

---

Cargo.lock
crates/jstz_kernel/src/inbox.rs
crates/jstz_kernel/src/lib.rs
crates/jstz_mock/src/host.rs
crates/jstz_proto/Cargo.toml
crates/jstz_proto/src/context/account.rs
crates/jstz_proto/src/error.rs
crates/jstz_proto/src/executor/mod.rs
crates/jstz_proto/src/executor/smart_function.rs
crates/jstz_proto/src/executor/withdraw.rs
crates/jstz_proto/src/lib.rs

Implements native withdrawal from external messages.
`cargo test -p jstz_proto -- executor::smart_function executor::withdraw`

feat(withdrawal): implement native withdrawal

---

crates/jstz_cli/sandbox-params.json
crates/jstz_cli/src/bridge/mod.rs
crates/jstz_cli/src/bridge/withdraw.rs
crates/jstz_cli/src/config.rs
crates/jstz_cli/src/main.rs
crates/jstz_cli/src/run.rs
crates/jstz_cli/src/utils.rs
crates/jstz_proto/src/executor/mod.rs
scripts/execute_latest_outbox_message.sh

Adds `bridge withdraw` command to the cli
Closes [JSTZ-105](https://linear.app/tezos/issue/JSTZ-105/implement-cli-command-for-withdraw)
Underneath the hood, the cli command prepares and calls the run operation against `/jstz/withdraw`
1. Run the sanbox
```
cargo run -- sandbox start
```
2. Deposit funds form bootstrap1 to the logged in account 
```
cargo run -- bridge deposit --from bootstrap1 --to bob --amount 1000
```
3. Withdraw funds from the logged in account to L1 address
```
cargo run -- bridge withdraw -t tz1dbGzJfjYFSjX8umiRZ2fmsAQsk8XMH1E9 -a 123.123456
```
4. Execute the outbox using octez client
```
./scripts/execute_latest_outbox_message.sh $OCTEZ_CLIENT
```
5. Check balance
```
$OCTEZ_CLIENT -E http://127.0.0.1:18730 get balance for tz1dbGzJfjYFSjX8umiRZ2fmsAQsk8XMH1E9
```

feat(cli): add bridge withdraw command

---

Cargo.lock
Cargo.toml
crates/jstzd/Cargo.toml
crates/jstzd/src/lib.rs
crates/jstzd/src/task/mod.rs

Define the Task trait. Task represents any task to be run with backends, e.g. octez node, jstz node, etc.
[JSTZ-115](https://linear.app/tezos/issue/JSTZ-115/define-the-task-trait)
Define the basic `Task` trait.
The methods:
* `spawn`: The initialiser that takes in the necessary config for this task and runs the task.
* `kill`: Abort the running task.
* `health_check`: Check if the task is still alive.
`cargo build`
```sh
$ cd $(git rev-parse --show-toplevel)/crates/jstzd && cargo build
Compiling jstzd v0.1.0-alpha.0 (/Users/huanchengchang/code/jstz/crates/jstzd)
Finished dev [unoptimized + debuginfo] target(s) in 0.64s
```

feat(jstzd): define Task trait

---

Cargo.lock
Cargo.toml
codecov.yml
crates/jstzd/Cargo.toml
crates/jstzd/src/docker/image.rs
crates/jstzd/src/docker/mod.rs
crates/jstzd/src/docker/runnable_image.rs
crates/jstzd/src/lib.rs

Implement traits / struct to run docker container that can later be used for jstzd
The related tasks are the following but not all of them are fully covered/tested yet (e.g. mounts/hosts etc)
[image](https://linear.app/tezos/issue/JSTZ-61/implement-dockerimage)
[runnable image](https://linear.app/tezos/issue/JSTZ-57/implement-dockerrunnableimage)
Implement the docker images traits and structs
cargo test --package jstzd --lib

feat(jstzd): implement image

---

Makefile
crates/jstzd/Cargo.toml
crates/jstzd/src/lib.rs
crates/jstzd/src/main.rs
crates/jstzd/tests/dummy.rs
nix/crates.nix

[jstz-44](https://linear.app/tezos/issue/JSTZ-44/enable-integration-tests-in-ci)
This PR enables all integration tests except those in `jstz_api`. This is primarily due to 
the fact that `jstz_api`'s integration tests need parallelising before being executed in a CI
environment.
To test locally, run one of the following (or all of them :) ):
```
cargo test -p jstzd
nix build .#checks.aarch64-darwin.cargo-test-int
make cov
```
To check in CI, look at the codecov output (which will automatically be commented below)

chore: enable integration testing in CI

---

Cargo.lock
crates/jstz_core/Cargo.toml
crates/jstz_core/src/kv/outbox.rs
crates/jstz_mock/src/lib.rs
crates/jstz_proto/Cargo.toml
crates/jstz_proto/src/api/smart_function.rs
crates/jstz_proto/src/context/ticket_table.rs
crates/jstz_proto/src/error.rs
crates/jstz_proto/src/executor/fa_withdraw.rs
crates/jstz_proto/src/executor/mod.rs
crates/jstz_proto/src/executor/smart_function.rs
crates/jstz_proto/src/executor/withdraw.rs
crates/jstz_proto/src/receipt.rs

Adds support for direct fa withdraw from external operation `RunFunction` and through smart function call. 
Because this is implemented as smart function call, also closes https://linear.app/tezos/issue/JSTZ-112/fa-withdrawal-smart-function-call for free.
This design is based on TZIP-029 except that the user initiates the withdrawal by calling the proxy smart function instead of the protocol.
This design has a few benefits over TZIP-029
1. Simpler and symmetric UX - Just like how users don't need to know the ticket details of a deposit, users should not need to know ticket details to withdraw. This information is correctly exposed in proxy smart function only.
2. Simplifies implementation in the protocol
3. Removes 1 level of indirection. It is obvious now that the proxy smart function …

feat(withdrawal): implement fa withdrawal

---

crates/jstzd/tests/dummy.rs
flake.lock
flake.nix
nix/crates.nix
nix/patches/0001-fix-octez-rust-deps-for-nix.patch

We will require octez for our integration tests for jstzd
This PR simply adds `octez-v21` using the Nix flake from https://gitlab.com/tezos/tezos/-/blob/master/flake.nix. 
Unfortunately, this will take along time to build, but the dependency will rarely change + once we have a Mac CI runner, we can use that as a cache. 
This PR includes two patches to the `tezos/tezos` flake:
- The first patches the `/bin/bash` issue and the `/usr/bin/env bash` shebang issue for `build.sh` in `src/rust_deps`
- The second patches the cargo dependencies for `src/rust_deps`, prefetching them using `importCargoLock`. Without this, the build fails as the `build.sh` script invokes `cargo` which tries to download the dependencies from `crates.io`. 
To execute the integration test that uses octez in a Nix …

chore(nix): add octez distribution to nix shell and integration tests

---

Cargo.lock
Cargo.toml
crates/jstzd/Cargo.toml
crates/jstzd/src/task/mod.rs
crates/jstzd/src/task/octez_node.rs
crates/jstzd/tests/octez_node_test.rs
crates/octez/src/node.rs
nix/crates.nix

[JSTZ-116](https://linear.app/tezos/issue/JSTZ-116/implement-octeznode)
Created struct `OctezNode` that implements `Trait`. Each instance of this struct represents an octez node process.
Note:
* There is no config validation in `OctezNode`. It simply attempts to call the node binary with the given config values and returns errors if there is any. It does not check if there are existing files or directories, e.g. previously created data directory. It is therefore possible that the created process does not use the given config values because it reads the config file from the previously created data directory. Validation is left to the caller. I thought about implementing these checks or removing existing files, but then I thought it might actually lead to unexpected results, so I decided to …

feat(jstzd): Implement OctezNode

---

CONTRIBUTING.md

As the jstz team grows, it is expected that PR management becomes inconsistent between deveopers. This PR adds PR guidelines to `CONTRIBUTING.md` that all jstz devs should adhere to where possible.
Closes [JSTZ-153](https://linear.app/tezos/issue/JSTZ-153/update-pr-guidelines-in-contributingmd)
Updates the Creating a pull request section of `CONTRIBUTING.md`

chore(contributing): update PR guidelines

---

Cargo.lock
crates/jstzd/Cargo.toml
crates/jstzd/src/task/endpoint.rs
crates/jstzd/src/task/mod.rs

[JSTZ-130](https://linear.app/tezos/issue/JSTZ-130/implement-endpoint)
Implemented struct `Endpoint` that represents an octez node RPC endpoint.
Note that the line `#[allow(dead_code)]` is added because the struct fields are not referenced anywhere else for now.

feat(jstzd): Implement Endpoint

---

crates/jstzd/src/task/directory.rs
crates/jstzd/src/task/endpoint.rs
crates/jstzd/src/task/mod.rs
crates/jstzd/src/task/octez_client.rs
crates/jstzd/src/task/octez_node.rs

[Octez client](https://linear.app/tezos/issue/JSTZ-126/implement-octezclient)
Add constructor for octez client
Note: the actual octez-client binary sets `base-dir` to `$HOME/.tezos-client` if no values are provided. i followed the spec and ignored this pattern and instead create a tempdir if the base-dir isn't specified.  
```
6 unit tests:
cargo test --package jstzd --lib -- task::octez_client::test
```

feat(jstzd): add octez client

---

.github/workflows/ci.yml

Cancel workflow runs for outdated commits to save resources and time.
Leverage [workflow concurrency](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#concurrency) to cancel redundant workflow runs.
Run [#11109580529](https://github.com/jstz-dev/jstz/actions/runs/11109580529) was cancelled when a new commit was pushed to this branch and replaced by [#11109992057](https://github.com/jstz-dev/jstz/actions/runs/11109992057).

ci: cancel workflow runs for outdated commits

---

Cargo.lock
crates/jstzd/Cargo.toml
crates/jstzd/src/task/octez_client.rs
crates/jstzd/tests/octez_client_test.rs

[141](https://linear.app/tezos/issue/JSTZ-141/implement-octezclientconfig-init)
blocked by #572 
This PR implements the `octez_client config init` 
In order to be consistent with the api for #582 i return the `Child` and let the user handle it.
Note: i omitted the following two argumetns as this is only used for `mockup mode` 
```
--bootstrap-accounts 
--protocol-constants
```
two integration test:
```
cargo test --package jstzd --test octez_client_test         
```
output:
```
running 2 tests
test command_fails_on_non_utf8_path ... ok
test config_init ... ok
```

feat(jstzd): add config init for client

---

crates/jstzd/src/task/octez_client.rs
crates/jstzd/tests/octez_client_test.rs

[implement gen keys](https://linear.app/tezos/issue/JSTZ-136/implement-octezclientgen-keys)
blocked by #577 
blocked by #572 
implement gen keys for octez client
added integration test:
`generates_keys`

Octez client gen keys

---

Cargo.lock
crates/jstzd/src/task/octez_node.rs
crates/octez/Cargo.toml
crates/octez/src/async_node.rs
crates/octez/src/lib.rs

Part of JSTZ-116.
[JSTZ-116](https://linear.app/tezos/issue/JSTZ-116/implement-octeznode)
Create an async version of `OctezNode` from crate `octez`.
This piece of code will replace the current `OctezNode` struct later on. For now it's kept in a separate module in order not to affect other pieces of code that are referencing `OctezNode`.
* Integration test: ran the code in the file `crate/jstzd/tests/octez_node_test.rs` and everything worked as expected.

feat(jstzd): Use async octez node

---

.github/workflows/docker.yml
.gitignore
docs/bridge.md
docs/installation.md
scripts/install-jstz-cli.sh

Getting docs ready for Engineering offsite
* Update docs for eng offsite with focus on installation and native bridge. 
* [Fix CI for docker image publication](https://github.com/jstz-dev/jstz/actions/runs/11225663601)
* Update install script to point to new published image

Eng offsite preparation

---

Cargo.lock
crates/jstzd/Cargo.toml
crates/jstzd/src/task/octez_client.rs
crates/jstzd/tests/octez_client_test.rs

[show url](https://linear.app/tezos/issue/JSTZ-146/implement-octezclientshow-address)
Show the address for the given alias. 
Implemented an `Address` struct that can be parsed from the stdout of the show address command
Added 3 integration tests
```
cargo test --package jstzd --test octez_client_test -- show_address
running 3 tests
test show_address_fails_for_non_existing_alias ... ok
test show_address_with_secret_key ... ok
test show_address ... ok
test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 6 filtered out; finished in 1.26s
```
4 unit tests:
```
cargo test --package jstzd --lib -- task::octez_client::test::address_try_from
running 4 tests
test task::octez_client::test::address_try_from_fails_on_invalid_input ... ok
test …
```

octez client: show address

---

Cargo.lock
crates/jstzd/src/lib.rs
crates/jstzd/src/task/octez_node.rs
crates/jstzd/tests/octez_client_test.rs
crates/jstzd/tests/octez_node_test.rs
crates/octez/Cargo.toml
crates/octez/src/async_node.rs
crates/octez/src/lib.rs
crates/octez/src/node_config.rs

Completes JSTZ-116.
[JSTZ-116](https://linear.app/tezos/issue/JSTZ-116/implement-octeznode)
Replaces run options in string with a proper struct in order to be more selective compared with accepting random strings.
Also moved `OctezNodeConfig` to crate octez since it's actually not just for jstzd.
Added test cases for unit testing in crate octez.

feat(jstzd): implement node run option

---

crates/jstzd/src/task/octez_client.rs
crates/jstzd/tests/octez_client_test.rs

Closes JSTZ-137.
[JSTZ-137](https://linear.app/tezos/issue/JSTZ-137/implement-octezclientadd-address)
Implemented `octez-client add address`.
Added one integration test:
```sh
$ cargo test --test octez_client_test add_address
running 1 test
test add_address ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 10 filtered out; finished in 1.01s
```

feat(jstzd): implement add_address

---

crates/jstz_cli/src/sandbox/daemon.rs

Bake for command is available only on latest protocols of a 'version' of the protocol. Since we upgraded to the latest octez release, ParisC is now the latest protocol
`cargo run -- sandbox start`

fix(sandbox): activate parisC in sandbox

---

crates/jstzd/tests/octez_baker_test.rs
crates/jstzd/tests/octez_client_test.rs
crates/jstzd/tests/utils.rs

Pulling common parts out of integration test cases since we have too many of them now.
Test cases for octez-client usually require setting up the node and the client. These steps are pretty much identical for those test cases and thus can be moved into the utils module, which makes those test cases neater.
Somehow clippy complains that the utils module is not used, so `#![allow(dead_code)]` is added to that entire module.
All existing test cases should pass.

refactor(jstzd): refactor tests

---

crates/jstzd/src/task/octez_node.rs
crates/jstzd/tests/octez_client_test.rs
crates/jstzd/tests/utils.rs
crates/octez/src/async/client.rs
crates/octez/src/async/node.rs
crates/octez/src/async/node_config.rs

It’s simpler to make the node endpoint of the client builder required so we don’t have to think about the default behavior. 
Will make a separate PR for the baker 
* clean up the config builder 
* the client will not have a fallback default endpoint
existing tests pass

remove default trait, endpoint for octez node

---

crates/octez/src/async/bootstrap.rs
crates/octez/src/async/protocol.rs

Completes JSTZ-149.
[JSTZ-149](https://linear.app/tezos/issue/JSTZ-149/implement-protocol)
Adds bootstrap smart rollups to the base protocol parameter set.
Each `BootstrapSmartRollup` instance has 4 fields:
```rs
pub struct BootstrapSmartRollup {
/// Rollup address.
address: SmartRollupHash,
/// Type of Proof-generating Virtual Machine (PVM) that interprets the kernel.
pvm_kind: SmartRollupPvmKind,
/// Smart rollup kernel in hex string.
kernel: String,
/// Michelson type of the rollup entrypoint in JSON format.
parameters_ty: Value,
}
```
To add a bootstrap rollup, the simplest way imo is to create a sandbox and actually deploy the rollup. The operation where the rollup is originated contains all the information needed to instantiate `BootstrapSmartRollup`. Added one example file that …

feat(jstzd): add bootstrap smart rollups to ProtocolParameterBuilder

---

Cargo.lock
crates/jstzd/tests/octez_client_test.rs
crates/octez/Cargo.toml
crates/octez/src/async/client.rs

Closes JSTZ-140.
[JSTZ-140](https://linear.app/tezos/issue/JSTZ-140/implement-octezclientoriginate-contract)
Implements `octez-client originate contract`. If the execution is successful, the contract address and the hash of the operation where the origination took place are returned.
* Unit test: new test cases
```sh
$ cargo test --lib task::octez_client::test::parse_
running 6 tests
test task::octez_client::test::parse_operation_hash_pattern_mismatch ... ok
test task::octez_client::test::parse_contract_address_pattern_mismatch ... ok
test task::octez_client::test::parse_operation_hash ... ok
test task::octez_client::test::parse_contract_address_bad_hash ... ok
test task::octez_client::test::parse_operation_hash_bad_hash ... ok
test task::octez_client::test::parse_contract_address ... ok …
```

feat(jstzd): originate contract

---

Cargo.lock
crates/jstzd/Cargo.toml
crates/jstzd/tests/octez_client_test.rs
crates/jstzd/tests/utils.rs
crates/octez/Cargo.toml
crates/octez/src/async/client.rs

Completes JSTZ-142.
[JSTZ-142](https://linear.app/tezos/issue/JSTZ-142/implement-octezclientwait-for)
Implements `octez-client wait for <op_hash>`.
* Integration test: added one test case
```sh
$ cargo test --test octez_client_test originate_contract_and_wait_for
running 1 test                                                                                                                                                        
< truncated baker logs >
test originate_contract_and_wait_for ... ok                                                               
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 14 filtered out; finished in 6.69s
```

feat(jstzd): implement wait_for

---

.github/workflows/ci.yml

Make sure that workflow runs for all main commits still get executed.
I merged PRs consecutively too soon and some workflow runs, e.g. https://github.com/jstz-dev/jstz/actions/runs/11627599091/job/32381228428, were cancelled by the succeeding merge. The workflow should be executed for all main commits, so I'm adding a condition to the workflow definition so that pushes to main are excluded from that rule.
According to [github docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context), `github.ref_name` refers to
> The short ref name of the branch or tag that triggered the workflow run. This value matches the branch or tag name shown on GitHub. For example, feature-branch-1.
> For pull …

ci: do not cancel workflow runs for main

---

flake.nix
nix/patches/0002-allow-floats-in-wasm-rollup.patch

Floats are disallowed by default in the wasmer run by the rollup due to an Etherlink constraint. This PR adds a patch to allow that within jstz.

fix(octez): allow float in octez rollup node

---

Cargo.lock
Cargo.toml
crates/jstz_engine/Cargo.toml
crates/jstz_engine/src/lib.rs
flake.nix
nix/crates.nix
nix/mozjs.nix

This PR adds the skeleton for the much long-awaited `jstz_engine` crate -- the crate that
will provide memory-safe wrappers on SpiderMonkey's `mozjs` crate. 
There is a simple unit test in `jstz_engine` demonstrating that SpiderMonkey does correctly
work in our CI. 
Initially I tried adding `mozjs` from crates.io, but this backfired since the released version of mozjs is
**5 years old**. 
So we'll need to use `patch.crates-io` 😔
An initial goal of this PR was to add the patched `mozjs` in such a way that would avoid 
us rebuilding SpiderMonkey each time (~10-15 minutes on a reasonably powerful machine). 
`mozjs-sys`'s build system luckily provides such an approach, where one builds an 'archive' 
containing `libjs_static.a` (statically compiled SpiderMonkey) and some autogenerated Rust …

feat: add `jstz_engine` crate

---

Cargo.lock
Cargo.toml

**Problem**: jstz sandbox is stuck
```sh
jstz sandbox start -d
tail -f ~/.jstz/sandbox-logs/kernel.log
```
Seeing no logs mean the kernel is stuck and cannot boot. 
How to find the issue. Firstly load the kernel using the `octez-smart-rollup-wasm-debugger` with empty inputs
```sh
make build-cli
echo '[[]]' > inputs.json
octez-smart-rollup-wasm-debugger --kernel crates/jstz_cli/jstz_kernel.wasm --inputs inputs.json
```
Erroneous outputs often look like:
```
Error
Unknown exception: Error(_, "float instructions are forbidden")
```
or 
```
Error
jstz_kernel:0x51a-0x550: link failure: unknown import "__wbindgen_placeholder__"."__wbindgen_object_drop_ref"
```
In this case, after #624, we need to fix the invalid import. To find the uses of the import, use `wasm2wat` to translate …

fix: remove `wasm-bindgen` imports in `jstz_kernel.wasm`

---

.prettierignore
Cargo.lock
Cargo.toml
crates/jstz_cli/src/deploy.rs
crates/jstz_cli/src/run.rs
crates/jstz_crypto/Cargo.toml
crates/jstz_crypto/src/public_key.rs
crates/jstz_crypto/src/public_key_hash.rs
crates/jstz_crypto/src/signature.rs
crates/jstz_node/Cargo.toml
crates/jstz_node/openapi.json
crates/jstz_node/src/services/operations.rs
crates/jstz_proto/Cargo.toml
crates/jstz_proto/src/context/account.rs
crates/jstz_proto/src/executor/deposit.rs
crates/jstz_proto/src/executor/fa_deposit.rs
crates/jstz_proto/src/executor/fa_withdraw.rs
crates/jstz_proto/src/executor/mod.rs
crates/jstz_proto/src/executor/smart_function.rs
crates/jstz_proto/src/operation.rs
crates/jstz_proto/src/receipt.rs

Adds OpenAPI schema for paths in `OperationService`
Added `ToSchema` definitions to types that used in the request and response objects of the `OperationService`, namely `SignedOperation` and `Receipt`. The `ToSchema` trait was auto derived where it made sense but for many types, this was not possible and annotating fields was the cleanest way to do it. Annotations also force developers to update the schema when the type changes in the future.
Type names in `jstz_proto` for `receipt` module had to be changed because they would override the types of similar names in the `operation` module.
Added `ToSchema` derivation for types in `jstz_crypto` crate.
```
cargo test -p jstz_nodecargo test -p jstz_node
```
```
cargo run -- sandbox start 
```

feat(jstz_node): implement openapi for operations service

---

crates/octez/src/async/node_config.rs

Fix the default value for `OctezNodeRunConfig::network`.
`OctezNodeConfigBuilder::build` uses the default value for `OctezNodeRunOptions` when `run_config` is not set, but this default value is not the one expected because `OctezNodeRunOptions::network` is a string and defaults to `""` instead of `"sandbox"`. This is fixed by implementing `Default` for `OctezNodeRunConfig` explicitly.
Added one test case.

fix(octez): set default network for run options

---

crates/jstzd/tests/octez_client_test.rs
crates/jstzd/tests/utils.rs
crates/octez/src/async/client.rs

Part of JSTZ-163; in preparation for #634.
[JSTZ-163](https://linear.app/tezos/issue/JSTZ-163/spawn-octezbaker-in-jstzd)
Make `OctezClientBuilder` build `OctezClientConfig` instead of `OctezClient` directly. `OctezClient` then can be instantiated by calling `new(config)`. `OctezClientConfig` is needed because configs for octez client will be added to `JstzdConfig` and I don't think the client itself should be part of the config.
Updated relevant test cases.

feat(octez): add OctezClientConfig

---

crates/jstzd/tests/utils.rs
crates/octez/src/async/baker.rs

Part of JSTZ-163; in preparation for #634.
[JSTZ-163](https://linear.app/tezos/issue/JSTZ-163/spawn-octezbaker-in-jstzd)
Remove `octez_node_data_dir` from baker because it's not in use and it's not part of the config for the `octez-baker` executable either.
All existing test cases should still work.

fix(octez): remove octez_node_data_dir from baker

---

crates/jstzd/tests/protocol_test.rs
crates/octez/src/async/protocol.rs

Part of JSTZ-163; in preparation for #634.
[JSTZ-163](https://linear.app/tezos/issue/JSTZ-163/spawn-octezbaker-in-jstzd)
Expose `Protocol` after a protocol file is built. This is required because calling `activate_protocol` after a parameter file is generated still needs the protocol hash and that cannot be extracted from the parameter file.
All existing test cases should still work.

feat(octez): make ProtocolParameterBuilder return protocol

---

Cargo.lock
crates/jstzd/Cargo.toml
crates/jstzd/src/task/jstzd.rs
crates/jstzd/src/task/mod.rs
crates/jstzd/src/task/utils.rs
crates/jstzd/tests/jstzd_test.rs
crates/jstzd/tests/octez_node_test.rs
crates/jstzd/tests/utils.rs
nix/crates.nix

Completes JSTZ-163.
[JSTZ-163](https://linear.app/tezos/issue/JSTZ-163/spawn-octezbaker-in-jstzd)
Spawn baker in jstzd.
Note that there is a small usability issue regarding bootstrap accounts: these accounts cannot be used by the baker except for the hard-coded activator account. This is because bakers only use accounts with secret keys imported and bootstrap accounts in parameter files only have public keys. This is especially a problem when users use their own template parameter files with bootstrap accounts attached. There is no solution for now. I don't think hardcoding a "base baker" account inside `ProtocolParameterBuilder` is a good idea since it adds irrelevant logic to that module.
Updated `crates/jstzd/tests/jstzd_test.rs`.
```sh
$ cargo test --test jstzd_test
running 1 test
< …
```

feat(jstzd): spawn baker in jstzd

---

crates/jstzd/src/task/octez_rollup.rs
crates/octez/src/async/rollup.rs

The rollup config didn't have an option to add the kernel debug  file
Add the path to kernel debug file to rollup config
updated the unit test

Octez: add kernel file to rollup config

---

crates/jstzd/tests/octez_client_test.rs
crates/jstzd/tests/utils.rs
crates/octez/src/async/client.rs

Completes JSTZ-144.
[JSTZ-144](https://linear.app/tezos/issue/JSTZ-144/implement-octezclientsend-rollup-inbox-message)
Implement `send_rollup_inbox_message` which performs `octez-client send smart rollup message <messages> from <src>`.
* Unit test: added tests for parsing block hashes from execution output
```sh
$ cargo test --lib async::client::test::test_parse_block_hash
running 1 test
test r#async::client::test::test_parse_block_hash ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 77 filtered out; finished in 0.00s
$ cargo test --lib async::client::test::parse_block_hash
running 2 tests
test r#async::client::test::parse_block_hash_pattern_mismatch ... ok
test r#async::client::test::parse_block_hash_bad_hash ... ok
test result: ok. 2 passed; 0 failed; 0 ignored; 0 …
```

feat(octez): implement send_rollup_inbox_message

---

crates/jstzd/tests/jstzd_test.rs
crates/jstzd/tests/octez_client_test.rs

[CI](https://github.com/jstz-dev/jstz/actions/runs/11781846583/job/32815571186) just randomly failed (in some PR checks as well.) This happens a bit too often. For some reason,
* the baker process was not removed, i.e. still listed in `ps` output, after 10 seconds
* calling `octez-client wait for` took longer than expected when it should have returned almost immediately when the operation was present
* etc
and tests failed because of these. This never happened to me when I ran tests locally though.
Tweaked some test settings so that the tests are less likely to be flakey:
* Wait a bit longer in integration tests so that tests don't fail due to possibly some delay in the runner machine. That octez-client test might be longer, but it's still better than tests randomly failing.
* Give the …

fix(jstzd): mitigate test flakiness

---

crates/jstzd/resources/bootstrap_contract/exchanger.json
crates/jstzd/resources/bootstrap_contract/jstz_native_bridge.json
crates/jstzd/src/lib.rs
crates/jstzd/tests/contract_test.rs
crates/jstzd/tests/jstzd_test.rs
crates/jstzd/tests/utils.rs
crates/octez/src/async/client.rs

Closes JSTZ-166.
[JSTZ-166](https://linear.app/tezos/issue/JSTZ-166/deploy-xtz-bridge)
Adds contracts `exchanger` and `jstz_native_bridge` to the sandbox as bootstrap contracts.
Integration test:
* Updated `jstzd_test`
* Added `contract_test` to ensure that the contract json files always match the michelson code in `contracts/`

feat(jstzd): add bootstrap contracts exchanger and jstz_native_bridge

---

crates/jstz_api/src/js_log.rs
crates/jstz_node/openapi.json
crates/jstz_node/src/services/error.rs
crates/jstz_node/src/services/logs/db.rs
crates/jstz_node/src/services/logs/mod.rs
crates/jstz_proto/src/js_logger.rs

Implements OpenAPI for LogsService
We probably want a single client gen binding that supports all node endpoints. With that in mind, the persistent log endpoints have been removed from conditional compilation and instead return a Bad Request if it is called on a node that was not compiled with persistent logging.
(Note: We should change enabling/disabling persistent logging enable from conditional compilation to runtime configuration)
Removed the `QueryResponse` which is a wrapper over LogRecord.
Removed `QueryParams` which acts as a function dispatch over the db api. Instead, just called the db api directly because they are 1 to 1 with their handlers.
```
cargo test -p jstz_node api_doc_regression
cargo test --features persisitent-logging -p jstz_node api_doc_regression
```

feat(jstz_node): implement openapi for logs service

---

crates/jstzd/src/task/jstzd.rs
crates/jstzd/tests/jstzd_test.rs

Part of JSTZ-121.
Added route `/health` to `JstzdServer`. Note that in this PR the octez node and baker instances in Jstzd are wrapped with `Arc<RwLock<_>>` because they need to be passed to the server as the state. I know we can just make baker derive `Clone` and then clone `JstzdServer.jstzd` and things under the hood are also wrapped with `Arc`, but I think it's clearer like this with explicit `Arc` and `RwLock` in this module and we know for sure that these instances are not duplicated but shared when they are cloned.
* Integration test: updated `crates/jstzd/tests/jstzd_test.rs` to use the health check endpoint

feat(jstzd): implement health check endpoint in jstzd server

---

crates/octez/src/async/node.rs
crates/octez/src/async/node_config.rs

Fix typo missed out in previous PRs.
Fix typo missed out in previous PRs.
All tests should still pass as there is no new logic introduced.

fix(octez): fix typo in octez node config

---

crates/octez/src/async/endpoint.rs

Implement `Serialize` for `Endpoint` so that it can be dumped in JSON.
Added one unit test.

feat(octez): implement serialize for endpoint

---

Makefile
crates/jstz_cli/src/deploy.rs
crates/jstz_cli/src/run.rs
crates/jstz_crypto/src/hash.rs
crates/jstz_crypto/src/public_key.rs
crates/jstz_crypto/src/public_key_hash.rs
crates/jstz_crypto/src/secret_key.rs
crates/jstz_crypto/src/signature.rs
crates/jstz_node/openapi.json
crates/jstz_node/src/api_doc.rs
crates/jstz_node/src/lib.rs
crates/jstz_proto/src/api/smart_function.rs
crates/jstz_proto/src/context/account.rs
crates/jstz_proto/src/executor/deposit.rs
crates/jstz_proto/src/executor/fa_deposit.rs
crates/jstz_proto/src/executor/fa_withdraw.rs
crates/jstz_proto/src/executor/smart_function.rs
crates/jstz_proto/src/operation.rs
crates/jstz_proto/src/receipt.rs

This PR fixes the awkward external tagging that serde uses for Json serialisation with the following changes:
1. Cryptos enums are marked  with `#[serde(untagged)]`
2. Non-cryptos enums are marked as  `#[serde(tag = "_type")]`
These changes ensures that we get generated code that makes sense in Typescript from https://github.com/jstz-dev/jstz/pull/644
Code should build, tests should pass
`make`

Fix: serde on enums

---

.github/workflows/generate-node-client.yml
crates/jstz_node/openapi.json
crates/jstz_node/stainless.yml
crates/jstz_proto/src/operation.rs
crates/jstz_proto/src/receipt.rs

This PR sets up [Stainless](https://app.stainlessapi.com/trilitech/projects) Github Action to automatically generate the client library and push changes to `jstz-client` repo.  The auto generated bindings will be useful as we continue to evolve the Jstz node endpoints and communication bindings. 
Generated code: https://github.com/jstz-dev/jstz-client
* Adds generate client job
* Adds stainless.yaml config
* Represents operation hash as byte array
Evaluation doc:  https://docs.google.com/document/d/1kU_xjPYoHaqgmewAZlJDpkJ25FTNnccq8Wb88YQhcFk/edit?usp=sharing
| | Description | Stainless
|-- | -- | --
| Code quality | Coherent generated code: (M1) Separation by resource, (M2) Sensible calling conventions and method names, (M3) Able to return the body type and Response, async, (M4) …

feat(ci): integrates stainless client lib gen into ci

---

crates/jstzd/src/task/jstzd.rs
crates/jstzd/tests/jstzd_test.rs
nix/crates.nix

Changes the way the test checks if baker has been destroyed because it does not always work.
The original idea of checking if a baker process is indeed destroyed is to check if there is any process with `octez-baker` in its name with `ps`. This works fine when there is only one such test running each time, but it becomes problematic when there are multiple tests and even multiple workers running in parallel -- the baker launched by each test might have been destroyed, but `ps` also shows baker processes launched by other tests.
This check is now performed with a different approach. ~The baker binary is copied to a temp file and then jstzd launches the baker with that clone. The test still looks for that name in `ps` and removes that clone at the end of the test. This approach should be …

fix(jstzd): revise baker check in jstzd test

---

crates/octez/src/async/directory.rs

feat(octez): serialise directory

---

Cargo.toml
crates/octez/src/async/client.rs

Serialise octez client config. Note that the `base_dir` field is omitted if it's a temp path because it's generated and managed by the program and users should not see it when they fetch the serialised config from the jstzd server.

feat(octez): serialise octez client config

---

crates/jstzd/src/task/jstzd.rs
crates/jstzd/tests/jstzd_test.rs

Closes JSTZ-121.
Wrap the test in a future so that we can still call `stop` at the end of the test to clean up everything before the program exits should the test fail and panic. Otherwise, the test program does not actually close after the panic and the baker and octez-node  processes remain running even after the test program terminates.
In a tokio task, `panic` is captured and returned as `Err`, so handling failed assertions like this is much simpler than trying to do something like `catch_unwind`.
The test should still work as is.

feat(jstzd): use AsyncDropper in JstzdServer

---

crates/jstzd/src/config.rs
crates/jstzd/src/lib.rs
crates/octez/src/async/baker.rs
crates/octez/src/async/client.rs
crates/octez/src/async/node_config.rs
crates/octez/src/async/protocol.rs

Deserialise jstzd config provided by users. The config looks like
```json
{
"octez_node": {...},
"octez_client": {...},
"octez_baker": {...},
"protocol": {...},
"server_port": 1234
}
```
where each object entry matches the corresponding config builder.

feat(jstzd): deserialise user config

---

crates/jstzd/src/task/utils.rs
crates/jstzd/tests/octez_client_test.rs
crates/jstzd/tests/utils.rs

Following #645.
Reuse `poll` in `retry` since they do very similar things. Also added some tests for these two functions.

refactor(jstzd): use poll in retry

---

crates/jstzd/src/config.rs
crates/jstzd/src/task/jstzd.rs
crates/octez/src/async/baker.rs
crates/octez/src/async/client.rs
crates/octez/src/async/protocol.rs

Build jstzd config from user config.
The flow goes as follows:
1. Does the user provide a config file?
* Y: try to read the config file
* N: use the default config where a bootstrap account is inserted
1. Build node config
1. Does the config covers octez client?
* Y: use it as is
* N: create one pointing to the node's rpc endpoint
1. Build baker config and fill in information about the node and the client if it's not given
1. Build protocol parameters
1. Done
Loading bootstrap contracts and rollups is in a separate PR.
Note that config validation is not implemented, so users are responsible for misconfiguration, e.g. octez client using something other than the node's rpc endpoint.
* Unit test: added test …

feat(jstzd): build jstzd config from user config

---

crates/jstzd/src/config.rs
crates/jstzd/src/lib.rs
crates/jstzd/tests/jstzd_test.rs
crates/octez/src/async/bootstrap.rs
crates/octez/src/async/protocol.rs

Insert jstz smart contracts into user config.
Note that user contracts whose addresses collide with those reserved for jstz contracts will overwrite jstz contracts. This aligns with the current implementation where bootstrap contracts in the base parameter file take precedence, even if it means that jstz won't launch in such cases.

feat(jstzd): insert jstz bootstrap contracts

---

crates/jstz_node/openapi.json
crates/jstz_node/src/services/operations.rs

Adds an endpoint to hash operations in Jstz so that user's can have consistent hashing without wasm dependency. A slightly nicer UX would be an indutry standard binary encoding that is consistent across rust, typescript and other languages but existing solutions are not effortless drop ins and will require additional effort at a later time.
* Adds the hashing endpoint
*  Updates openapi
* 
`cargo test -p jstz_node api_doc_regression`

feat(node): add hash operation endpoint

---

crates/jstzd/src/task/jstzd.rs
crates/jstzd/tests/jstzd_test.rs

Implement shutdown signal in jstzd server.
If a program spins up jstzd server and keeps it running, it needs a way to know when jstzd server is terminated, e.g. after someone calls the shutdown endpoint. Otherwise, the program would just hang there not knowing when it can exit. This PR adds a `wait` method to achieve that. When `wait` finally returns, it means that jstzd server is shut down.
* Integration test: updated jstzd test to verify that `wait` actually works

feat(jstzd): implement shutdown signal in jstzd server

---

crates/jstzd/src/config.rs
crates/jstzd/src/task/child_wrapper.rs
crates/jstzd/src/task/jstzd.rs
crates/jstzd/tests/jstzd_test.rs

[task](https://linear.app/tezos/issue/JSTZ-165/spawn-jstznode-in-jstzd)
The ci fails for the same reason as [the rollup PR](https://github.com/jstz-dev/jstz/tree/leounoki-jstz-164/spawn-rollup-3)
* spawn jstz-node in jstzd
* introduce a type aliass `Shared` and refactored the jstzd by adding a blanket implementation so we can avoid having to write `Arc<RwLock<..` everywhere
add integration tests the runs successfully locally 
```
nix flake check
```

Jstzd: spawn node in jstzd server

---

Cargo.lock
crates/jstzd/Cargo.toml
crates/jstzd/src/config.rs

There is a problem with simply loading files from `CARGO_MANIFEST_DIR`: the directory is no longer available after the binary is built and therefore the binary will complain that the files do not exist.
Pack bootstrap contracts into builds at compile time with `rust_embed` so that they remain accessible to the binary. This is already done for protocol parameters, so the only part with problems is the bootstrap contracts. This PR changes the way those files are loaded.
Manually built jstzd and ran the executable in an octez container and the sandbox launched as expected.
This cannot really be tested with any of the existing test now. As long as all existing tests still work, we should be good to go.

fix(jstzd): include bootstrap contracts in builds

---

crates/jstzd/src/config.rs
crates/jstzd/src/task/jstzd.rs

[jstz node config](https://linear.app/tezos/issue/JSTZ-240/use-real-jstz-node-in-config)
replace the dummy jstz node with actual one in the config
extened the config unit test

Jstzd: use real jstz node config

---

crates/jstzd/src/task/jstzd.rs
crates/jstzd/tests/jstzd_test.rs
crates/octez/src/async/rollup.rs

[serialzie rollup config](https://linear.app/tezos/issue/JSTZ-241/implemetn-rollup-config-endpoint)
serialize the rollup config and return as part of the config endpoint
add integration test to jstzd
add unit test

Jstzd: serialize rollup config

---

crates/jstz_node/src/config.rs
crates/jstzd/src/task/jstzd.rs
crates/jstzd/tests/jstzd_test.rs
crates/octez/src/async/rollup.rs

[serialize node config](https://linear.app/tezos/issue/JSTZ-242/implemetn-jstz-node-config-endpoint)
serialize the node config 
unit test 
integratio for jstzd test

Leounoki jstz 242/serialize jstz node config

---

Cargo.lock
Cargo.toml
crates/jstzd/Cargo.toml
crates/jstzd/src/config.rs
crates/jstzd/src/lib.rs
crates/jstzd/src/task/jstzd.rs
crates/jstzd/tests/jstzd_test.rs
crates/jstzd/tests/main_test.rs
crates/jstzd/tests/octez_client_test.rs
nix/crates.nix

Completes JSTZ-168.
Spins up jstzd server on `jstzd run <config_path>`. It makes things easier if we wait a bit for jstzd before spinning up jstzd server, so I made some changes to that part.
Threading is necessary in the tests because `assert_cmd` unfortunately does not handle async yet.
* Integration test: updated existing test cases

 feat(jstzd): launch jstzd server with cli

---

crates/jstzd/src/lib.rs
crates/jstzd/tests/main_test.rs

Part of JSTZ-189.
[JSTZ-189](https://linear.app/tezos/issue/JSTZ-189/monitor-health-and-capture-signals-after-calling-jstzdserverrun)
Terminate jstzd on SIGTERM and SIGINT.
Note that we still need to find a way to shut down all processes when SIGKILL hits the server process. What happens now is that the subprocesses become orphans after the server is terminated.
* Integration test: added back `default_config` with SIGTERM and added one test case with SIGINT

feat(jstzd): listen to os signals

---

crates/jstz_engine/src/compartment.rs
crates/jstz_engine/src/context.rs
crates/jstz_engine/src/lib.rs
nix/crates.nix

A SpiderMonkey `Runtime` contains the state of the garbage collector. The collector partitions the JavaScript heap into compartments. `Compartment`s have the invariant that no object in the compartment can contain pointers to another compartment. 
A `Context` contains the state for a virtual machine that executes and manages JavaScript objects within a `Runtime`. It can compile and execute scripts, get and set object properties, call JavaScript functions, convert JavaScript data from one type to another, create objects, and so on. 
This PR adds the skeletons for the `Compartment` and `Context` types & traits. 
We track the compartment that an object or context is in at the type-level using capability traits. 
```
cargo nextest run --package jstz_engine
```

feat(jstz_engine): add skeletons for `Context` and `Compartment`

---

crates/jstz_engine/src/context.rs
crates/jstz_engine/src/lib.rs
crates/jstz_engine/src/realm.rs

Adds an interface for `Realm`s. A realm represents a distinct execution environment for JavaScript code, 
encapsulating global objects, intrinsic objects, and a separate environment for executing scripts and modules.
This PR adds the ability to:
- Create new realms (which currently, by default, creates a new compartment),
- Enter new realms using `Context::enter_realm`
- Leave the realm once the `Context` is dropped. 
```
cargo nextest run --package jstz_engine
```

feat(jstz_engine): add support for creating, entering and exiting `Realm`s

---

crates/jstz_engine/src/lib.rs
crates/jstz_engine/src/script.rs

Adds memory and type-safe version of `JSScript`.
Adds ability to compile and evaluate scripts. 
```
cargo nextest run --package jstz_engine
```

feat(jstz_engine): add safe wrapper for JS `Script`s

---

crates/jstz_engine/src/gc/mod.rs
crates/jstz_engine/src/gc/ptr.rs
crates/jstz_engine/src/lib.rs
crates/jstz_engine/src/script.rs

Problem: SpiderMonkey has an incremental garbage collector that relies on write barriers to maintain a consistency reachability set. 
Intuitive view of incremental GC:
1. Take snapshot of compartment
2. Mark a bit, get interrupted
3. Execute some code
4. Mark a bit again, ...
...
5. Compartment fully marked, do sweeping
However, in step 3, the reachability set of objects may change. Write barriers are a solution to notify the GC when the reachability set *might* change e.g. on a write to a pointer.
This PR implements `GcPtr`, a safe write barriered pointer. 
Dereferencing the pointer is still unsafe since the caller must guarentee that the object that the
pointer points to is valid. 
```
cargo nextest run --package jstz_engine
```

feat(jstz_engine): implement a write-barriered GC pointer abstraction

---

.config/nextest.toml
nix/crates.nix

Closes JSTZ-208.
[JSTZ-208](https://linear.app/tezos/issue/JSTZ-208/ci-terminate-slow-tests)
Terminate tests that take too much time in CI to save resources and prevent unexpected long-running tests from blocking the CI runner.
A test branch contains changes in this PR and a dummy test that does nothing but sleeps for 2 minutes. Workflow run: https://github.com/jstz-dev/jstz/actions/runs/12035957074/job/33556133877
The test was terminated and the overall check failed as expected.

ci: terminate slow tests

---

crates/jstz_crypto/src/public_key.rs

Part of JSTZ-247.
[JSTZ-247](https://linear.app/tezos/issue/JSTZ-247/display-useful-information-for-users)
In preparation for #721.
Get public key hashes from public keys.

feat(jstz_crypto): get hash of public keys

---

crates/jstzd/src/task/octez_rollup.rs
crates/octez/src/async/rollup.rs

Write rollup logs to a log file instead of stdout/stderr.
Ran jstzd locally and did not see any rollup node logs.

feat(octez): write rollup log to file

---

crates/jstzd/src/config.rs
crates/jstzd/tests/main_test.rs
crates/octez/src/async/baker.rs

Write baker logs to a log file instead of stdout/stderr.
Ran jstzd locally and did not see any baker logs.

feat(octez): write baker log to file

---

crates/jstzd/src/task/octez_node.rs
crates/octez/src/async/node.rs

Write octez-node logs to a log file instead of stdout/stderr.
Ran jstzd locally and did not see any octez-node logs.

feat(octez): write node log to file

---

crates/jstzd/src/config.rs
crates/jstzd/tests/main_test.rs

Closes JSTZ-245.
[JSTZ-245](https://linear.app/tezos/issue/JSTZ-245/set-default-values-for-fields-that-are-not-filled-in-input-config)
Insert the required bootstrap accounts into jstzd config anyway. Previously they were only inserted when user config would be absent, but this is quite inconvenient and does not really make sense. I was a bit concerned about the required accounts colliding with accounts provided by users, but this should not be the main concern for now. We should fail the launch when there is any address collision, but that will be implemented later on.
* Unit test: confirmed that the bootstrap accounts are inserted anyway
* Integration test: jstzd launched successfully without the required bootstrap accounts specified in the config file

fix(jstzd): insert bootstrap accounts into config

---

crates/octez/src/async/bootstrap.rs
crates/octez/src/async/protocol.rs

Part of JSTZ-247.
[JSTZ-247](https://linear.app/tezos/issue/JSTZ-247/display-useful-information-for-users)
In preparation for #721.
Store bootstrap accounts in protocol parameters so that they can be retrieved later.

feat(octez): store bootstrap accounts in protocol parameters

---

crates/jstz_cli/src/bridge/deposit.rs
crates/jstz_cli/src/bridge/withdraw.rs
crates/jstz_cli/src/config.rs
crates/jstz_cli/src/jstz.rs
crates/jstz_cli/src/repl/debug_api/account.rs
crates/jstz_cli/src/run.rs
crates/jstz_core/src/kv/outbox.rs
crates/jstz_core/src/kv/transaction.rs
crates/jstz_crypto/src/error.rs
crates/jstz_crypto/src/hash.rs
crates/jstz_crypto/src/lib.rs
crates/jstz_crypto/src/public_key_hash.rs
crates/jstz_crypto/src/smart_function_hash.rs
crates/jstz_kernel/src/inbox.rs
crates/jstz_kernel/src/lib.rs
crates/jstz_kernel/src/parsing.rs
crates/jstz_mock/src/lib.rs
crates/jstz_mock/src/message/fa_deposit.rs
crates/jstz_node/src/services/logs/mod.rs
crates/jstz_proto/src/api/ledger.rs
crates/jstz_proto/src/api/smart_function.rs
crates/jstz_proto/src/context/account.rs
crates/jstz_proto/src/executor/fa_deposit.rs
crates/jstz_proto/src/executor/fa_withdraw.rs
crates/jstz_proto/src/executor/smart_function.rs
crates/jstz_proto/src/executor/withdraw.rs
crates/jstzd/tests/octez_client_test.rs
crates/octez/src/async/client.rs

[Introduce smart function hash](https://linear.app/tezos/issue/JSTZ-251/introduce-smartfunctionhash)
In preparation for [254](https://linear.app/tezos/issue/JSTZ-254/migrate-to-newaddress-type)
1. Introduce a `Hash` trait that both the public key hash for user account and sf hash for sf account will use
```
pub trait Hash<'de>:
Sized
+ ...
{
fn to_base58(&self) -> String;
fn from_base58(data: &str) -> Result<Self>;
fn as_bytes(&self) -> &[u8];
fn digest(data: &[u8]) -> Result<Self>;
}
```
2. make `PublicKeyHash` implement the JstzHash
3. Introduce `SmartFunctionHash` that implements the JstzHash. this hash will be used for sf address and starts with `TZ1...`
unit test

feat: implement smart function hash

---

crates/jstz_proto/src/context/mod.rs
crates/jstz_proto/src/context/new_account.rs
crates/jstz_proto/src/error.rs

[introduce new address](https://linear.app/tezos/issue/JSTZ-252/introduce-enum-newaddress)
in preparation for [254](https://linear.app/tezos/issue/JSTZ-254/migrate-to-newaddress-type)
introduce NewAddress type that supports both user(tz..) and sf(KT1..) address
add unit test

introduce new address type

---

crates/octez/src/async/bootstrap.rs

Part of JSTZ-247.
[JSTZ-247](https://linear.app/tezos/issue/JSTZ-247/display-useful-information-for-users)
In preparation for #721.
Fetch the address of a bootstrap account.
* Unit testing: updated one test to cover this method

feat(octez): get bootstrap account address

---

Cargo.lock
crates/jstzd/Cargo.toml
crates/jstzd/src/task/jstzd.rs

Completes JSTZ-247.
[JSTZ-247](https://linear.app/tezos/issue/JSTZ-247/display-useful-information-for-users)
Print information about bootstrap accounts when all components are ready.
* Manual testing: ran jstzd locally and observed the printed lines
```sh
$ ./jstzd run /tmp/config.json 
__________
\  jstz  /
)______(
|""""""|_.-._,.---------.,_.-._
|      | | |               | | ''-.
|      |_| |_             _| |_..-'
|______| '-' `'---------'` '-'
)""""""(
/________\
`'------'`
.------------.
/______________\
0.1.0-alpha.0 https://github.com/jstz-dev/jstz
+--------------------------------------+---------------------+
| Address                              | XTZ Balance (mutez) |
+======================================+=====================+
| …
```

feat(jstzd): print bootstrap account info

---

crates/jstz_engine/src/gc/mod.rs
crates/jstz_engine/src/gc/ptr.rs
crates/jstz_engine/src/gc/trace.rs

We'll need to trace native Rust objects. To do so, we'll need a `Trace` trait (and a `Finalize` for drops)
This PR:
- Defines the `Trace` and `Finalize` traits + some helpful macros
- Implements the `Trace` and `Finalize` trait for many common types.
Code isn't easily testable (relies on calling out to SM GC where `Tracer` is defined). I suggest we ignore the codecov check for this PR -- these implementations will become tested as we implement APIs on top of them

feat(jstz_engine): define the `Trace` and `Finalize` traits

---

crates/jstz_cli/src/account.rs
crates/jstz_cli/src/bridge/deposit.rs
crates/jstz_cli/src/bridge/mod.rs
crates/jstz_cli/src/bridge/withdraw.rs
crates/jstz_cli/src/config.rs
crates/jstz_cli/src/deploy.rs
crates/jstz_cli/src/kv.rs
crates/jstz_cli/src/logs/trace.rs
crates/jstz_cli/src/main.rs
crates/jstz_cli/src/repl/mod.rs
crates/jstz_cli/src/run.rs
crates/jstz_cli/src/sandbox/daemon.rs
crates/jstz_cli/src/sandbox/mod.rs

Part of JSTZ-248.
[JSTZ-248](https://linear.app/tezos/issue/JSTZ-248/revise-jstz-cli-so-that-it-works-with-jstzd)
In preparation for #732.
We want to make jstz_cli make http requests to fetch jstzd config so that it can be used against jstzd. The `load` method is synchronous now, but we cannot use `reqwest::blocking` because this method is normally called inside async functions elsewhere. This means that we need to change this method itself and other functions where this is called to async.
Note that `load_sync` and `reload_sync` are created as a synchronous version of the `load` and `reload` methods just for the sandbox. Since the sandbox has nothing to do with jstzd, it will never make http calls to fetch jstzd config and thus it can keep using the synchronous version. This avoids …

feat(jstz_cli): make Config::load async

---

crates/jstz_cli/src/bridge/deposit.rs
crates/jstz_cli/src/config.rs
crates/jstz_cli/src/sandbox/mod.rs
crates/jstz_cli/src/utils.rs

Completes JSTZ-248.
[JSTZ-248](https://linear.app/tezos/issue/JSTZ-248/revise-jstz-cli-so-that-it-works-with-jstzd)
Make `jstz_cli` compatible with `jstzd`. This is more like a temporary patch before `jstz sandbox` is taken down.
To use `jstz_cli` with a running `jstzd` instance, an environment variable `USE_JSTZD` needs to be set to `true` or `1`. `jstz_cli` will then load config from jstzd server at 127.0.0.1:55555 (default jstzd server endpoint) and find the nodes and client directory.
Note that if a user uses `jstz_cli` with `jstz sandbox` first and then switch to `jstzd`, the next usage against `jstz sandbox` will fail because the data directory path stored in the config will still point to `jstzd`. I think this is fine for now since we don't plan to keep `jstz sandbox` alive in the …

feat(jstz_cli): make jstz_cli compatible with jstzd

---

crates/jstz_kernel/src/lib.rs
crates/jstz_kernel/src/parsing.rs
crates/jstz_mock/src/lib.rs

[task link](https://linear.app/tezos/issue/JSTZ-262/use-newaddress-for-jstz-kernel)
Prep for [254](https://linear.app/tezos/issue/JSTZ-254/migrate-to-newaddress-type)
use new address type for jstz kernel
add unit tests

refactor(jstz_kernel): mirgrate to new_address

---

crates/jstz_proto/src/api/smart_function.rs

deleted the nonce for sf creation [here](https://github.com/jstz-dev/jstz/pull/729) but we should recover it since contract can create another contract and nonce is required to guarantee the uniqueness of the addresss

fix(jstz_proto): increment nonce

---

crates/jstz_api/tests/wpt.rs
crates/jstz_api/tests/wptreport.json
crates/jstz_wpt/src/report.rs

Closes JSTZ-256.
[JSTZ-256](https://linear.app/tezos/issue/JSTZ-256/run-async-wpt-test-cases)
Fixes the wpt runner in jstz_api so that it covers async test cases. Asynchronous tests, including those wrapped in promises, were not properly executed because `eval` only runs the synchronous tests and puts async ones in the task queue. The runtime task queue was never touched afterwards and thus the async tests were simply abandoned. With changes in this PR, async test cases can be executed as expected, and also because of this, we don't need the `Null` test status because at the end of the async task chain, test suites are completed and therefore there is always a meaningful test status returned.
Note that the task queue must be executed after all synchronous tests finish, i.e. after all …

fix(wpt): run async tests and collect results

---

crates/octez/src/async/file.rs

Part of JSTZ-250.
[JSTZ-250](https://linear.app/tezos/issue/JSTZ-250/use-tempfile-for-kernel-debug-log)
Expose the path to the file inside `FileWrapper`.
* Unit test: added two tests
```sh
$ cargo test async::file::tests::path
running 2 tests
test r#async::file::tests::path_tempfile ... ok
test r#async::file::tests::path ... ok
test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 108 filtered out; finished in 0.00s
```

feat(octez): get path from file wrapper

---

crates/jstzd/src/config.rs
crates/jstzd/src/task/octez_rollup.rs
crates/jstzd/tests/jstzd_test.rs
crates/octez/src/async/rollup.rs

Part of JSTZ-250.
[JSTZ-250](https://linear.app/tezos/issue/JSTZ-250/use-tempfile-for-kernel-debug-log)
Use `FileWrapper` in jstz node config for kernel debug log.
`kernel_debug_file` does not get deserialised since we don't have any use case for that, so we don't need to implement `Deserialize` for `FileWrapper`. Overall, carrying a file like this in config is definitely not good because it complicates de/serialisation. There should be a refactor later on to get rid of all these whatever wrapper in config types and instead hold them somewhere else like in the jstzd state or so.
* Unit test: added one tests. All existing relevant tests should still work since fundamentally there is nothing changed.

feat(jstz): use file wrapper for kernel debug log in config

---

crates/jstz_cli/src/bridge/withdraw.rs
crates/jstz_cli/src/config.rs
crates/jstz_cli/src/deploy.rs
crates/jstz_cli/src/repl/debug_api/account.rs
crates/jstz_cli/src/repl/mod.rs
crates/jstz_cli/src/run.rs
crates/jstz_kernel/src/inbox.rs
crates/jstz_kernel/src/lib.rs
crates/jstz_kernel/src/parsing.rs
crates/jstz_mock/src/message/fa_deposit.rs
crates/jstz_node/openapi.json
crates/jstz_node/src/services/logs/mod.rs
crates/jstz_proto/src/api/ledger.rs
crates/jstz_proto/src/api/smart_function.rs
crates/jstz_proto/src/context/account.rs
crates/jstz_proto/src/context/new_account.rs
crates/jstz_proto/src/context/ticket_table.rs
crates/jstz_proto/src/executor/deposit.rs
crates/jstz_proto/src/executor/fa_deposit.rs
crates/jstz_proto/src/executor/fa_withdraw.rs
crates/jstz_proto/src/executor/mod.rs
crates/jstz_proto/src/executor/smart_function.rs
crates/jstz_proto/src/executor/withdraw.rs
crates/jstz_proto/src/js_logger.rs
crates/jstz_proto/src/operation.rs
crates/jstz_proto/src/receipt.rs
crates/jstz_proto/src/request_logger.rs

[task link](https://linear.app/tezos/issue/JSTZ-261/use-newaddress-for-jstz-proto)
In preparation for [171](https://linear.app/tezos/issue/JSTZ-171/change-smart-function-addresses-to-kt1)
final step of migrating to the new address type in jstz_proto
removed the old address type completely and use the new addres type
NOTE: this PR doesn't change the behaviour of jstz proto and KT address will be supported in the upcoming PRs 
1. add unit tests 
2. manually tested with 
* deploy, running smart function
* deposit/withdrawal
```
cargo run --bin jstz -- account create test
cargo run --bin jstz -- bridge deposit --from bootstrap1 --to test --amount 2 --network dev
cargo run --bin jstz -- account balance -a test --network dev
cargo run --bin jstz -- bridge withdraw --to …
```

refactor(jstz_proto): mirgrate to new_address

---

crates/jstz_api/src/lib.rs
crates/jstz_cli/src/jstz.rs
crates/jstz_cli/src/repl/debug_api/kv.rs
crates/jstz_node/src/services/accounts.rs
crates/jstz_proto/src/api/kv.rs
crates/jstz_proto/src/api/mod.rs
crates/jstz_proto/src/executor/smart_function.rs

preparation step for [271](https://linear.app/tezos/issue/JSTZ-271/use-smart-function-hash-for-new-account)
we need to move the kv api from jstz_api to jstz_proto since rust doesn't support cyclic dependencies
move the KvApi to `jstz_proto`, this way we could use the new address type in the Kv, which is set when jstz runtime apis are registered
manually tested kv on the cli to verify kv works 
```
─(15:51:17 on leounoki-jstz-271-2/move-kv ✹ ✭)──> jstz run tezos://tz1ayVniHHVwhhzZZC5PQxnaxMBQct8PV3U5/ --network dev --trace
Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.35s
warning: the following packages contain code that will be rejected by a future version of Rust: parse-display-derive v0.4.1
note: to see what the problems were, use the option `--future-incompat-report`, …
```

refactor(jstz_proto): move kv api

---

crates/jstzd/build.rs

Completes JSTZ-277.
[JSTZ-277](https://linear.app/tezos/issue/JSTZ-277/make-built-kernel-files-easily-accessible)
Part of [JSTZ-273](https://linear.app/tezos/issue/JSTZ-273/ship-jstzd-in-a-container).
Currently building the kernel wasm file into the installer file and preimages is part of the build process. These files are kept somewhere in the build environment, which is accessible through the environment variable `OUT_DIR` _only at build time_. Some pieces of code are generated and used by jstzd to find the kernel files. These pieces of code are then built into jstzd at compile time. In these pieces of code, the path known as `OUT_DIR` at build time is referenced as the directory that contains the kernel files. This becomes an issue when jstzd is launched outside the build environment …

feat(jstzd): set default import path for jstzd kernel files

---

crates/jstz_cli/src/account.rs
crates/jstz_cli/src/jstz.rs
crates/jstz_core/src/kv/transaction.rs
crates/jstz_proto/src/context/account.rs
crates/jstz_proto/src/context/new_account.rs

preparation step for [758](https://github.com/jstz-dev/jstz/pull/758) where new account is introduced
1. The validation check for the address type is removed as we intend to use the sf hash address directly in the following PRs.
2. the value for entry.or_insert_with doesn't need a `Default` trait
existing test pass

remove validation check for new address 

---

Cargo.lock
crates/jstz_crypto/Cargo.toml
crates/jstz_crypto/src/public_key.rs
crates/jstz_crypto/src/public_key_hash.rs
crates/jstz_crypto/src/secret_key.rs
crates/jstz_proto/Cargo.toml
crates/jstz_proto/src/operation.rs

Fixes an issue with json serialization  of `Content` printing the discriminator (`_type`) twice which causes problems when deserializing. 
This PR also identifies an issue with the binary encoding that is broken because `tezos_cryptos` cannot decode enums with `serde(untagged)`. This will be fixed in a follow up PR.
* Removes serde tag `_type` from operation struct types.
`cargo nextest run -p jstz_proto`

fix(operation): remove serde tag from operation variants

---

crates/octez/Cargo.toml
crates/octez/src/async/baker.rs
crates/octez/src/async/protocol.rs

Part of JSTZ-273.
[JSTZ-273](https://linear.app/tezos/issue/JSTZ-273/ship-jstzd-in-a-container)
Introduce one feature flag `disable-alpha` in the octez crate that hides the alpha protocol version. This is handy when the octez executables for alpha might not be available in an environment, e.g. when the base image of the jstzd image does not have alpha executables at all. This happens when the base image is tagged, e.g. `octez-v20.3`, `octez-v21.0`, including release candidates. The alpha executables are removed when those tagged images are built.
Also replaced Alpha with ParisC in some test cases just to avoid having to add the flag check.
Tested locally with a feature flag temporarily added to the jstzd crate:
```
[features]
build-image = ["octez/disable-alpha"]
```
The jstzd executable …

feat(octez): introduce feature 'disable-alpha'

---

crates/octez/Cargo.toml
crates/octez/src/async/rollup.rs

Part of JSTZ-273.
[JSTZ-273](https://linear.app/tezos/issue/JSTZ-273/ship-jstzd-in-a-container)
Introduce one feature flag `disable-slow-pvm` in the octez crate that adds one flag for the rollup node executable. This will force the rollup node not to raise any error or fall back to the slow PVM when it detects floating point operations in the kernel, which was enforced in octez-v21. A temporary solution that allows users to skip this behaviour by launching the rollup node with a new flag was implemented by the core team and was finalised in [90773bc](https://gitlab.com/tezos/tezos/-/commit/90773bcbea7ec941ea0f3e26cba742a0928e686e) after a few MRs. This PR simply adds that flag.
Note that this feature flag does not work with the current octez version (v21.0-rc2) referenced by nix, which is …

feat(octez): introduce feature 'disable-slow-pvm'

---

crates/jstz_crypto/src/smart_function_hash.rs
crates/jstz_kernel/src/parsing.rs
crates/jstz_node/openapi.json
crates/jstzd/build.rs

Since there's only one type of contract address on tezos, we don't need to use an enum.
* removed the enum from sfh
* renamed KT1 to `SmartFunctionHash`
existing tests work

Remove enum from smart function hash

---

crates/jstz_proto/src/context/new_account.rs
crates/jstz_proto/src/error.rs

first step of migrarting to a new account
[task link](https://linear.app/tezos/issue/JSTZ-257/introduce-new-account-type)
in preparation for [255](https://linear.app/tezos/issue/JSTZ-255/migrate-to-newaccount-type)
Added a new account context that handles address of both user and smart function. For a clearer api, we should use `SmartFunctionHash` for methods that's only intended for sf. This can be implemented after the migration to the new account type is completed. 
In the next step, the old account should be replaced with the new one.
Unit tests are added.

jstz proto: introduce new account

---

crates/jstz_core/src/bin_encodable.rs
crates/jstz_core/src/kv/mod.rs
crates/jstz_core/src/kv/outbox.rs
crates/jstz_core/src/kv/transaction.rs
crates/jstz_core/src/kv/value.rs
crates/jstz_core/src/lib.rs
crates/jstz_crypto/src/public_key_hash.rs
crates/jstz_kernel/src/inbox.rs
crates/jstz_kernel/src/lib.rs
crates/jstz_mock/src/host.rs
crates/jstz_node/src/services/accounts.rs
crates/jstz_node/src/services/operations.rs
crates/jstz_proto/src/executor/fa_deposit.rs
crates/jstz_proto/src/executor/fa_withdraw.rs
crates/jstz_proto/src/executor/smart_function.rs
crates/jstz_proto/src/operation.rs

This PRs switches the encoding library for value storage from `serde` to `bincode` which ensure binary serialization is independent of serde. This is important because serde manipulation on enums can break bincode, thus an encoding scheme independrnt of serde increases reliability.
* The main change is o embed encode as part of `Value` and replace `DeserializeOwned` with `bincode::Decode` in `Storage`.
* Changed anywhere using `bincode::serde` to strictly `bincode` to avoid serde-bincode complications
* Cleaned up some redundant serde tags
```
make build && make test-unit
```

feat(storage): use bincode for value storage

---

crates/jstz_proto/src/api/kv.rs

Bug:
Running the example/counter.js sf fails on the second time, resulitng in derserialization error (Serde(AnyNotSupported))
Cause:
`KvValue` currently relies on `#[bincode(with_serde)]` for deserializing the `serde_json::Value`. This forcese bincode to invokes `serde_json`'s `deserialize` method. For example, in serde_json, the `Number` type is deserialized using [deserialized_any](https://docs.rs/serde_json/latest/src/serde_json/number.rs.html#455) method. 
However the deserializer, provided by bincode decoder, doesn't support [deserializing "any" type](https://github.com/bincode-org/bincode/blob/0ab1f715ae824b84010f0d020a0ecd47227223e2/src/features/serde/de_owned.rs#L72), resulting in an error.
This PR fix this issue by manually implementing Decode/Encode method.
[Task …

Jstz proto: fix kv value serialization

---

crates/jstzd/Cargo.toml
crates/jstzd/Dockerfile

Closes JSTZ-278.
[JSTZ-278](https://linear.app/tezos/issue/JSTZ-278/create-docker-file-for-jstzd)
Create a dockerfile that builds jstzd as an image based on a designated octez image. One feature flag is added specifically for this docker build because
* jstzd in the image must not suffer from the slow PVM issue, which means the base image needs either the old version v20.3 or newer versions with the slow PVM fix
* jstzd in the image needs to have quebec support, which means the old version v20.3 is not suitable as the base image
and therefore we need to use a newer version as the base image. Since alpha is not yet stabilised, it's better that we don't allow users to use alpha at all, so this new feature flag includes `octez/disable-alpha`. The default protocol version used by jstzd will …

feat(jstzd): create dockerfile

---

crates/jstz_cli/src/config.rs
crates/jstzd/src/config.rs

Part of JSTZ-274.
[JSTZ-274](https://linear.app/tezos/issue/JSTZ-274/run-jstzd-with-jstz-sandbox-start)
Assign a constant port to jstz node. This is required for the container solution because for now the jstz node in jstzd is not configurable, which means there is no way to control the port assigned to jstz node beforehand and thus it's impossible to expose jstz node to jstz CLI in the host environment. Setting the port number to 8933 aligns with the old sandbox.
Also changed the port assigned to jstzd server from 55555 to 54321 because 55555 is a [secretly reserved port in MacOS](https://developer.apple.com/forums/thread/671197).
Launch jstzd locally to observe that the occupied ports have changed.

fix(jstzd): change ports assigned to jstz node and jstzd server

---

Cargo.lock
crates/jstz_cli/Cargo.toml
crates/jstz_cli/src/main.rs
crates/jstz_cli/src/sandbox/container.rs
crates/jstz_cli/src/sandbox/mod.rs

Completes JSTZ-274.
[JSTZ-274](https://linear.app/tezos/issue/JSTZ-274/run-jstzd-with-jstz-sandbox-start)
Enable users to run containerised jstzd with `jstz sandbox --container start`.
Users can choose to launch the sandbox running containerised jstzd with a newly introduced flag `--container`. All sandbox commands with this flag operates on the container.
* `jstz sandbox --container start`: launch a new container running a pre-defined image with jstzd inside. If the image does not exist, the program then tries to pull that from the repository. This command sets some default config values so that the CLI can interact with the octez node and the jstz node inside the container later on. Note that this command generates some temporary files. They are not going to be cleaned up by the CLI …

feat(cli): run containerised jstzd with 'sandbox start'

---

.github/actions/build-cli/action.yml
.github/workflows/cli-npm.yaml

Part of JSTZ-275.
[JSTZ-275](https://linear.app/tezos/issue/JSTZ-275/ship-cli-as-an-npm-package)
Add a new workflow for building the `jstz` CLI binary and uploading it to a release. This workflow will be triggered when a new tag is created. It builds the CLI based on the tagged commit and publishes the binaries to a release with that tag in this repo.
Tested uploading binaries to a test repo to avoid contaminating this one:
[release](https://github.com/huancheng-trili/test-cli/releases/tag/769%2Fmerge)
[workflow run](https://github.com/jstz-dev/jstz/actions/runs/12806216038)

ci: build and upload cli binary

---

.github/workflows/docker.yml

Closes JSTZ-279.
[JSTZ-279](https://linear.app/tezos/issue/JSTZ-279/add-jstzd-to-build-pipeline)
Add jstzd to the image build pipeline. Some additional changes:
* image tag `{{date 'YYYYMMDD'}}` changed to `{{ sha }}` because date is not really helpful when it comes to finding the source commit of an image
* `runs-on` changed to arm64 instances because `ubuntu-latest` can run out of memory easily for cross-compliation. Amd64 targets are also removed for now. Multiplatform will be handled later on with some more changes to the workflow.
[Test run](https://github.com/jstz-dev/jstz/actions/runs/12882838014)

ci: build jstzd image

---

crates/jstz_node/stainless.yml

Wrong indentation causing incorrect generations for log.  
This should fix `Account` resource having a `methods` and `subresources` field (https://github.com/jstz-dev/jstz-client/blob/main/src/resources/accounts/accounts.ts#L15)

fix(stainless): fix wrong indentation level for logs

---

.github/workflows/cli-npm.yaml

Part of JSTZ-275.
[JSTZ-275](https://linear.app/tezos/issue/JSTZ-275/ship-cli-as-an-npm-package)
Rename CLI binaries in releases.
* jstz_macos_arm64 -> jstz_darwin_arm64
* jstz_linux_amd64 -> jstz_linux_x64
This makes it easier to select binaries based on platform and architecture in node.js, which will be used by the npm package.
[Test build](https://github.com/huancheng-trili/test-cli/releases/tag/0.0.1)

ci: rename cli release binaries

---

packages/cli/main/install.js
packages/cli/main/package.json
packages/cli/main/run.mjs

Part of JSTZ-275.
[JSTZ-275](https://linear.app/tezos/issue/JSTZ-275/ship-cli-as-an-npm-package)
Create an NPM package for jstz CLI.
This package is usable but not in its complete shape. Ideally the package should have `optionalDependencies` that are used to install the actual CLI binary, but those smaller packages make testing a bit more complicated without publishing them to NPM, and publishing these packages needs some more careful planning, so for simplicity, this package uses a rather naive approach before the publish plan gets finalised. Lines about `BINARY_DISTRIBUTION_PACKAGE` are here in preparation for the optional dependencies. They have no effect at the moment.
What happens when a user runs `npm install -g @jstz-dev/cli` or `yarn global add @jstz-dev/cli` is that the package …

feat(cli): set up cli npm package

---

crates/jstz_cli/src/bridge/deposit.rs
crates/jstz_cli/src/config.rs
crates/jstz_cli/src/sandbox/container.rs
crates/jstz_cli/src/sandbox/daemon.rs

Part of JSTZ-274.
[JSTZ-274](https://linear.app/tezos/issue/JSTZ-274/run-jstzd-with-jstz-sandbox-start).
Since now jstzd can also run in a container, we need to identify such cases to use the fixed address for the bridge contract rather than using the alias. To achieve this, a flag `container` is added to the sandbox config. This flag is set only when the sandbox container is in use.
Tested this manually.

fix(cli): add `container` flag to sandbox config

---

crates/jstz_cli/src/sandbox/container.rs
crates/jstzd/src/config.rs
crates/octez/src/async/node.rs

Part of JSTZ-273.
[JSTZ-273](https://linear.app/tezos/issue/JSTZ-273/ship-jstzd-in-a-container)
Since for now jstzd lives in a container and interacts with the host environment, everything inside the container that is exposed to the host environment needs to sit at address 0.0.0.0 instead of 127.0.0.1 or localhost to ensure that traffic can be sent back to the host environment. For octez node specifically, one new flag `--allow-all-rpc` is required for 0.0.0.0.
Tested manually by calling `curl localhost:18730/chains/main/blocks/head` from the host environment. Block information was returned as expected.

fix(jstzd): replace localhost with 0.0.0.0

---

crates/jstz_proto/src/operation.rs
examples/dashboard/package.json
examples/dashboard/src/main.tsx
flake.nix
package-lock.json
packages/sdk/index.ts
packages/sdk/package.json
packages/sdk/tsconfig.json

This PR updates the jstz sdk to use the client lib.  Technically, users don't need to use the client sdk but it has some convenience features that might be cherry-picked into the generated client lib. 
Will review this in the next step as it is getting quite difficult to work across `jstz` and `jstz-client` repos with varying head branches.
* Updates jstz sdk to use published version jstz-client. Note that this is published to my personal scope for now until we move `@jstz-dev` to trilitech org
* Updates example dashboard
* The js_jstz build was initially failing because the dependency, `undici-types` was being pulled in with 2 none resolvable versions which was causing`ENOTCACHED` issues. The violating dependency versions were being brought in by `node` dependency where v18 (the one …

feat(client-lib): update client lib

---

.github/workflows/docker.yml

Part of JSTZ-286.
[JSTZ-286](https://linear.app/tezos/issue/JSTZ-286/build-multiplatform-images)
Set default octez tag for builds triggered by tag events. Normally when the workflow is triggered, an input value `octez-tag` is provided, but when the workflow is triggered by a tag event, there is no way of getting that value, so we need to set a default value. This value should be identical to the octez version that is used during development and testing, in our case, in nix, but currently the default value set in this PR is different from that nix version because the nix version does not work well and I don't have enough time figuring out how to update that for now.
Tested by temporarily setting the workflow input `octez-tag` to optional and triggered a run without any input value. The …

ci: set default octez tag for images

---

crates/jstzd/Dockerfile

Closes JSTZ-286.
[JSTZ-286](https://linear.app/tezos/issue/JSTZ-286/build-multiplatform-images)
Remove the job limit in building docker images for jstzd. The config value `--jobs` was set to prevent the system from using too much resource during cross-compilation, but now there is no need to do cross-compilation, this config value can be removed to speed up the build process.
N/A

fix(jstzd): remove job limit in docker build

---

Cargo.lock
Cargo.toml
crates/jstz_engine/Cargo.toml
crates/jstz_engine/src/context.rs
crates/jstz_engine/src/gc/mod.rs
crates/jstz_engine/src/gc/ptr.rs
crates/jstz_engine/src/gc/root.rs
crates/jstz_engine/src/realm.rs
crates/jstz_engine/src/script.rs

See `gc/root.rs` for context. 
See `gc/root.rs` for described solution. 
```
cargo nextest run -p jstz_engine
```

feat(jstz_engine): add support for rooting GC values

---

crates/jstz_engine/src/gc/root.rs

**Related Tasks**: [jstz-263](https://linear.app/tezos/issue/JSTZ-263/implement-prolong-for-common-types)
**Dependencies**: #680 
This PR simply implements `Prolong` for some Rust primitive / basic types. 
All changes are type-level changes 🤓

feat(jstz_engine): implement `Prolong` for common types

---

crates/jstz_cli/src/bridge/deposit.rs
crates/jstz_cli/src/bridge/withdraw.rs
crates/jstz_cli/src/config.rs
crates/jstz_cli/src/deploy.rs
crates/jstz_cli/src/jstz.rs
crates/jstz_cli/src/repl/debug_api/account.rs
crates/jstz_cli/src/run.rs
crates/jstz_cli/src/utils.rs
crates/jstz_kernel/src/inbox.rs
crates/jstz_kernel/src/lib.rs
crates/jstz_kernel/src/parsing.rs
crates/jstz_node/src/services/accounts.rs
crates/jstz_node/src/services/logs/db.rs
crates/jstz_node/src/services/logs/mod.rs
crates/jstz_proto/src/api/ledger.rs
crates/jstz_proto/src/api/smart_function.rs
crates/jstz_proto/src/context/account.rs
crates/jstz_proto/src/context/mod.rs
crates/jstz_proto/src/context/ticket_table.rs
crates/jstz_proto/src/executor/deposit.rs
crates/jstz_proto/src/executor/fa_deposit.rs
crates/jstz_proto/src/executor/fa_withdraw.rs
crates/jstz_proto/src/executor/mod.rs
crates/jstz_proto/src/executor/smart_function.rs
crates/jstz_proto/src/executor/withdraw.rs
crates/jstz_proto/src/operation.rs
crates/jstz_proto/src/receipt.rs

final step of migration to support KT1 address
[task link](https://linear.app/tezos/issue/JSTZ-253/rename-old-accountrs)
* rename the `new_account`, `NewAddress` back to `account` and `Address`
* avoid unnecessary clone inside jstz_proto
existing test works

NewAddress -> Address

---

crates/jstz_node/openapi.json
crates/jstz_node/src/services/accounts.rs
crates/jstz_node/stainless.yml

fix(jstz_node): rename client->jstz-client, add query param to openapi

---

crates/jstz_proto/src/executor/smart_function.rs

There is a bug in jstz protocol where the tx isn't properly committed nor rolled back due to the incorrect handling of the parsing of the response type. This will result in incorrect rollup state in case users deploy a smart function that doesn't return a correct `Response` type.
One example is that when we add [support](https://linear.app/tezos/issue/JSTZ-294/support-transfer-in-request) for transfer in request object, we need to ensure that the state updated by the transfer and execution of the smart functions is atomic. This bug will violates the atomicity if the smart function doesn't return a proper response type.
[issue link](https://linear.app/tezos/issue/JSTZ-297/fix-jstz-proto-not-handling-invalid-return-type)
Change Script.run so that it will match on the result of parsing of …

Jstz proto: handle tx properly in script run

---

crates/jstz_engine/src/context.rs
crates/jstz_engine/src/gc/ptr.rs
crates/jstz_engine/src/gc/root.rs
crates/jstz_engine/src/lib.rs
crates/jstz_engine/src/realm.rs
crates/jstz_engine/src/script.rs
crates/jstz_engine/src/value/conversions.rs
crates/jstz_engine/src/value/mod.rs

**Related Tasks**: [jstz-265](https://linear.app/tezos/issue/JSTZ-265/implement-jsvalue-skeleton)
**Dependencies**: #738 
This PR:
- Adds a `JsValue` wrapper type
- Adds some useful traits for obtaining (raw) handles (used by mozjs ffi functions as 'rooted pointers')
- Replaces uses of `JSVal` with `JsValue` 
PR either consists of tyoe definitions or refactors.
``` 
cargo nextest run -p jstz_engine
```

feat(jstz_engine): add type definition for `JsValue` wrapper

---

crates/jstz_cli/src/account.rs

Closes JSTZ-283.
[JSTZ-283](https://linear.app/tezos/issue/JSTZ-283/enter-passphrase-does-not-accept-empty-input)
Allow empty input when users are prompted to enter the passphrase when they create new accounts.
Tested manually by trying to create a new account locally:
```sh
$ ./jstz deploy index.js --name example --network dev
You are not logged in. Please type the account name that you want to log into or create as new: e
Account not found. Do you want to create it? yes
Enter the passphrase for the new account (or leave empty to generate a random one):        
Generated passphrase: pond elevator nation final menu cliff license boring donate badge side bullet
Logged in to account e with address tz1frMYLkuPzdkcthRv79qyvL6eBaR8KUKcA
```

fix(cli): allow empty input for passphrase

---

.config/nextest.toml
Cargo.lock
Cargo.toml
crates/jstz_engine/Cargo.toml
crates/jstz_engine/src/compartment.rs
crates/jstz_engine/src/context.rs
crates/jstz_engine/src/gc/ptr.rs
crates/jstz_engine/src/lib.rs
crates/jstz_engine/src/realm.rs
crates/jstz_engine/src/script.rs
crates/jstz_engine/src/value/conversions.rs
crates/jstz_engine/src/value/mod.rs
crates/jstz_engine/tests/ui/compartments_are_generative.rs
crates/jstz_engine/tests/ui/compartments_are_generative.stderr

**Related Tasks**: [jstz-298](https://linear.app/tezos/issue/JSTZ-298/fix-generative-of-lifetime-parameters-for-compartments) 
While playing around with unrooting this morning, Ryan and I observed the following bug -- namely the following snippet compiles:
```rust
// Initialize JS engine
let engine = JSEngine::init().unwrap();
let rt = Runtime::new(engine.handle());
let rt_cx1 = Runtime::new(engine.handle());
let cx1 = rt_cx1.new_realm().unwrap();
let rt_cx2 = Runtime::new(engine.handle());
let cx2 = rt_cx2.new_realm().unwrap();
// This line shouldn't compile
let foo = vec![cx1, cx2];
```
Morally speaking, each `new_realm` should allocate a 'generative' lifetime parameter -- this parameter is generative in the sense that no other lifetime should unify with it apart from itself. 
The fix …

fix(jstz_engine): introduce generative compartment `Id`s

---

crates/jstz_api/tests/wpt.rs
crates/jstz_api/tests/wptreport.json

Closes JSTZ-304.
[JSTZ-304](https://linear.app/tezos/issue/JSTZ-304/handle-utf-16-strings)
Handle JsStrings with utf-16 characters properly in the test runner. Some test cases involve utf-16 characters, and the implementation of `TryFromJs for String` does not handle those characters properly, specifically the method [`to_std_string`](https://docs.rs/boa_engine/0.19.0/src/boa_engine/value/conversions/try_from_js.rs.html#39-52), which leads to errors like
`could not convert JsString to Rust string: invalid utf-16: lone surrogate found`
and leaves the runner unable to handle some tests.
To fix this, we need to get `JsString` first and then do the proper conversion ourselves.
```
```
Test cases showed up for the test suite `encodeInto.any.js` and …

fix(wpt): handle utf-16 characters

---

.github/workflows/ci.yml

Completes JSTZ-310.
[JSTZ-310](https://linear.app/tezos/issue/JSTZ-310)
Upgrade codecov-action to v5 to fix the token issue. This ensures that contributions in the future don't run into this problem.
Before: this [test commit](https://github.com/jstz-dev/jstz/pull/815/commits/ac8f95404c9804dc2dc6772a907bb79fbde2e820) shows that it did not work with my forked repo.
After: codecov works in this PR

ci: update codecov action to v5

---

Cargo.lock
Cargo.toml
crates/jstz_engine/Cargo.toml
crates/jstz_engine/src/context.rs
crates/jstz_engine/src/gc/compartment.rs
crates/jstz_engine/src/gc/mod.rs
crates/jstz_engine/src/gc/ptr.rs
crates/jstz_engine/src/gc/root.rs
crates/jstz_engine/src/gc/trace.rs
crates/jstz_engine/src/lib.rs
crates/jstz_engine/src/realm.rs
crates/jstz_engine/src/script.rs
crates/jstz_engine/src/value/conversions.rs
crates/jstz_engine/src/value/mod.rs

This PR defines a macro `gcptr_wrapper` which defines a wrapper struct over a GC pointer with some phantom lifetime and compartment parameters.
- Move `compartment.rs` to `gc/` -- compartments are a gc concept
- Implement `gcptr_wrapper` macro and refactor existing code to make use of it. 
Refactoring -- existing tests should cover changes

refactor(jstz_engine): replace existing wrapper definitions with common `gcptr_wrapper` macro

---

examples/get-tez/index.ts

The sample application get-tez double counts how much it sends to an account. When a user requests tez, it adds 2 to the amount that they have requested.

fix(examples): fix double-count for get-tez example

---

examples/show-tez/src/index.ts

if you run the `show-tez` example and run the command `show` before sending any messages, you get a 404 error in the console. This change handles that error.
1. Start the sandbox.
2. Build and deploy the get-tez example
3. Build and run the show-tez example
4. Send the command `show`
The show-tez example should return the message "No messages yet." instead of a 404 error.

fix(examples): handle zero messages in show-tez example

---

docs/api/request.md

The docs page for the Request object refers to the Response object in error.

fix(docs): correct instance methods for Request object

---

crates/jstz_api/Cargo.toml
crates/jstz_api/tests/wpt.rs
nix/crates.nix

Skip wpt in CI in a different way so that test coverage for jstz_api can still be calculated properly.
I'm making some code changes to jstz_api in #808, but codecov complains that the test coverage is 0 even if I created a test for the changed lines. The problem lies in this `--exclude-from-test` flag. Since the goal is to prevent llvm-cov from running wpt, I replaced that flag with a feature flag in jstz_api that ignores wpt so that other tests in the crate can contribute to test coverage.
CI runs properly.
Test coverage indeed changed with the [test commit](https://app.codecov.io/github/jstz-dev/jstz/commit/4fc0af07209047e5e7afc5b650fffc8dde71d702/indirect-changes).

ci: skip wpt but keep test coverage for jstz_api

---

crates/jstz_engine/src/gc/ptr.rs
crates/jstz_engine/src/lib.rs
crates/jstz_engine/src/string/mod.rs
crates/jstz_engine/src/string/str.rs

**Related Tasks**: [jstz-214](https://linear.app/tezos/issue/JSTZ-214/implement-jsstring-and-jsstr)
**Dependencies**: #739 
Adds type definitions for `JsString` and `JsStr`. 
Additionally wraps most (if not all) functions that operate on strings.

feat(jstz_engine): implement `JsString` and `JsStr` wrappers

---

crates/jstz_api/src/lib.rs
crates/jstz_api/src/stream/queuing_strategy/size.rs
crates/jstz_api/src/todo.rs
crates/jstz_api/tests/wpt.rs
crates/jstz_api/tests/wptreport.json

Enable test suites for `CountQueuingStrategy` ([interface](https://streams.spec.whatwg.org/#countqueuingstrategy), [class](https://nodejs.org/docs/v22.13.1/api/globals.html#class-countqueuingstrategy)) and `ByteLengthQueuingStrategy` ([interface](https://streams.spec.whatwg.org/#bytelengthqueuingstrategy), [class](https://nodejs.org/docs/v22.13.1/api/globals.html#class-bytelengthqueuingstrategy)).
```sh
```

feat(wpt): enable tests for queuing strategies

---

crates/jstz_api/tests/wpt.rs
crates/jstz_api/tests/wptreport.json

Enable test suites for CompressionStream ([interface](https://compression.spec.whatwg.org/#compression-stream), [class](https://nodejs.org/docs/v22.13.1/api/webstreams.html#class-compressionstream)) and DecompressionStream ([interface](https://compression.spec.whatwg.org/#decompression-stream), [class](https://nodejs.org/docs/v22.13.1/api/webstreams.html#class-decompressionstream)).
```sh
```

feat(wpt): enable tests for de/compression stream

---

.github/workflows/cli-npm.yaml
crates/jstz_cli/src/jstz.rs
crates/jstz_engine/src/script.rs
crates/jstz_engine/src/value/conversions.rs
crates/jstzd/Dockerfile
crates/jstzd/tests/jstzd_test.rs
crates/jstzd/tests/main_test.rs
flake.lock
rust-toolchain.toml

Completes JSTZ-314.
[JSTZ-314](https://linear.app/tezos/issue/JSTZ-314/upgrade-rust-version-to-1820)
On the way to building jstz engine for riscv.
Bump Rust version to 1.82.0 in order to use the toolchain for `riscv64gc-unknown-linux-musl` ([ref](https://releases.rs/docs/1.82.0/#compiler)).
CI passes.

chore: bump Rust version to 1.82.0

---

crates/jstz_cli/src/bridge/withdraw.rs
crates/jstz_cli/src/main.rs
crates/jstz_cli/src/run.rs
crates/jstz_core/src/reveal_data.rs

[task link](https://linear.app/tezos/issue/JSTZ-301/add-transfer-cli)
* add support for transfer
```
Usage: jstz transfer [OPTIONS] <AMOUNT> <ADDRESS|ALIAS>
Arguments:
<AMOUNT>         The amount in XTZ to transfer
<ADDRESS|ALIAS>  
Options:
-g, --gas-limit <GAS_LIMIT>  The maximum amount of gas to be used [default: 550000]
-i, --include                Include response headers in the output
-n, --network <NETWORK>      Specifies the network from the config file, defaulting to the configured default network. Use `dev` for the local sandbox
```
* introduce `RunArgs` as the number of arguments were getting bigger and linting complaning
```
cargo run --bin jstz -- transfer 1 KT1AyfEg3c1ZkW4CATmzSoo5MiNkTP16qpb7 -n dev
Transferred 1 XTZ to KT1AyfEg3c1ZkW4CATmzSoo5MiNkTP16qpb7
cargo run --bin …
```

Jstz cli: transfer

---

Cargo.lock
Cargo.toml

Closes JSTZ-313.
[JSTZ-313](https://linear.app/tezos/issue/JSTZ-313/upgrade-tezos-version)
In preparation for #707.
Upgrades the rollup sdk so that jstz_engine can be built for target `riscv64gc-unknown-linux-musl`.
CI should continue to work.
To test building into riscv, spin up a container with this image:
`ghcr.io/huancheng-trili/cross-riscv64gc-unknown-linux-musl:5f9a19d`
```sh
docker run -it --rm --entrypoint bash ghcr.io/huancheng-trili/cross-riscv64gc-unknown-linux-musl:5f9a19d
git clone https://github.com/jstz-dev/jstz.git --branch huanchengchang-jstz-313
wget -O a.tar.gz https://github.com/huancheng-trili/test-mozjs/releases/download/mozjs-sys-v0.128.3-0/libmozjs-riscv64gc-unknown-linux-musl.tar.gz
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
. …
```

chore: update rollup sdk version

---

crates/jstz_api/tests/wpt.rs
crates/jstz_api/tests/wptreport.json

Enable test suites for crypto ([interface](https://w3c.github.io/webcrypto/#crypto-interface), [class](https://nodejs.org/docs/v22.13.1/api/crypto.html)).
```sh
```

feat(wpt): enable tests for crypto

---

crates/jstz_api/src/stream/queuing_strategy/mod.rs
crates/jstz_api/src/stream/readable/mod.rs
crates/jstz_api/tests/wpt.rs
crates/jstz_api/tests/wptreport.json

Enable test suites for ReadableByteStreamController ([interface](https://streams.spec.whatwg.org/#readablebytestreamcontroller), [class](https://nodejs.org/docs/v22.14.0/api/webstreams.html#class-readablebytestreamcontroller)).
```sh
```

feat(wpt): enable tests for readable byte streams

---

crates/jstz_api/tests/wpt.rs
crates/jstz_api/tests/wptreport.json

Enable test suites for URL ([interface](https://url.spec.whatwg.org/#url), [class](https://nodejs.org/docs/v22.14.0/api/url.html#class-url)) and URLSearchParams ([interface](https://url.spec.whatwg.org/#urlsearchparams), [class](https://nodejs.org/docs/v22.14.0/api/url.html#class-urlsearchparams)).
```sh
```

feat(wpt): enable tests for url and url search params

---

crates/jstz_api/tests/wpt.rs
crates/jstz_api/tests/wptreport.json

Enable test suites for Response ([interface](https://fetch.spec.whatwg.org/#response), [class](https://nodejs.org/docs/v22.14.0/api/globals.html#response)).
```sh
```

feat(wpt): enable tests for response

---

crates/jstz_proto/src/api/smart_function.rs
crates/jstz_proto/src/executor/smart_function.rs

[related link](https://linear.app/tezos/issue/JSTZ-329/handle-response-refund-for-user-account)
This is a part of [supporting transfer in request](https://linear.app/tezos/issue/JSTZ-295/support-transfer-in-resopnse)
This PR enables smart function to refund the user (only in the top most level). 
cargo test -p jstz_proto

feat(proto): add refund for user in response

---

crates/jstz_crypto/src/smart_function_hash.rs

Part of JSTZ-338.
[JSTZ-338](https://linear.app/tezos/issue/JSTZ-338/jstz-account-alias-panics-when-address-is-too-short)
Check the length of input strings in `from_base58` to avoid panics.
This bug leads to something like this:
```
$ jstz account alias a b                      
thread 'main' panicked at crates/jstz_crypto/src/smart_function_hash.rs:60:20:
byte index 3 is out of bounds of b
```
Updated the corresponding unit test.

fix(crypto): check length of smart function addresses

---

crates/jstz_crypto/src/error.rs

Completes JSTZ-338.
[JSTZ-338](https://linear.app/tezos/issue/JSTZ-338/jstz-account-alias-panics-when-address-is-too-short)
Make the error message of `InvalidSmartFunctionHash` look "less cheap".
Before:
```
$ ./jstz account alias a b          
error: invalid value 'b' for '<KT1 ADDRESS>': InvalidSmartFunctionHash
```
After:
```
./jstz account alias a b    
error: invalid value 'b' for '<KT1 ADDRESS>': invalid smart function hash
```
Other lines are updated due to formatting.
Added one unit test.

feat(crypto): improve error message of InvalidSmartFunctionHash

---

crates/jstz_api/tests/wpt.rs
crates/jstz_api/tests/wptreport.json

Enable test suites for atob/btoa ([interface](https://html.spec.whatwg.org/multipage/webappapis.html#dom-atob), [class](https://nodejs.org/docs/v22.14.0/api/globals.html#atobdata)).
```sh
```

feat(wpt): enable tests for atob/btoa

---

.prettierignore
.rustfmt.toml
Makefile
flake.nix

Following #837, the pre-commit hook fails (since `fa2.js` is not formatted). 
There are two issues here:
1. The configured ignore `crates/jstz_tps_bench/fa2.js` should be `.prettierignore` instead of the global ignores (for treefmt)
2. The `make fmt` targets don't use Nix
This PR updates `make fmt` and `make fmt-check` to use `nix fmt`. 
Additionally it moves the ignore for `crates/jstz_tps_bench/fa2.js` to `.prettierignore` 
(and a comment instructing that future changes should be made in `.rustfmt.toml`/`.prettierignore`
for language-specific ignores)
Test your pre-commit hook works by committing something :)

chore: use `nix fmt` for fmt and fmt-check targets in Makefile

---

.cargo/config.toml
Cargo.lock
Cargo.toml
Makefile
crates/jstz_runtime/Cargo.toml
crates/jstz_runtime/README.md
crates/jstz_runtime/src/main.rs
flake.nix
nix/crates.nix
nix/rust-toolchain.nix
nix/v8.nix

Add support for Deno in Jstz and cross compilation to `riscv64gc-unknown-linux-musl`.
As part of this work, the [rusty_v8 repo was forked](https://github.com/jstz-dev/rusty_v8/tree/130.0.7) and archive uploaded there.
The basics of registering a new op and executing a script are added to `main.rs`
A couple of TODOs are to bring in the patches made to `rusty_v8` into the forked repo and automate the riscv release, but these can be done later
* Adds  `jstz_runtime` crate
* Fetches v8 riscv archive in nix  and adds `make riscv-runtime`
`make riscv-runtime`
`cargo run -p jstz_deno_engine`

feat(jstz_engine): support deno

---

crates/jstz_api/tests/wpt.rs
crates/jstz_api/tests/wptreport.json

Enable test suites for set/clear interval and timeout functions ([interface](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#timers), [implementation](https://nodejs.org/docs/v22.14.0/api/timers.html#scheduling-timers)).
```sh
```

feat(wpt): enable tests for interval and timeout functions

---

crates/jstz_api/tests/wpt.rs
crates/jstz_api/tests/wptreport.json

Enable test suites for ReadableStream ([interface](https://streams.spec.whatwg.org/#readablestream), [class](https://nodejs.org/docs/v22.14.0/api/webstreams.html#class-readablestream)).
```sh
```

feat(wpt): enable tests for readable stream

---

.github/workflows/cli-npm.yaml

Completes JSTZ-345.
[JSTZ-345](https://linear.app/tezos/issue/JSTZ-345/build-static-cli-binary-for-x86-64)
Build CLI for `x86_64-unknown-linux-musl` in order to get static x64 cli binaries.
I tried to use `pkgsMusl` in nix, but nix tried to rebuild a whole bunch of irrelevant packages for musl, which took hours, and in the end there were some error in those in irrelevant packages, and again mozjs does not have a prebuilt for `x86_64-unknown-linux-musl`, so I'm building this as how it's done for aarch64-linux.
[Test workflow run](https://github.com/jstz-dev/jstz/actions/runs/13699721004/job/38310216001)
Also tested the built binary in a clean x64 environment.

ci: build static x64 cli binary

---

crates/jstz_api/tests/wpt.rs
crates/jstz_api/tests/wptreport.json

Enable test suites for WritableStream ([interface](https://streams.spec.whatwg.org/#writablestream), [class](https://nodejs.org/docs/v22.14.0/api/webstreams.html#class-writablestream)).
```sh
```

feat(wpt): enable tests for writable stream

---

flake.nix

When entering the nix shell, I get the following error:
```
direnv: loading ~/clients/trilitech/jstz/jstz/.envrc                                                                                                
direnv: using flake -j auto
warning: ignoring untrusted substituter 'https://trilitech-jstz.cachix.org', you are not a trusted user.
Run `man nix.conf` for more information on the `substituters` configuration option.
error:
… while calling the 'derivationStrict' builtin
at /builtin/derivation.nix:9:12: (source not available)
… while evaluating derivation 'nix-shell'
whose name attribute is located at /nix/store/jk6xpbfh10gz6q5cqw8b2f7xk0pl7hkv-source/pkgs/stdenv/generic/make-derivation.nix:375:7
… while evaluating attribute 'RISCV_V8_ARCHIVE_DIR' of derivation 'nix-shell'
at …
```

fix(nix): fix hash incompatability between CI (linux) and local (MacOS)

---

Cargo.lock
crates/jstz_core/src/host.rs
crates/jstz_proto/Cargo.toml
crates/jstz_runtime/Cargo.toml
crates/jstz_runtime/src/lib.rs
crates/jstz_runtime/src/runtime.rs

Adds `JstzRuntime`, the top level struct that will manage the `JsRuntime` state. 
This PR sets up for the implementation of runtime APIs. Check out https://github.com/jstz-dev/jstz/pull/863, https://github.com/jstz-dev/jstz/pull/868/filesfor an example.
*  For `JstzRuntime` to interact with protocol state, we pre-seed the initialization with a `Protocol` that allows us to expose instances of `HostRuntime` and `Transaction` to extension logic. 
* ~`deno_core` exposes the ability to take snapshots of the running instance which we can use to quickly create isolated, sandboxed environments for each Smart Function evaluation but I couldn't got that to work yet 😞 ~ Removed snapshot function
* Currently, `JstzRuntime` can only execute plain, non ECMAScript module Javascript. Supporting default …

feat(runtime): add JstzRuntime

---

crates/jstz_api/tests/wpt.rs
crates/jstz_api/tests/wptreport.json

Enable test suites for FormData ([interface](https://xhr.spec.whatwg.org/#formdata), [class](https://nodejs.org/docs/v22.14.0/api/globals.html#class-formdata)).
```sh
```

feat(wpt): enable tests for FormData

---

crates/jstz_api/tests/wpt.rs
crates/jstz_api/tests/wptreport.json

Completes JSTZ-303.
Enable test suites for TransformStream ([interface](https://streams.spec.whatwg.org/#transformstream), [class](https://nodejs.org/docs/v22.14.0/api/webstreams.html#class-transformstream)).
```sh
```

feat(wpt): enable tests for transform stream

---

.github/workflows/ci.yml
crates/jstz_tps_bench/src/kernel/main.rs
flake.nix
nix/crates.nix

Part of JSTZ-31.
[JSTZ-31](https://linear.app/tezos/issue/JSTZ-31)
Runs benchmarking as part of each build. If a build is for a PR, benchmarking will be run against the base branch as well for comparison. If benchmarking does not work in the base branch, it will be skipped. Of course it's possible to cache the result somewhere so that we don't need to run it for the base branch every time, but since it requires setting up a database and nix cache should help avoid building the base branch from scratch, I think it's okay to leave it like this. This result display can be further extended to something like attaching a comment to a PR so that people are easily aware of changes that lead to performance regression.
`jstz_bench` in flake.nix looks a bit awkward because of how the benchmark …

ci: benchmark after build

---

Cargo.lock
Cargo.toml
crates/jstz_core/Cargo.toml
crates/jstz_core/src/error.rs
crates/jstz_core/src/lib.rs
crates/jstz_core/src/reveal_data.rs

Part of [adding support for large smart function](https://linear.app/tezos/project/large-smart-function-deployment-e1f8c66e4e03/overview)
[task url](https://linear.app/tezos/issue/JSTZ-358/implement-reveal-data)
Added `RevealData` struct that introduces apis to
1. reveal data greater than 4KB via the reveal data channel.
2. help encode the data and chunk them into preimages of size 4KB. 
The max size of data supported is now 10MB.
Added uni tests:
```
cargo test --package jstz_core   
```

feat(jstz_core): implement reveal data

---

crates/jstz_cli/src/deploy.rs
crates/jstz_cli/src/run.rs
crates/jstz_mock/src/lib.rs
crates/jstz_node/openapi.json
crates/jstz_proto/src/executor/mod.rs
crates/jstz_proto/src/operation.rs
crates/jstz_tps_bench/src/bench/generate.rs

**Related Issues**: [Operations can be signed with any key pair](https://linear.app/tezos/issue/JSTZ-396/operations-can-be-signed-with-any-key-pair) 
This PR fixes the security vuln described in the linear issue. 
This PR removes `source` from `Operation`, adding `public_key` in its place. 
Additionally, we can now remove `public_key` from `SignedOperation`. 
This means `public_key` is the single source of truth (in the protocol) about the signer's identity. 
Which was the issue that led to the vuln. 
This PR additionally adds some tests around `Operation::verify_nonce` and `SignedOperation::verify`
```
cargo nextest run -p jstz_proto
```

fix(proto): remove `Operation.source` and fix `Operation::verify_nonce`

---

crates/jstz_kernel/src/lib.rs
crates/jstz_node/openapi.json
crates/jstz_proto/src/error.rs
crates/jstz_proto/src/executor/mod.rs
crates/jstz_proto/src/operation.rs

Part of [large sf deployment](https://linear.app/tezos/project/large-smart-function-deployment-e1f8c66e4e03/issues)
[task link](https://linear.app/tezos/issue/JSTZ-360/support-reveallargepayloadoperation)
* add a new operation `RevealLargePayLoadOperation` 
* refactored and modified the `execute_external_operation` to handle the `RevealLargePayLoadOperation` 
add unit test 
```
cargo test -p jstz_proto
```

feat(jstz_proto): add reveal large payload op

---

.github/workflows/ci.yml

Completes JSTZ-339.
[JSTZ-339](https://linear.app/tezos/issue/JSTZ-339/run-web-platform-tests-as-part-of-ci)
Runs wpt as part of CI.
I decided not to add wpt as a nix flake package because
* it's troublesome.
* adding wpt means the submodule needs to be pulled into the source as well, and wpt is a huge code repository, meaning a non-trivial increase in the amount of data cached / size of derivation.
* running wpt in parallel means we can save some time for each CI run.
Note:
* Using a rust base image is much simpler than using a python base image because there is no need to set up CC and relevant libraries for rust with a rust base image.
* Soft-linking `python3.11` to `python3` is necessary because our wpt runner looks for `python3`.
* wpt has some problem with python 3.12 and above, so …

ci: run wpt

---

Cargo.lock
Cargo.toml
crates/jstz_cli/Cargo.toml
crates/jstz_cli/src/bridge/deposit.rs
crates/jstz_cli/src/config.rs
crates/jstz_cli/src/sandbox/consts.rs
crates/jstz_cli/src/sandbox/jstzd.rs

Part of JSTZ-355.
[JSTZ-355](https://linear.app/tezos/issue/JSTZ-355/replace-all-localhost-with-127001)
Replace references to `localhost` in CLI with `127.0.0.1`.
Also refactored a bit to make things more testable.
Tested running the sandbox locally both in the host environment and in a container.

fix(cli): replace localhost with 127.0.0.1

---

Cargo.lock
crates/jstz_runtime/Cargo.toml
crates/jstz_runtime/src/error.rs
crates/jstz_runtime/src/lib.rs
crates/jstz_runtime/src/runtime.rs
crates/jstz_runtime/tests/wpt.rs

**Related Tasks**: [Implement module loading](https://linear.app/tezos/issue/JSTZ-374/implement-module-loading) 
We need to be able to load ES modules. Why? Smart functions are ES modules. 
**Dependencies**: #862, #870 
This PR adds support for module loaders to `JstzRuntime`. Additionally it adds all the functions required for loading, evaluating and calling the default handler.
For now, we do not support passing arguments to the default handler.
```sh
cargo nextest run -p jstz_engine
```

feat(runtime): add support for module loaders

---

Cargo.lock
Cargo.toml
crates/jstz_cli/Cargo.toml
crates/jstz_cli/src/account.rs

Part of JSTZ-403.
[JSTZ-403](https://linear.app/tezos/issue/JSTZ-403/passphrases-and-tz1-generation-are-different-to-umami-and-octez-cli)
The version of `tiny-bip39` in this repo is out of date and `tiny-bip39` itself lacks some features. Replacing it with `bip39` allows us to do more things easily. It seems that there used to be some issues with `bip39` and `tiny-bip39` was created as a fork to address those issues. It's been a while since `tiny-bip39` was created and added to this repo and I assume that now `bip39` is fine with the upgrades.
* Manual testing: CLI still works
* Unit testing: added one test to monitor bip39 API

chore(deps): replace tiny-bip39 with bip39

---

.github/workflows/ci.yml
crates/jstz_runtime/tests/wpt.rs

Completes JSTZ-333.
[JSTZ-333](https://linear.app/tezos/issue/JSTZ-332/collect-test-metrics)
The test runner now dumps test stats as a markdown file to a specified destination when the environment variable `STATS_PATH` is present. This file is picked up in the CI workflow and displayed in the run summary.
[Test summary](https://github.com/jstz-dev/jstz/actions/runs/14105298959/attempts/1#summary-39510379280)

feat(wpt): display metrics

---

flake.nix

Brings `riscv-sandbox` into our nix environment for testing Jstz using the RISCV PVM supervisor
* Uses pkgs.rustPlatform.buildRustPackage to fetch and build the `sandbox` workspace member of the `tezos/tezos` riscv project
* `useFetchCargoVendor` is set to true to ensure dependencies are vendored for the CI environment
`riscv-sandbox --help`

feat(nix): add support for riscv sandbox

---

flake.nix

Fixes the issues with `riscv-sandbox` not building with supervisor feature
`nm $(which riscv-sandbox) | grep linux` should not be empty

fix(riscv-sandbox): properly enable supervisor build

---

docs/functions/overview.md
docs/functions/requests.md

We got some user feedback with questions about the context that Jstz runs in and whether smart functions have access to the global context.
Stress that smart functions run in a separate context every time and must store data in the KV store.

fix(docs): clarification on globals and single entrypoint

---

crates/jstz_cli/src/bridge/withdraw.rs

Completes JSTZ-399.
[JSTZ-399](https://linear.app/tezos/issue/JSTZ-399/make-sure-that-cli-config-works-when-users-switch-between-native-and)
Normally, when it comes to layer 1 operations, CLI always calls octez-client to perform them. This does not work with the containerised sandbox because it's a bit troublesome keeping track of the octez base directory that contains necessary data, so a container flag in the sandbox config was created and CLI goes through the exposed jstzd endpoint to tell octez client in the container to perform such operations. This gets a bit messy and difficult to maintain.
The `withdraw` command uses octez-client to resolve layer 1 address aliases, which has the same issue.
Make the withdraw command resolve layer 1 address aliases through jstzd when users run it …

fix(cli): resolve l1 aliases through jstzd

---

crates/jstz_cli/src/bridge/deposit.rs
crates/jstz_cli/src/bridge/withdraw.rs
crates/jstz_cli/src/deploy.rs
crates/jstz_cli/src/sandbox/jstzd.rs
crates/jstz_cli/src/sandbox/mod.rs

Part of JSTZ-421.
[JSTZ-421](https://linear.app/tezos/issue/JSTZ-421/clean-up-sandbox-config)
Sandbox config is not really necessary after jstzd is integrated into CLI.
Make CLI check sandbox status through jstzd instead of by checking the sandbox config. Since jstzd server always listens on port 54321, it's sufficient to check if the sandbox is running properly through the health check endpoint.
* Manual testing: tested the sandbox locally
* Unit testing: added some test cases for the new helper function.

refactor(cli): check sandbox status through jstzd

---

crates/jstz_tps_bench/Cargo.toml

`jstz_tps_bench` not compiling due to missing import
Add utils feature to kernel sdk dependency

fix(cargo): enable utils feature in jstz_tps_bench

---

Cargo.lock
crates/jstz_runtime/Cargo.toml

Patch `deno_fetch` with our `deno_fetch` fork - https://github.com/jstz-dev/deno/tree/ryan/patch-deno-fetch . The fork exposes `deno_fetch_base` crates which exposes the fetch ops as traits that we can implement in our code going forward.  
The set of changes made by the fork can be found at https://github.com/jstz-dev/deno/pull/1 
Closes: [JSTZ-419](https://linear.app/tezos/issue/JSTZ-419/fork-deno-fetch), [JSTZ-420](https://linear.app/tezos/issue/JSTZ-420/removetraitify-non-compliant-functionality-from-deno-fetch)
Dangerous and non-blockchain compliant features from `deno_fetch` need to be removed or traitfied. This allows us to alter the behaviour of fetch dependning no the environment that we're running in (blockchain sandbox and wpt). Isolating changes allows to potentially upstream …

feat(runtime): patch deno_fetch with jstz fork

---

Cargo.lock
crates/jstz_cli/Cargo.toml
crates/jstz_cli/src/config.rs
crates/jstz_cli/tests/config.rs

Completes JSTZ-461.
[JSTZ-461](https://linear.app/tezos/issue/JSTZ-461/support-xdg-compatibility)
Closes #892.
Support `XDG_CONFIG_HOME` for config. Following the [guideline](https://specifications.freedesktop.org/basedir-spec/latest/#variables),
* when `XDG_CONFIG_HOME` is set, the path to the config file is `$XDG_CONFIG_HOME/config.json`.
* when `XDG_CONFIG_HOME` is not set, the path to the config file is changed to `$HOME/.config/jstz/config.json`.
Configuring config directory with `JSTZ_HOME` is replaced by `XDG_CONFIG_HOME`.
* Integration test: added one test

feat(cli): support XDG_CONFIG_HOME for config

---

docs/functions/requests.md

You can get the query params from a request; mention this in the doc about requests.

feat(doc): document query params

---

crates/jstz_api/tests/wpt.rs
crates/jstz_runtime/tests/wpt.rs

Part of JSTZ-437.
[JSTZ-437](https://linear.app/tezos/issue/JSTZ-437/calculate-pass-rate-against-deno-test-set)
Deno runs a specific subset of the entire WPT test suites. We want to run the same subset for jstz.
Update wpt to [e78446e](https://github.com/web-platform-tests/wpt/tree/e78446e34a1921371658a5df08c71d83f50a2a2f). This is the version pinned by deno at the time v2.1.10 was released.
Note that the lines for comparing WPT results are removed from the test runners. Since the number of tests will grow quite a bit, I don't think it makes much sense to check in large files with rather limited information. We'll figure out how to track changes later on.
WPT job should still run normally.

chore(wpt): update wpt

---

Cargo.lock
crates/jstz_runtime/tests/test_harness_api.js
crates/jstz_wpt/Cargo.toml
crates/jstz_wpt/src/lib.rs
crates/jstz_wpt/src/serve.rs

Part of JSTZ-437.
[JSTZ-437](https://linear.app/tezos/issue/JSTZ-437/calculate-pass-rate-against-deno-test-set)
Deno runs a specific subset of the entire WPT test suites. We want to run the same subset for jstz.
Correctly set the constraint on subset tests in order to compare the test results with deno's report. The original `?0-5` constraint tells the runner to access the first 5 test cases in each subset test that might contain hundreds of test cases. Deno does not put such a constraint on their runner and we need to remove it if we want to compare our test coverage against their results. However, deno does run subset tests in batches. This uncovers an issue in the way we pack test scripts. Since WPT is designed for a web environment, it expects the runner to be able to handle URL query …

fix(wpt): properly set location.search for subset tests

---

Cargo.lock
crates/jstz_kernel/src/lib.rs
crates/jstz_mock/src/host.rs
crates/jstz_proto/src/error.rs
crates/jstz_proto/src/executor/mod.rs
crates/jstz_tps_bench/src/kernel/main.rs
crates/jstzd/build.rs
crates/jstzd/build_config.rs

[task link](https://linear.app/tezos/issue/JSTZ-363/add-authentication)
* Add auth to the protocol to check that reveal large payload comes from `bootstrap1` 
* created a task to organize protocol constants in one place. Will leave it for now as we only have ticketer and injector .
add unit test.
```
cargo test -p jstz_proto
```

Add auth for proto

---

.github/actions/build-cli/action.yml
.github/actions/test-cli/action.yml
.github/workflows/cli-npm.yaml

Completes JSTZ-356.
[JSTZ-356](https://linear.app/tezos/issue/JSTZ-356/test-cli-happy-path-with-different-machines)
Test the built CLI binaries to be released as part of the release pipeline. The test is basically running a few simple commands in a clean environment to make sure that the binaries are statically linked and do not need additional libraries.
The pipeline is updated from
```
build mac         -> upload to release
build linux x64   -> upload to release
build linux arm64 -> upload to release
```
to
```
build mac         ─> test in mac          ─┐
build linux x64   ─> test in linux x64    ─┼─> upload all binaries to release
build linux arm64 ─> test in linux arm64  ─┘
```
[Test build](https://github.com/jstz-dev/jstz/actions/runs/14449726946)
[Uploaded …

chore(ci): test CLI happy path with different machines

---

Cargo.lock
crates/jstz_runtime/.gitignore
crates/jstz_runtime/Cargo.toml
crates/jstz_runtime/tests/wpt.rs

Completes JSTZ-437.
[JSTZ-437](https://linear.app/tezos/issue/JSTZ-437/calculate-pass-rate-against-deno-test-set)
Deno runs a specific subset of the entire WPT test suites. We want to run the same subset for jstz and compare the results.
Extract stats from deno's WPT report and calculate our pass rate accordingly.
A deno report looks like this:
```
{
"results": [
{"test": "/WebCryptoAPI/algorithm-discards-context.https.window.html", "subtests": [...], "status": ... },
{...}
]
}
```
where each entry in `results` is the report of a test suite. We can extract the number of test cases in each test suite by inspecting its status and subtests. Based on the status and other information of a subtest, we know which test cases work with deno. Therefore, after iterating through the entire report, we …

feat(wpt): calculate pass rate against deno test set

---

Cargo.lock
crates/jstz_cli/src/account.rs
crates/jstz_crypto/Cargo.toml
crates/jstz_crypto/src/lib.rs
crates/jstz_tps_bench/Cargo.toml
crates/jstz_tps_bench/src/bench/generate.rs

Part of JSTZ-484.
[JSTZ-484](https://linear.app/tezos/issue/JSTZ-484/update-account-creation)
In jstz, the term `passphrase` has always been what is referred to as mnemonic in other tools like octez-client and L1 wallets. This is misleading and the way CLI derives keys from passphrases is also problematic.
Replace `keypair_from_passphrase` with `keypair_from_mnemonic` to align key derivation with octez-client.
Added unit tests.

fix(crypto): remove keypair_from_passphrase

---

crates/jstz_node/openapi.json
crates/jstz_node/src/services/operations.rs
crates/jstz_proto/src/executor/mod.rs
crates/jstz_proto/src/operation.rs

[link](https://linear.app/tezos/issue/JSTZ-458/store-recipt-in-the-original-hash)
Before this fix, when handling RLP operation in the protocol, the protocol used  the RLP operation hash. it should be linked to the orignal operation hash instead as RLP operation is an `intermediate opertion`
* Extended the RLP operation to include the hash of the original operation
* Modified the protocol to use the orginal operation hash instead of the RLP hash
add unit test.
```
cargo test -p jstz_proto
```

Fix Operation hash for large payload operation

---

.github/workflows/ci.yml
.github/workflows/test-nightly.yml

WPT and benchmark are two jobs that are part of CI now. They take quite a bit of time, especially WPT because its results are not cached.
Create a new workflow that runs WPT and benchmark nightly instead of for every PR push. The original discussion was only about moving WPT, but I think it makes sense to move benchmark as well.
The new workflow will also be able to be triggered manually.
N/A

ci: set up nightly tests

---

crates/jstzd/Cargo.toml
crates/octez/Cargo.toml
crates/octez/src/async/rollup.rs

`disable-slow-pvm` was created when the old octez version whose rollup node did not have the flag was still in use by nix. Now we no longer need it.
Removing this feature.
Everything should still build.

chore(octez): remove disable-slow-pvm

---

crates/jstz_crypto/src/smart_function_hash.rs
crates/jstz_kernel/src/parsing.rs
crates/jstz_node/openapi.json
crates/jstz_proto/src/executor/fa_withdraw.rs
crates/jstz_proto/src/executor/smart_function.rs
crates/jstzd/build.rs

Removes outbox message ID to avoid confusion among end users. 
Outbox message id field was intended to be used by users to track their bridge withdrawal. However, completing this feature requires a  lot more work that we cannot prioritize right now. So instead of allowing this to linger, we remove it and set the withdrawal request fields as part of its receipt.
Closes: [JSTZ-489](https://linear.app/tezos/issue/JSTZ-489/remove-outbox-message-id-temporarily)
* Remove outbox message id
* Add Fa withdraw request fields into the receipt
* Regenerate the new open api doc
* ticketer and proxy l1 contract were converted into smart function hash because it needs encoding and openapi derivations. This change should be safe since Jstz uses the same hashing scheme for contracts
* Added newtype …

chore(proto): remove outbox messasge id

---

Makefile
crates/jstz_node/openapi.json
crates/jstz_proto/src/api/smart_function.rs
crates/jstz_proto/src/context/account.rs
crates/jstz_proto/src/executor/deposit.rs
crates/jstz_proto/src/executor/fa_deposit.rs
crates/jstz_proto/src/executor/fa_withdraw.rs
crates/jstz_proto/src/js_logger.rs
crates/jstz_proto/src/operation.rs
crates/jstz_proto/src/receipt.rs
crates/jstz_tps_bench/src/kernel/main.rs

Since we target a primarily JS/TS audience, generated code should use camel case. Additionally, its [generally good practice](https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format) to use camel case properties in API services
Closes: https://linear.app/tezos/issue/JSTZ-488/use-camelcase-for-json
Annotated structs that affect the open api generation with `#[serde(rename_all = "camelCase")]`
Corresponding stainless changes - https://github.com/jstz-dev/jstz-client/commit/8e1a71486a6b0ef41c5ed736d17c9e2394f9454a#diff-25fd7ba932755790a659d8dfcf1c25b9d628e7b642e9087dfd55af137db086e6

chore(proto): use camelCase in json

---

crates/jstz_node/openapi.json
crates/jstz_proto/src/api/kv.rs

Kv values can be `any` type
Closes https://linear.app/tezos/issue/JSTZ-315/jstzclientgetkv-should-return-anyunknown-instead-of-string 
* Change `value_type` of `KvValue` to `Value` which generates a schema with `any` type according to `utoipa` docs. The change gets reflects as `unknown` in generated client code which enforces narrowing to a more specific type 
Client changes - https://github.com/jstz-dev/jstz-client/commit/74424af176240c2539cd6900f7d57a10d92dc9d3#diff-6115f1e5afaba23f2a3d1a208e6662475a463d79bb53df12c7c7f2bd6ddc848aR41

chore(openapi): update kv value type to any

---

crates/jstz_node/openapi.json
crates/jstz_proto/src/operation.rs
crates/jstz_proto/src/receipt.rs

We want to make it easy for dapps to attach transfers to run/deploy functions and read these values from responses
Closes https://linear.app/tezos/issue/JSTZ-457/allow-setting-transfer-headers-in-client-sdk 
* Includes transfer headers in request and response headers of open api schema
Generated client- https://github.com/jstz-dev/jstz-client/commit/527c7dcd0a4bf45b6a77229824bff9fc2dbf2b5a#diff-25fd7ba932755790a659d8dfcf1c25b9d628e7b642e9087dfd55af137db086e6

chore(openapi): support settings transfer in sdk

---

crates/jstz_cli/src/account.rs
crates/jstz_crypto/src/lib.rs
crates/jstz_tps_bench/src/bench/generate.rs

Part of JSTZ-485.
[JSTZ-485](https://linear.app/tezos/issue/JSTZ-485/import-jstz-accounts-with-secret-keys-in-cli)
Get key pairs from secret key strings. Essentially,
```
"edsk..." --> (PublicKey, SecretKey)
```
Added one unit test.

feat(crypto): get key pairs from secret keys

---

crates/jstz_cli/src/main.rs
docs/cli.md

release chore
fix the run cli arg. simply renamed from "request" to "method"
```
cargo run --bin jstz -- run jstz://KT1RoV8imUNX6xMYiX3YTrzHZifqS4N1yU7A/ --method POST --network dev --trace
```

Replace "request" with "method" in CLI

---

.github/workflows/docker.yml
crates/jstzd/Dockerfile

Part of the release chores.
Update the default tag of the octez base image used by the jstzd image to `octez-v22.0`.
N/A

chore(ci): update octez base image

---

docs/.vitepress/config.mjs
docs/functions/building.md
docs/functions/deploying.md
docs/functions/overview.md

We had an internal user hear that Jstz runs your TS code without having to build it so they tried to deploy a smart function without building it with the Jstz dependencies. 
Make it clear that you have to build smart functions with the Jstz dependencies before deploying them.
This PR also adds instructions for deploying smart functions to the sandbox; are we ready to provide instructions for deploying to any other network?

feat(docs): building and deploying topics

---

crates/jstz_cli/src/deploy.rs
crates/jstz_cli/src/main.rs
crates/jstz_cli/tests/deploy.rs

Completes JSTZ-498.
Closes #926.
[JSTZ-498](https://linear.app/tezos/issue/JSTZ-498/jstz-deploy-name-needs-a-f-argument)
Add one flag `--force` to `jstz deploy` to overwrite known smart functions. Example:
```
$ jstz deploy index.js --name foo
...
Smart function deployed by test_user at address: KT1...
Run with `jstz run jstz://KT1.../`
$ jstz deploy index.js --name foo
✕  ERROR  The smart function name 'foo' already exists. Please choose another name or specify the `--force` flag to overwrite the name.
$ jstz deploy index.js --name foo --force
...
Smart function deployed by test_user at address: KT1...
Run with `jstz run jstz://KT1.../`
```
Added one integration test.

feat(cli): overwrite smart function name

---

Cargo.lock
Cargo.toml
crates/jstz_cli/src/sandbox/mod.rs
crates/jstz_node/openapi.json
packages/cli/main/package.json

Bump version to 0.1.1-alpha.1 for the next release
* Bump version in workspace `Cargo.toml`
* Bump version in `packages/cli/main/package.json`
* Bump version of `SANDBOX_IMAGE` in `crates/jstz_cli/src/sandbox/mod.rs`
* Regenerate openapi schema - `cargo run --bin jstz-node -- spec -o crates/jstz_node/openapi.json`

chore(release): bump version to 0.1.1-alpha.1

---

.github/actions/test-cli/action.yml

CLI release check [failed](https://github.com/jstz-dev/jstz/actions/runs/14640353127/job/41081511102) because `jstz account create` is now aligned with the other account creation flow where users are asked to input a passphrase and the library we use for user prompts does not work properly in certain cases.
Keep `jstz account list` in the check and remove other lines. It should be fine as the main idea of the check was to ensure that the binaries are packaged properly.
I find it surprising that the prompt library does not even accept pipes. We should probably replace that library since it means CLI cannot be used in automation.
[Test run](https://github.com/jstz-dev/jstz/actions/runs/14641309059/job/41084238779)

fix(ci): remove cli checks that require input

---

crates/jstz_cli/src/run.rs
crates/jstz_cli/tests/account.rs
crates/jstz_cli/tests/deploy.rs
crates/jstz_cli/tests/exec.rs
crates/jstz_cli/tests/utils.rs
crates/jstz_proto/src/api/smart_function.rs
crates/jstz_proto/src/error.rs
crates/jstz_proto/src/executor/mod.rs

Jstz supports `jstz://` scheme in its URL but this has never been validated which is a bug. This PR fixes that.
* Validate jstz scheme in cli, `RunFunction` operation and in `SmartFunction.call`
* Add `ProcessSession` to cli test utils to reduce friction
```
cargo nextest run -p jstz_proto invalid_scheme
cargo nextest run -p jstz_cli invalid_scheme --test
```

fix(cli, proto): validate jstz scheme in run function

---

docs/quick_start.md

Completes JSTZ-508.
Fixes #904.
[JSTZ-508](https://linear.app/tezos/issue/JSTZ-508/fix-invisible-text-in-docs)
Remove the inline style for code blocks. Setting the foreground colour to #FFF makes the text invisible in light mode.
Before:
After:

fix(docs): fix invisible text

---

.github/workflows/deploy-dev-docs.yml

Completes JSTZ-503.
[JSTZ-503](https://linear.app/tezos/issue/JSTZ-503/create-staging-environment-for-docs)
Currently every commit in the main branch triggers a doc build and the docs are deployed directly to https://jstz-dev.github.io/jstz/. This means that changes not yet released are immediately reflected in the pages, which can be confusing for users.
Push dev docs to a different repo and deploy them there.
This requires
- a target repo, tbd but named as `dev-docs` in this PR, with github pages configured to be built from the root of the repo.
- a github API token with write access to the repo's content and github pages. The token needs to be added to runner secrets, currently named as `DEV_DOC_REPO_TOKEN`.
[Test workflow run](https://github.com/jstz-dev/jstz/actions/runs/14637809073) …

ci: deploy dev docs elsewhere

---

.github/workflows/deploy-dev-docs.yml

Fixes #973.
A [build](https://github.com/jstz-dev/jstz/actions/runs/14730155797/job/41342204433) failed because the script could not move the built doc files when the destination folders were not empty.
Remove folders in `dev-docs` so that the new built doc files can be moved to the target repo.
[Test run](https://github.com/jstz-dev/jstz/actions/runs/14731992946/job/41348342036)

fix(ci): move built dev docs properly

---

.github/workflows/deploy-docs.yml

Completes JSTZ-509.
[JSTZ-509](https://linear.app/tezos/issue/JSTZ-509/deploy-docs-on-release)
Deploy docs to prod on release. This workflow can also be triggered manually with any commit ref. The rules are:
* If a ref is given to the workflow (manual run,) the ref is used to deploy the pages.
* If no ref is given to the workflow (manual run,) `main` is used to deploy the pages.
* If the workflow is triggered by a tag, the tag is used to deploy the pages.
Note that to allow tags to trigger this workflow, this repo setting needs to be updated:
`Environments` -> `github-pages` -> `Deployment branches and tags` -> Add tag rule "*"
Tested with my fork.
[Tag in the main branch](https://github.com/huancheng-trili/jstz/actions/runs/14704612789)
[Workflow …

ci: deploy prod docs on release

---

flake.nix

Completes JSTZ-372.
[JSTZ-372](https://linear.app/tezos/issue/JSTZ-372/remove-warn-no-formatter-logs-from-nix-fmt)
Make `nix fmt` ignore files without formatters. Note that toml files can actually be formatted with `toml-sort`, but it kind of messes up `Cargo.toml` files, even if it does sort dependencies.
```
$ nix --accept-flake-config -L --extra-experimental-features nix-command --extra-experimental-features flakes fmt
treefmt.toml> 
2025/05/01 11:35:39 INFO using config file: /nix/store/dpl77vgzks5r8jcbp46rczxs5ybw55y2-treefmt.toml
traversed 520 files                                                                
emitted 407 files for processing                                                   
formatted 1 files (0 changed) in 55ms
```
No more warnings.

chore(nix): make fmt ignore unsupported files

---

crates/octez/resources/protocol_parameters/sandbox/ProtoALphaALphaALphaALphaALphaALphaALphaALphaDdp3zK
crates/octez/resources/protocol_parameters/sandbox/PsQuebecnLByd3JwTiGadoG4nGWi3HYiLXUjkibeFV8dCFeVMUg
crates/octez/resources/protocol_parameters/sandbox/PsRiotumaAMotcRoDWW1bysEhQy2n1M5fy8JgRp8jjRfHGmfeA7
crates/octez/src/node.rs

Jstzd has 1 second block times and 8 second ttl which means forged operations have at most 8 seconds to be injected and applied. This window is too small for injecting operations from web wallets where usually a manual sign approval is required between forge and inject.
Web wallets require access to octez rpc to work correctly.
1. Increase `max_operations_time_to_live` to 60 in protocol parameter
2. Add `--cors-origin=*` arg to octez node run
Only config changes so existing test should pass. Test coverage reports nill unfortunately.
`make test` 
Tested manually by Bohdan

fix(octez): increase operation ttl to to blocks (1m) and allow any origin on cors

---

crates/jstz_kernel/src/lib.rs
crates/jstz_proto/src/api/smart_function.rs
crates/jstz_proto/src/executor/fa_deposit.rs
crates/jstz_proto/src/executor/smart_function.rs

`Script` is a runtime specific concept. Yet the `deploy` function doesn't rely on any runtime specific functions. 
This PR simply splits `deploy` from `Script` (and removes some redundant logic from `SmartFunction.create`)
Exiting tests should cover this refactor

refactor(proto): rm `Script::deploy`, replace with `smart_function::deploy`

---

scripts/execute_latest_outbox_message.sh

Realised that the helper script needs to be updated while trying out withdrawals.
Made the `execute_latest_outbox_message` helper script usable with jstzd. Also updated the script overall with a linter.
Tested the script with a local sandbox.
Shellcheck gives no warning.

fix: use execute_latest_outbox_message with jstzd

---

Cargo.lock
Cargo.toml
crates/jstz_utils/Cargo.toml
crates/jstz_utils/src/lib.rs
crates/jstzd/Cargo.toml
crates/jstzd/src/task/utils.rs
crates/jstzd/tests/octez_client_test.rs

Part of JSTZ-544.
[JSTZ-544](https://linear.app/tezos/issue/JSTZ-544/create-sequencer-mode)
In preparation for #990.
Created a new crate `jstz_utils` that covers helper functions used across crates. For now only `poll` is moved to this crate because it's needed soon. The new crate is named `jstz_utils` instead of simply `utils` because each crate possibly has its own `utils` module and dealing with the naming conflict is a bit annoying.
CI passes.

refactor: create jstz_utils

---

crates/jstz_cli/src/repl/debug_api/account.rs
crates/jstz_node/src/services/operations.rs
crates/jstz_proto/src/api/smart_function.rs
crates/jstz_proto/src/context/account.rs
crates/jstz_proto/src/executor/smart_function.rs

This PR merges the logic between `SmartFunction::call` and `smart_function::run::execute` (in theory they should do the same thing anyway). 
**Dependencies**: #948 
This PR is split into two commits. 
The first commit handles the merging of the logic between `SmartFunction::call` and `smart_function::run::execute`. In some places, I discovered inconsistencies around how transfers were handled. This was discussed offline and the conclusion was that if a transfer fails, then it should revert the callee's transaction and return `Response.error()`. 
The second commit updates all the tests affected by the change of semantics in transfers. 
```
cargo nextest run -p jstz_proto
```

refactor(proto): merge logic between `SmartFunction::call` and `smart_function::run::execute`

---

Cargo.lock
crates/jstz_node/Cargo.toml
crates/jstz_node/src/config.rs
crates/jstz_node/src/lib.rs
crates/jstz_node/src/main.rs
crates/jstz_node/src/services/mod.rs
crates/jstz_node/src/services/utils.rs
crates/jstz_node/tests/sequencer.rs
crates/jstzd/src/config.rs
crates/jstzd/src/task/jstzd.rs
crates/jstzd/tests/jstz_node_test.rs
crates/jstzd/tests/jstzd_test.rs

Completes JSTZ-544.
[JSTZ-544](https://linear.app/tezos/issue/JSTZ-544/create-sequencer-mode)
Added an enum `RunMode` to jstz node. This enum indicates the mode that jstz node will run in. `Default` means running jstz node as is and `Sequencer` means the sequencer behaviour will be activated. This mode is determined by the CLI argument `--mode` which defaults to `default`.
Also added one API route `GET /mode` which returns the node's mode for testing.
* Integration testing: added one test

feat(jstz_node): create sequencer mode

---

crates/jstz_node/src/lib.rs
crates/jstz_node/src/sequencer/mod.rs
crates/jstz_node/src/sequencer/queue.rs

Part of JSTZ-546.
[JSTZ-546](https://linear.app/tezos/issue/JSTZ-546/set-up-operation-queue)
When a signed operation to be injected arrives at the sequencer, the operation should be placed in a queue and wait to be processed.
Implemented a basic queue that carries `SignedOperations`.

feat(sequencer): implement basic queue

---

crates/jstz_node/src/config.rs
crates/jstz_node/src/lib.rs
crates/jstz_node/src/main.rs
crates/jstzd/src/config.rs
crates/jstzd/src/task/jstzd.rs
crates/jstzd/tests/jstz_node_test.rs
crates/jstzd/tests/jstzd_test.rs

Part of JSTZ-546.
[JSTZ-546](https://linear.app/tezos/issue/JSTZ-546/set-up-operation-queue)
When a signed operation to be injected arrives at the sequencer, the operation should be placed in a queue and wait to be processed.
Added a queue to jstz node and made its capacity configurable.
Also created a struct `RunOptions` that collects all values passed into `run` because the linter complained about that method having too many arguments.
Existing tests should pass. This is trivial so I'm leaving the actual tests to #993.

feat(sequencer): add queue to node

---

Cargo.lock
Cargo.toml
crates/jstz_node/Cargo.toml
crates/jstz_node/src/sequencer/queue.rs
crates/jstz_node/src/services/error.rs
crates/jstz_node/src/services/operations.rs

Part of JSTZ-546.
[JSTZ-546](https://linear.app/tezos/issue/JSTZ-546/set-up-operation-queue)
When a signed operation to be injected arrives at the sequencer, the operation should be placed in a queue and wait to be processed. If the queue still has space, the response code would be 200 as usual. If the queue is full, the response code would be 503.
Made the sequencer insert incoming signed operations into the queue.
* Unit testing: added tests for both the new error and the API handler.

feat(sequencer): insert operations to queue

---

crates/jstz_node/src/lib.rs
crates/jstz_node/src/sequencer/mod.rs
crates/jstz_node/src/sequencer/worker.rs

Part of JSTZ-551.
[JSTZ-551](https://linear.app/tezos/issue/JSTZ-551/create-worker)
Created a skeleton of the worker. The worker only gets created in the sequencer and runs in a separate thread and does its job periodically.
* Unit testing: added test cases

feat(sequencer): implement worker skeleton

---

crates/jstz_node/src/lib.rs
crates/jstz_node/src/sequencer/mod.rs
crates/jstz_node/src/sequencer/queue.rs
crates/jstz_node/src/sequencer/worker.rs

Part of JSTZ-551.
[JSTZ-551](https://linear.app/tezos/issue/JSTZ-551/create-worker)
Made the worker read from the operation queue. For now it does nothing to the operations because the runtime is not yet set up.
Also moved `dummy_op` to the sequencer module level so that it can be shared across test modules.
* Unit testing: added test cases

feat(sequencer): make worker read from queue

---

Cargo.lock
Cargo.toml
crates/jstz_runtime/src/ext/jstz_console/console.js
crates/jstz_runtime/src/ext/jstz_console/mod.rs
crates/jstz_runtime/src/runtime.rs

[task ilnk](https://linear.app/tezos/issue/JSTZ-357/remove-colours-from-console)
Disabled color in console. 
The relevant changes are made to deno [here](https://github.com/jstz-dev/deno/pull/4)
cargo test --package jstz_runtime

Disable console color

---

crates/jstz_cli/src/logs/trace.rs
crates/jstz_node/src/services/logs/mod.rs
crates/jstz_proto/src/lib.rs
crates/jstz_proto/src/runtime/mod.rs
crates/jstz_proto/src/runtime/v1/js_logger.rs
crates/jstz_proto/src/runtime/v1/mod.rs
crates/jstz_proto/src/runtime/v1/script.rs

Since we need to support both boa and v8 in the interim, the code depending to each runtime should be factored out to allow as much re-use of runtime independent code as possible
Part of https://linear.app/tezos/issue/JSTZ-495/move-boa-runtime-to-v1-in-jstz-proto
Depends on https://github.com/jstz-dev/jstz/pull/1007
Moves js logger into `runtime::v1`
`make build && make test`

JSTZ-495-3: Move js logger to v1

---

crates/jstz_proto/src/executor/smart_function/deploy.rs
crates/jstz_proto/src/executor/smart_function/host.rs
crates/jstz_proto/src/executor/smart_function/mod.rs
crates/jstz_proto/src/executor/smart_function/run.rs
crates/jstz_proto/src/runtime/mod.rs
crates/jstz_proto/src/runtime/v1/fetch_handler.rs
crates/jstz_proto/src/runtime/v1/host_script.rs
crates/jstz_proto/src/runtime/v1/js_logger.rs
crates/jstz_proto/src/runtime/v1/mod.rs

Since we need to support both boa and v8 in the interim, the code depending to each runtime should be factored out to allow as much re-use of runtime independent code as possible
Part of https://linear.app/tezos/issue/JSTZ-495/move-boa-runtime-to-v1-in-jstz-proto
Depends on https://github.com/jstz-dev/jstz/pull/1002
Moves `host_script.rs` and `run_top_level_fetch` to v1
`make build && make test`

JSTZ-495-4: move host_script and top level fetch to v1

---

crates/jstz_node/Cargo.toml
crates/jstz_node/src/sequencer/db.rs
crates/jstz_node/src/sequencer/mod.rs
nix/crates.nix

Part of JSTZ-575.
[JSTZ-575](https://linear.app/tezos/issue/JSTZ-575/implement-host)
A new host is needed for the sequencer, at least when the runtime is going to run natively. This host stores data in a data store accessible from the exterior.
Implemented a sqlite wrapper for the new host and some basic methods that perform queries required by the host. Using a sqlite db should be fine for jstz because fortunately jstz only uses some host methods that do not really depend on the tree-based WASM rollup data store.
Some additional helper functions like `exec_read` are implemented to make reusing connections, e.g. for transactions, easier.

feat(sequencer): implement runtime db

---

crates/jstz_node/src/lib.rs
crates/jstz_node/src/sequencer/db.rs
crates/jstz_node/src/services/operations.rs
crates/jstz_node/src/services/utils.rs

Part of JSTZ-576.
[JSTZ-576](https://linear.app/tezos/issue/JSTZ-576/use-boa-runtime)
The sequencer needs a runtime to execute incoming operations.
Updated the receipt API handler in jstz node such that it reads receipts from the runtime db when it runs in sequencer mode. A new entry `runtime_db` is added to jstz node's app state. The API handler reads receipts from that database and returns the results to users. For now `runtime_db` uses a temporary file as the database file for simplicity. Later on this will be made configurable.
Integration tests will be added in other PRs.

feat(sequencer): get receipts from store

---

Cargo.lock
Cargo.toml
crates/jstz_cli/src/repl/debug_api/account.rs
crates/jstz_core/Cargo.toml
crates/jstz_core/src/error.rs
crates/jstz_core/src/kv/transaction.rs
crates/jstz_core/src/kv/value.rs
crates/jstz_proto/src/context/account.rs
crates/jstz_proto/src/context/ticket_table.rs
crates/jstz_proto/src/operation.rs
crates/jstz_proto/src/runtime/v1/api/kv.rs
crates/jstz_proto/src/runtime/v1/fetch_handler.rs
crates/jstz_proto/src/runtime/v2/fetch.rs
crates/jstz_runtime/src/ext/jstz_kv/kv.rs
crates/jstz_runtime/src/lib.rs
crates/jstz_runtime/tests/wpt.rs
flake.nix

[JSTZ-610](https://linear.app/tezos/issue/JSTZ-610/implement-guarded-for-implicit-locking)
In order to avoid having to lock/unlock transaction object once we use Arc<Mutex<...>> for sharing it across threads, this PR implements Guarded and GuardedMut. Guarded replaces references returned by Transaction and contains a reference counter of the guard and a pointer to a value from the Transaction object. We can use deref or deref_mut, to get references to the value within an unsafe block, whose safety is guaranteed since the lock stays alive while Guarded is alive. Lock gets dropped automatically, when all Guarded/GuardedMut get dropped. Additionally Transaction is modified to be a wrapper for sharing Arc<Mutex<Inner>> with Inner being the actual implementation. It also holds a non-owning …

feat(core): implicit locking

---

crates/jstz_node/src/services/accounts.rs
crates/jstz_node/src/services/operations.rs
crates/jstz_node/src/services/utils.rs

Part of JSTZ-601.
[JSTZ-601](https://linear.app/tezos/issue/JSTZ-601/expose-runtime-db-with-jstz-node-api)
Jstz node API needs to return data from runtime db when jstz node runs in sequencer mode.
Updated the handler of `/accounts/<address>` such that it returns data from the runtime db when jstz node runs in sequencer mode.

feat(sequencer): read account from db

---

Cargo.lock
Cargo.toml
crates/jstz_kernel/src/inbox.rs
crates/jstz_node/Cargo.toml
crates/jstz_node/src/lib.rs
crates/jstz_node/src/sequencer/inbox.rs
crates/jstz_node/src/sequencer/mod.rs
crates/jstz_node/tests/sequencer.rs

[task link](https://linear.app/tezos/issue/JSTZ-589/monitor-blocks)
Part of processing the inbox messages, we need a way to monitor blocks first
* implement `Monitor` that listenens to the L1 box via the rollup node rpc
* added `warp` to mock the http streaming for testing
* added mock rpc server to the sequencer test to return dummy value
NOTE: added unit tests for the monitor instead of the jstz node server, in the future if more logic is added we can add integration test for the jstz node server but this should be enough for now. 
cargo test -p jstz_node
manually ran jstzd with a sequencer mode and you will be able to see the block number being printed to the console

feat(sequencer): implement inbox monitor

---

crates/jstz_core/src/kv/transaction.rs
crates/jstz_proto/src/runtime/v2/fetch.rs
crates/jstz_runtime/src/ext/jstz_kv/mod.rs
crates/jstz_runtime/src/lib.rs
crates/jstz_runtime/src/runtime.rs
crates/jstz_runtime/tests/wpt.rs

[JSTZ-375](https://linear.app/tezos/issue/JSTZ-375/replace-andmut-transaction-with-arcmutextransaction)
This PR remove static lifetime from transaction, which is now possible as the Transaction was moved within Arc<Mutex<Inner>>.
```make```

feat(core): remove static lifetime from transactions

---

docs/architecture/accounts.md
docs/cli.md
docs/quick_start.md
examples/call-from-web/README.md
examples/show-tez/src/index.ts

Completes JSTZ-586.
[JSTZ-586](https://linear.app/tezos/issue/JSTZ-586/replace-jstz-in-docs)
Closes #1008.
Replaced all references to `~/.jstz` with `~/.config/jstz` as the home directory for jstz has been updated. Should have been done in #923.
N/A

fix(docs): replace ~/.jstz

---

crates/jstz_node/src/sequencer/db.rs
crates/jstz_node/src/sequencer/host.rs

Part of JSTZ-601.
[JSTZ-601](https://linear.app/tezos/issue/JSTZ-601/expose-runtime-db-with-jstz-node-api)
Jstz node API needs to return data from runtime db when jstz node runs in sequencer mode.
Implemented one method `get_subkeys` to return subkeys from the runtime database and fixed the method `count_subkeys`.
I missed out some details in the previous implementation and realised that the query needs to be more complicated. For instance, for query key `/a`,
|key|should select|output|
|---|---|---|
|`/a`|Y|`""`|
|`/a/b`|Y|`"b"`|
|`/ab`|N|-
|`/b/a`|N|-
|`/a/c/d`|Y|`"c"`|
assuming that keys never have a trailing slash (not allowed in a host setup.) This means the query should select
* the target key itself
* keys with the target key as their prefix with one additional level
* keys with …

feat(sequencer): get subkeys

---

.github/workflows/deploy-dev-docs.yml

Unlike Vitepress, Docusaurus does not create new builds when documentation is not updated. This failed the pipeline when it tried to push dev docs for commits that did not involve changes in docs.
Updated the `build-dev-docs` workflow such that it skips pushing to the dev docs repo when docs are untouched.
[Test run](https://github.com/jstz-dev/jstz/actions/runs/15532072101/job/43723073515)

fix(ci): skip pushing dev docs when docs are not updated

---

crates/jstz_node/src/lib.rs
crates/jstz_node/src/sequencer/inbox/api.rs
crates/jstz_node/src/sequencer/inbox/mod.rs
crates/jstz_node/src/sequencer/queue.rs
crates/jstz_node/src/sequencer/runtime.rs
crates/jstz_node/tests/sequencer.rs

[task link](https://linear.app/tezos/issue/JSTZ-632/push-inbox-messages-push-into-the-queue)
Part of processing the inbox messages
Next step: handling [deposit](https://linear.app/tezos/issue/JSTZ-637/handle-deposit-operation) 
* add logic to fetch the inbox of the block from the rollup node
* add logic to push the inbox ops into the queues 
* add integration test to check if the operations in the inbox is being pushed into the q
NOTE: in case of failure, the fetch of the block and the push into the queue will be retired indefinitely.  
```
cargo test --package jstz_node --test sequencer -- run_sequencer --exact --show-output
```

feat(sequencer): push inbox msgs into the queue

---

docs/sandbox.md

I just thought this could use some clarification so people didn't wonder why their accounts didn't have any tez at the start.

fix(docs): clarify bootstrap accounts and Jstz accounts

---

Cargo.lock
crates/jstz_core/src/runtime.rs
crates/jstz_kernel/src/inbox.rs
crates/jstz_kernel/src/lib.rs
crates/jstz_node/Cargo.toml
crates/jstz_node/src/sequencer/inbox/parsing.rs
crates/jstz_node/src/sequencer/runtime.rs
crates/jstz_proto/src/executor/mod.rs
crates/jstz_proto/src/operation.rs
crates/jstz_proto/src/runtime/v1/mod.rs

Required for async kernel. 
Reduce review burden by only refactoring `executor::execute_operation` and its dependencies only
* Make proto `executor::execute_operation` async
* The second commit fixes a bug with async resolve value that doesn't get properly hooked into the local pool
1. `make build && make test` 
2. `make build-jstzd-kernel && cargo build -p jstzd` then deploy the following smart function
```
const handler = async (req) => {
return new Response("ok")
}
export default handler;
```
finally deploy and run the smart function

refactor(proto): asynchronify executor::execute_operation

---

crates/jstz_node/src/sequencer/inbox/mod.rs
crates/jstz_node/src/sequencer/inbox/parsing.rs
crates/jstz_node/src/sequencer/mod.rs
crates/jstz_node/src/sequencer/queue.rs
crates/jstz_node/src/sequencer/runtime.rs
crates/jstz_node/src/sequencer/worker.rs
crates/jstz_node/src/services/operations.rs
crates/jstz_node/tests/sequencer.rs
crates/jstz_proto/src/operation.rs

[task link](https://linear.app/tezos/issue/JSTZ-640/fa-deposit)
part of the processing inbox msgs. For now we only add support for native deposit as there is an issue with async runtime (fa deposit is async)
add support for native deposit operation. 
* make the queue take `Message` instead of `SignedOperation`. `Message` includes both External operations and Internal operations
* make the Internal operation clonable
* add unit test and integration test
cargo test --package jstz_node

feat(sequencer): support native deposit

---

Cargo.lock
Makefile
crates/jstz_api/src/http/response.rs
crates/jstz_kernel/Cargo.toml
crates/jstz_kernel/src/lib.rs
crates/jstz_node/src/sequencer/runtime.rs
crates/jstz_node/src/sequencer/worker.rs
crates/jstz_proto/src/context/account.rs
crates/jstz_proto/src/error.rs
crates/jstz_proto/src/executor/fa_deposit.rs
crates/jstz_proto/src/executor/mod.rs
crates/jstz_proto/src/executor/smart_function/run.rs
crates/jstz_proto/src/operation.rs
crates/jstz_proto/src/runtime/mod.rs
crates/jstz_proto/src/runtime/v1/fetch_handler.rs
crates/jstz_proto/src/runtime/v2/fetch/fetch_handler.rs
crates/jstz_proto/src/runtime/v2/fetch/http.rs
crates/jstz_proto/src/runtime/v2/fetch/mod.rs
crates/jstz_proto/src/runtime/v2/mod.rs
crates/jstz_runtime/src/runtime.rs
crates/jstz_runtime/src/sys/interfaces/request.rs
crates/jstz_runtime/src/sys/interfaces/response.rs
crates/jstz_utils/src/lib.rs

Part of https://linear.app/tezos/issue/JSTZ-599/integrate-v2-fetch 
Closes https://linear.app/tezos/issue/JSTZ-650/add-run-toplevel-fetch 
Add  `run_toplevel_fetch` for v2 runtime
* Removed execute_v2 and related code
* Wraps `process_and_dispatch_request` with `run_toplevel_fetch`
* Extends proto error with `V2Error`
* Add`make test-v2` to run with "v2_runtime" enabled
* V1 - Changed `Response.error` to have status code 400 instead of 500 
* V1 - Introduced `internal_server_error` for internal errors in V1
* Fixed up tests
* Ignore withdrawal tests for v2 as HostScript not yet implemented
* Ignore test that tests strictness of header hygiene for v2 as v2 fetch cleans bad headers instead of failing
* Ignore noop fetch tests for v2 as it is not yet implemented
* Adds tokio runtime to …

feat(proto): add v2 run_toplevel_fetch

---

crates/jstz_node/src/sequencer/runtime.rs
crates/jstz_node/src/sequencer/worker.rs

Part of: [task link](https://linear.app/tezos/issue/JSTZ-636/make-worker-spawn-async-aware)
The PR refactors the worker and initialize the tokio runtime before spawning the worker thread.
* make `runtime::process_message` into async
*  initialization the runtime outside of the worker thread, early return in case it fails
existing test works

refactor(sequencer): build runtime outside of the worker thread

---

crates/jstz_proto/src/runtime/v2/fetch/fetch_handler.rs
crates/jstz_runtime/Cargo.toml
crates/jstz_runtime/src/ext/jstz_console/mod.rs
crates/jstz_runtime/src/lib.rs
crates/jstz_runtime/src/runtime.rs
crates/jstz_runtime/tests/wpt.rs

Part of JSTZ-647.
[JSTZ-647](https://linear.app/tezos/issue/JSTZ-647/log-operation-details-for-v2-runtime)
V2 runtime has no logging basically.
Updated the console extension for v2 runtime such that log lines are printed in a specific format recognised by the log collector in jstz node. A sample line looks as follows:
```
[JSTZ:SMART_FUNCTION:LOG] {"address":"KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton","requestId":"js_types","level":"INFO","text":"false\n"}
```
This is the same as what is implemented for v1 runtime.
Note that since this format is only required when the runtime is built into the kernel, a new feature flag `kernel` is added such that `console` still writes messages in the old format in normal cases, e.g. with repl. That is,
```
[INFO] something
```
* Unit testing: updated tests
I …

feat(runtime): write console messages in logging format

---

crates/jstz_node/src/lib.rs
crates/jstz_runtime/src/ext/jstz_main/01_errors.js
crates/jstz_runtime/src/ext/jstz_main/98_global_scope.js
crates/jstz_runtime/src/ext/jstz_main/mod.rs

Random and timers will subbed in RISCV but we'd like them stub in native execution too.
Stub `Date.now` and  `Math.random` with constant values and make set/clear timeout/interval throw `NotSupported` error
Date is particularly difficult to stub because it has 5 constructors and since it is a built in types, its internals are completely opaque. My implementation tries to hide as much of the prototype chain as possible without re-writing the entire class but a motivated attacker would still be able to quite easily access it and call its functions. 
This solution temporary and exists while we are in native execution mode. RISCV solves this in kernel space, so I think its ok. 
`cargo nextest  run -p jstz_runtime jstz_main`

fix: stub random and timers

---

crates/jstz_node/src/lib.rs
crates/jstz_node/src/sequencer/worker.rs
crates/jstz_node/src/services/utils.rs
crates/jstz_node/tests/sequencer.rs

Completes JSTZ-663.
[JSTZ-663](https://linear.app/tezos/issue/JSTZ-663/expose-worker-heartbeat)
Since the worker runs in a separate thread, it is possible that the worker somehow panics and fails silently while the entire jstz node keeps running. We therefore need a way to know if the worker is still okay.
Added one endpoint `/worker/health` that reads the heartbeat value set by the worker and returns OK if the value was set in the last 30 seconds.
* Unit testing: added tests.
* Integration testing: updated the existing test.

feat(sequencer): expose worker heartbeat

---

crates/jstz_node/src/sequencer/inbox/mod.rs
crates/jstz_node/tests/sequencer.rs
crates/jstzd/src/task/jstzd.rs

Sequencer assumes that the rollup node is healthy by the time it starts. However jstzd starts the sequencer before the rollup is healthy. This PR fixes that.
* make jstzd::spawn wait for the rollup to spin up before spinning up the jstz node
* removed the sleep used for temp fix inside inbox::monitor 
* manually tested by running jstzd 
* existing test works

fix(sequencer,jstzd): wait for rollup

---

crates/jstz_node/Cargo.toml
crates/jstz_node/src/lib.rs
crates/jstz_node/src/sequencer/worker.rs
crates/jstz_node/tests/sequencer.rs
crates/jstz_proto/src/runtime/v1/mod.rs
crates/jstz_proto/src/runtime/v2/mod.rs

Completes JSTZ-645.
[JSTZ-645](https://linear.app/tezos/issue/JSTZ-645/stream-logs-from-runtime-debug-log-file)
The logging API in jstz node should be able to stream logs from the sequencer runtime.
Updated jstz node such that it streams from the local debug file when it runs in sequencer mode. Dependency `jstz_proto` needs to have feature `kernel` enabled in order to get logs written in the same format as what v1 runtime has right now.
* Integration test: updated the test.

feat(sequencer): stream logs from runtime

---

crates/jstz_runtime/src/error.rs
crates/jstz_runtime/src/sys/js/class.rs

Catch and propagate JS errors occuring in sys lib instead of ignoring them. Part of the effort to improve transparency of errors occurring in the runtime environment
- Propagates errors from js class, static method calls and set method calls
- Also converts JsErrors to JsErrorBox in RuntimeError convertor to capture only the exception message while hiding the deno line that the error comes from. 
`cargo nextest run -p jstz_runtime uncaught_constructor_errors_should_propagate`

fix(runtime): propagate errors from sys lib

---

crates/jstz_node/src/sequencer/db.rs
crates/jstz_node/tests/sequencer.rs

Completes JSTZ-671. (Maybe)
[JSTZ-671](https://linear.app/tezos/issue/JSTZ-671/fix-runtime-db-connections)
There were some random errors related to the runtime database in #1095.
Updated the runtime database's config, hoping to make accesses less problematic. WAL journal mode should permit reads during writes instead of terminating all ongoing reads when a write takes place.
Ran tests with the CI runner multiple times and it seemed fine. Not completely sure how robust this is, but since it cannot be reproduced easily, we see how it goes. At least now the integration test does not fail with the delay in response stream is removed.

fix(sequencer): change runtime db journal config

---

docs/alpha-tester.md

Correct links on this page for jstz.tezos.com with no sub-path.

fix(docs): correct links for jstz.tezos.com

---

crates/jstz_cli/tests/fa_deploy_test.rs
crates/jstzd/Cargo.toml
crates/jstzd/build.rs
crates/jstzd/resources/bootstrap_account/accounts.json
crates/jstzd/src/config.rs
crates/jstzd/src/task/jstzd.rs

Completes JSTZ-694.
[JSTZ-694](https://linear.app/tezos/issue/JSTZ-694/make-bootstrap-accounts-configurable-at-build-time)
Need a mechanism to replace the built-in bootstrap accounts when necessary.
Moved built-in bootstrap account details to a resource file and made jstzd config reader load the accounts from the resource file. The file will be embedded into release builds, which means we can have replace the built-in bootstrap accounts if we replace the resource file at compile time.
Also added a check to the build script that validates bootstrap accounts in the resource file. This ensures that these accounts packed into release builds are always valid.
* Unit testing: all relevant tests that depend on old still work.
* Integration testing: though `jstzd_test` actually needs to be …

chore(jstzd): load built-in bootstrap accounts from file

---

crates/jstz_cli/src/sandbox/container.rs

Completes JSTZ-689.
[JSTZ-689](https://linear.app/tezos/issue/JSTZ-689/expose-jstz-node-config-in-jstzd)
Following #1122. Since now jstz node is configurable and there are default values for the config, we need to set the desired values when launching a sandbox from CLI.
Updated CLI such that `jstz_node` config is added to the sandbox config. Since the mode in default jstz node config is "default", we need to explicitly set it to "sequencer" to run the sequencer in the sandbox.
* Unit testing: updated tests
* Manual testing: build CLI and launched the sandbox. Confirmed that jstz node ran in sequencer mode by checking the endpoint `http://localhost:8933/mode`.

chore(cli): set sandbox jstz node config

---

crates/jstzd/build.rs
crates/jstzd/resources/bootstrap_account/accounts.json
crates/jstzd/src/config.rs
crates/jstzd/src/task/jstzd.rs

Part of JSTZ-709.
[JSTZ-709](https://linear.app/tezos/issue/JSTZ-709/set-activator-account-properly)
We need a mechanism to rotate bootstrap accounts while making sure that octez node can still activate the protocol successfully.
Updated the format of `accounts.json`. Now the balance of each bootstrap account is specified in that file as well. This makes it easier to set the balance of individual bootstrap account.
Each entry can actually be transformed into a proper mapping as there are a bit too many fields now, but I'm keeping it simple here temporarily.
All tests should still work.

chore(jstzd): add balance to built-in bootstrap accounts

---

crates/jstzd/build.rs
crates/jstzd/resources/bootstrap_account/accounts.json
crates/jstzd/src/config.rs
crates/jstzd/src/task/jstzd.rs

Part of JSTZ-709.
[JSTZ-709](https://linear.app/tezos/issue/JSTZ-709/set-activator-account-properly)
We need a mechanism to rotate bootstrap accounts while making sure that octez node can still activate the protocol successfully.
Added validation for built-in bootstrap accounts to jstzd so that invalid bootstrap account config values are failed early. If the account alias `activator` is unknown to octez client, it will not be able to activate the protocol. Seriously speaking, for releases, the validation in the build script is sufficient, but I added similar logic to jstzd as well just to be safe, especially for local dev.
Also updated the bootstrap account display part. The activator account will not be printed out since this account should be purely internal.
* Unit testing: updated …

chore(jstzd): check bootstrap account 'activator'

---

crates/jstz_node/src/config.rs
crates/jstzd/build.rs
crates/jstzd/build_config.rs
crates/jstzd/resources/bootstrap_account/accounts.json
crates/jstzd/src/config.rs
crates/jstzd/src/task/jstzd.rs
crates/jstzd/tests/jstzd_test.rs

Part of JSTZ-711.
[JSTZ-711](https://linear.app/tezos/issue/JSTZ-711/replace-injector)
Injector cannot be hardcoded either.
Removed the hard-coded injector public key and instead added it to the list of built-in bootstrap accounts.
* Manual testing: ran jstzd locally without any issue.

chore(jstzd): read injector from file

---

.cargo/config.toml
Cargo.lock
Makefile
crates/jstz_kernel/Cargo.toml
crates/jstz_kernel/src/executable.rs
crates/jstz_kernel/src/inbox.rs
crates/jstz_kernel/src/lib.rs
crates/jstz_kernel/src/riscv_kernel.rs
crates/jstz_kernel/src/wasm_kernel.rs
crates/jstz_mock/Cargo.toml
crates/jstz_mock/src/host.rs
crates/jstz_mock/src/message/native_deposit.rs
crates/jstz_proto/Cargo.toml
crates/jstz_proto/src/context/account.rs
crates/jstz_proto/src/context/receipt.rs
crates/jstz_proto/src/lib.rs
crates/jstz_proto/src/runtime/v2/fetch/error.rs
crates/jstz_proto/src/runtime/v2/fetch/fetch_handler.rs
crates/jstz_runtime/Cargo.toml
crates/jstz_runtime/src/runtime.rs
rust-toolchain.toml

Closes https://linear.app/tezos/issue/JSTZ-599/integrate-v2-fetch 
Introduces the Jstz kernel event loop for use within RISCV PVM.
RISCV PVM is fundamentally different from WASM in that kernel's no longer need to return to the PVM for tick counting. Tick counting and proof generation occur within the RISCV VM itself, enabling kernel's to manage their own event loops, and keep memory around for the lifetime of the program, essentially as long as the blockchain lives. 
This let's jstz keep around suspended futures in memory and across read_input events
* Split wasm and riscv kernel entrypoint, guarded by feature flag
* Use tokio single threaded and local set to drive event loop to enforce FIFO task queing and support !Send futures required by JsHostRuntime
* Refactor parse message to expose …

feat(kernel): support riscv pvm kernel event loop

---

crates/jstzd/build.rs
crates/jstzd/resources/bootstrap_account/accounts.json
crates/jstzd/src/config.rs
crates/jstzd/src/task/jstzd.rs
crates/jstzd/tests/jstzd_test.rs

Completes JSTZ-713.
[JSTZ-713](https://linear.app/tezos/issue/JSTZ-713/set-rollup-operator)
It is actually fine to use bootstrap1 as the operator, but since we might not always have bootstrap1 in the list of built-in bootstrap accounts, it's better to set up a dedicated account as the rollup operator.
Added one required bootstrap account `rollup_operator` to the list of built-in bootstrap accounts. This account will be the rollup operator and will not be exposed to users. This account being missing in the bootstrap account list will lead to a build error.
Ran the integration test `jstzd_test` locally and it worked.

chore(jstzd): create dedicated account as rollup operator

---

crates/jstz_proto/src/context/account.rs
crates/jstz_proto/src/lib.rs
crates/jstz_proto/src/runtime/v2/fetch/error.rs
crates/jstz_proto/src/runtime/v2/fetch/fetch_handler.rs
crates/jstz_proto/src/runtime/v2/fetch/http.rs
crates/jstz_proto/src/runtime/v2/ledger/mod.rs
crates/jstz_proto/src/runtime/v2/mod.rs
crates/jstz_proto/src/runtime/v2/oracle/oracle.rs
crates/jstz_proto/src/runtime/v2/protocol_context.rs
crates/jstz_runtime/src/ext/jstz_console/mod.rs
crates/jstz_runtime/src/ext/jstz_kv/mod.rs
crates/jstz_runtime/src/lib.rs
crates/jstz_runtime/src/runtime.rs
crates/jstz_runtime/tests/wpt.rs

Closes https://linear.app/tezos/issue/JSTZ-697/dispatch-to-oracle-on-http-request 
We need to support oracle calls in fetch
* Extends SupportedScheme to http (no https support yet)
* Dispatch http calls to `dispatch_oracle`
* `ProtocolContext` in `Runtime` was renamed to `RuntimeContext`
* `ProtocolContext` introduced in proto to hold stateful globals. This is implemented as a global `pub static Arc<Mutex<>>`. ProtocolContext can only be initialized globally.
* Checks for pre-conditions before making an oracle call which are
(1) Source address must be user address. Source is the address that initiated the run operation. Its important to note that all gas deductions occur against the source address only, although gas is set to 0 for now
(2)  RunFunctions cannot call the oracle directly. …

feat(fetch): dispatch handling http request to the oracle

---

crates/jstz_node/src/sequencer/host.rs
crates/jstz_node/src/services/accounts.rs
crates/jstz_node/src/services/operations.rs
crates/jstz_node/src/services/utils.rs

I was testing the zod example and found that deploying and running the smart function were very slow.
Changed the way the sequencer runtime host deals with bytes. Instead of using base58check functions, now it uses hex to encode bytes and decode strings.
* Unit testing: added a timeout check to an existing test. Without the changes, the test will fail as writing a byte array with 64K elements will take more than 10 seconds.

fix(sequencer): decode and encode with hex

---

Cargo.lock
Cargo.toml
crates/jstz_cli/src/sandbox/mod.rs
crates/jstz_node/openapi.json
crates/jstz_node/openapi_v1.json
packages/cli/main/package.json

Bump version to 0.1.1-alpha.2 for the next release
* Bump version in workspace `Cargo.toml`
* Bump version in `packages/cli/main/package.json`
* Bump version of `SANDBOX_IMAGE` in `crates/jstz_cli/src/sandbox/mod.rs`
* Regenerate openapi schema - 
```
cargo run --bin jstz-node --features v2_runtime -- spec -o crates/jstz_node/openapi.json
cargo run --bin jstz-node -- spec -o crates/jstz_node/openapi_v1.json
```
* Synched `Cargo.lock` with compatible dependency versions

chore(release): bump version to 0.1.1-alpha.2

---

crates/jstz_proto/src/runtime/v2/fetch/fetch_handler.rs
crates/jstz_proto/src/runtime/v2/oracle/oracle.rs
crates/jstz_proto/src/runtime/v2/protocol_context.rs

We need to gc requests when they reach TTL based on the current block level
Part of https://linear.app/tezos/issue/JSTZ-541/handle-oracleresponse-operation-in-kernel 
* Adds read only current level to the global protocol context with mutator exposed for testing. The write mechanism will be implemented in next PR
* Update protocol context to expose Arc<Mutex<>> over each field rather than on the entire struct
* Set default TTL to 80 levels and calculate the timeout in send request. The block time in jstzd is 1s allowing 80 seconds to respond.
* Update gc to run compare against the global current level
`cargo nextest run -p jstz_proto oracle  --features v2_runtime`

feat(oracle): use global level to calculate ttl

---

crates/jstz_cli/Dockerfile
crates/jstz_node/Dockerfile
crates/jstz_rollup/Dockerfile
crates/jstzd/Dockerfile

[Image build](https://github.com/jstz-dev/jstz/actions/runs/15973401341) failed mysteriously.
Changed `WORKDIR` from `/` to `/jstz_build`. It seems that somehow the changes in dependencies introduced in #1153 do not work well with that root `WORKDIR`. Perhaps something got overwritten in the failed build and therefore led to the error.
[Test build](https://github.com/jstz-dev/jstz/actions/runs/15977019715)

fix(image): change workdir in dockerfile

---

crates/jstz_kernel/src/inbox.rs
crates/jstz_kernel/src/wasm_kernel.rs

Kernel was stalled because mark for reboot was set too early. It was preventing the kernel to progress to the next level (My guess is that it was stuck in the install phase).
I've tested without mark for reboot and it looked like everything worked just fine but I've kept it in case there are hidden issues down the line.
Move mark for reboot back into `read_message`
`make build-jstzd-kernel && cargo run --bin jstzd run ~/jstzd-config.json`
`cargo run --bin jstz bridge deposit --from bootstrap1 --to ryan --amount 1000 -n dev`
`cargo run -- deploy examples/get-tez/dist/index.js  -n dev`
`cargo run -- run jstz://KT1SXBizWUHDEYTpcRqfethonWSdESy1M9nD/ --data '{"message":"please give me tez"}'  -n dev`

fix(wasm-kernel): move mark for reboot back into read message

---

examples/show-tez/package-lock.json
examples/show-tez/src/index.ts

Completes JSTZ-743.
[JSTZ-743](https://linear.app/tezos/issue/JSTZ-743/clean-up-examples)
Some examples no longer work and need to be removed.
Updated the `show-tez` example so that it does not fail with the v2 runtime. GET requests with bodies are rejected by the v2 runtime with the following error:
```
{                                                                                                                                                                 
class: 'RuntimeError',                                                           
message: 'Uncaught TypeError: Request with GET/HEAD method cannot have body'
}
```
Tested the example with a sandbox.

fix(example): use POST in show-tez

---

crates/jstz_core/src/kv/transaction.rs
crates/jstz_proto/src/context/account.rs
crates/jstz_proto/src/runtime/v2/fetch/fetch_handler.rs

[JSTZ-700](https://linear.app/tezos/issue/JSTZ-700/prevent-oracle-fetch-if-dirty-transaction)
This PR adds protections preventing running oracle in the case that the transaction is dirty. As a dirty we consider all changes except for changes to smart function accounts.
```make```

feat(oracle): prevent oracle fetch if dirty transaction

---

Cargo.lock
Cargo.toml
crates/jstz_cli/src/sandbox/mod.rs
crates/jstz_node/openapi.json
crates/jstz_node/openapi_v1.json
crates/jstzd/Dockerfile
packages/cli/main/package.json

Release 0.1.1-alpha.3 
- Bump version in workspace Cargo.toml
- Bump version in packages/cli/main/package.json
- Bump version of SANDBOX_IMAGE in crates/jstz_cli/src/sandbox/mod.rs
Regenerate openapi schema
```
cargo run --bin jstz-node --features v2_runtime -- spec -o crates/jstz_node/openapi.json
cargo run --bin jstz-node -- spec -o crates/jstz_node/openapi_v1.json
```

chore(release): 0.1.1-alpha.3 release

---

crates/jstz_cli/src/run.rs
crates/jstz_proto/src/executor/mod.rs
crates/jstz_proto/src/runtime/v2/fetch/error.rs
crates/jstz_proto/src/runtime/v2/fetch/fetch_handler.rs

The error message `Unsupport scheme 'tezos'` is grammatically incorrect.
Changed the error message to `Unsupported scheme`. The error enum value is correct, but the message needs to be updated.
All existing tests should still work.

fix: fix error message 'unsupported scheme'

---

crates/jstz_runtime/src/ext/jstz_main/99_main.js
examples/axios/README.md
examples/axios/build.sh
examples/axios/deploy.sh
examples/axios/echo.js
examples/axios/index.ts
examples/axios/package-lock.json
examples/axios/package.json
examples/axios/tsconfig.json

`self` is a property expected on `WorkerGlobalScope`. 
Generally, we cannot support every property on WorkerGlobalScope but we can support self which is used by libraries like Axios to access Fetch API irregardless of the environment.
See https://html.spec.whatwg.org/multipage/workers.html#dom-workerglobalscope-self
* Adds `self` to `globalThis` in `jstz_runtime`
* Adds an Axios example
Write jstzd config
```
cat <<EOF >  ~/jstzd-config.json
{
"jstz_node": {
"mode": "sequencer",
"capacity": 1024
}
}
EOF
```
Rebuild jstzd and run it
```
make build-jstzd-kernel && cargo run --bin jstzd --features oracle run ~/jstzd-config.json
```
Follow instructions in `examples/axios/README.md`

feat(runtime): support self on worker global scope

---

crates/jstz_kernel/Cargo.toml
crates/jstz_kernel/build.rs
crates/jstz_kernel/src/riscv_kernel.rs

- In memory host required because RISCV doesn't support persistent storage
- Presets required because there is no installer equivalent
`make`
Run in mem increased RISCV sandbox  
```
make riscv-pvm-kernel 
git clone git@github.com:jstz-dev/riscv-pvm.git
cd riscv-pvm
nix develop
cd src/riscv
cargo run --release  run -i <path to jstz>/target/riscv64gc-unknown-linux-musl/release/kernel-executable
```

feat(kernel): activate experimental in memory host and preset ticketer & injector in riscv kernel 

---

docs/examples.md
examples/axios/README.md

Builds on https://github.com/jstz-dev/jstz/pull/1190 to add some info about the Axios example to the docs. Will cause a conflict with https://github.com/jstz-dev/jstz/pull/1183 but we can work it out and probably put these two oracle examples in a single section. How's "HTTP libraries and external APIs" for a name for that section?

fix(docs): add info about the Axios example to docs

---

.github/workflows/ci.yml

Improve merge velocity of unrelated changes
Implements merge queues by adding `merge_queue` action trigger to CI and enabling the require merge queue setting in repo configurations.
The merge queue is configured with
- Maximum 10 concurrent builds at one time 
- Enforce a maximum of 10 PRs to merge in a single batch which should be well over our current velocity
- Merge every 2 minutes - PRs in the queue that pass checks will be flushed every 2 minutes
* Merge queue support was tested in https://github.com/jstz-dev/jstz/pull/1203

feat(gh): support merge queues

---

.cargo/config.toml
Makefile

Macos linking flags was being leaked into the RISCV musl compile. See `env | grep NIX_LDFLAGS`. This problem was unnoticeable when run on riscv sandbox but causes the rollup node to hand when ran
- Unset `NIX_LDFLAGS` on build
- Revert to `default-linker-libraries=y`
- Link atomics
`make riscv-pvm-kernel`

fix(kernel): fix leaking macos linking flags when compiling riscv kernel

---

.cargo/config.toml
Cargo.lock
Makefile
crates/jstz_kernel/Cargo.toml
crates/jstz_kernel/src/executable.rs
crates/jstz_kernel/src/riscv_kernel.rs

V8 platform setup takes a few seconds to setup.
Launching a dummy runtime warms the v8 platform up such that future runtime creation will be much faster
`make riscv-kernel-pvm`

feat(kernel): warm up runtime on kernel start

---

Cargo.lock
crates/jstz_node/src/config.rs
crates/jstz_node/src/lib.rs
crates/jstz_node/src/main.rs
crates/jstz_node/src/sequencer/runtime.rs
crates/jstz_node/src/sequencer/worker.rs
crates/jstz_node/src/services/operations.rs
crates/jstz_node/src/services/utils.rs
crates/jstz_utils/Cargo.toml
crates/jstz_utils/src/lib.rs
crates/jstzd/src/config.rs
crates/jstzd/src/task/jstzd.rs
crates/jstzd/tests/jstz_node_test.rs
crates/jstzd/tests/jstzd_test.rs

Some housekeeping.
Moved `KeyPair` from crate jstz_node to jstz_utils since it is going to be used by more than one crate. This is for #1194. Also removed the default implementation for `KeyPair` as mentioned in https://github.com/jstz-dev/jstz/pull/1148#discussion_r2171399218.
All tests should still work.

refactor: move KeyPair to jstz_utils

---

crates/jstz_proto/src/context/receipt.rs
crates/jstz_proto/src/error.rs
crates/jstz_proto/src/event.rs
crates/jstz_proto/src/executor/smart_function/deploy.rs
crates/jstz_proto/src/executor/smart_function/run.rs
crates/jstz_proto/src/logger.rs
crates/jstz_proto/src/runtime/v2/fetch/resources.rs

Part of: [774](https://linear.app/tezos/issue/JSTZ-774/increase-jstz-proto-test-coverage-to-90percent)
Closes: [JSTZ-795: Add tests for `jstz_proto` except error.rs](https://linear.app/tezos/issue/JSTZ-795/add-tests-for-jstz-proto-except-errorrs)
Increased the `jstz_proto`'s test coverage from 76% to 83%
The remaining part that needs testing is [error.rs](https://app.codecov.io/gh/jstz-dev/jstz/blob/main/crates%2Fjstz_proto%2Fsrc%2Ferror.rs) ([task link](https://linear.app/tezos/issue/JSTZ-794/add-test-for-jstz-protoerrorrs))
codecov link
[Before](https://app.codecov.io/gh/jstz-dev/jstz/tree/main/crates%2Fjstz_proto)
[After](https://app.codecov.io/gh/jstz-dev/jstz/tree/leounoki%2Fjstz-774/crates%2Fjstz_proto)

chore(proto): increase test coverage

---

Makefile
crates/jstz_runtime/tests/api_coverage/main.rs
flake.nix

Ensure code is formatted/linted and dev env builds for everyone
* Install git pre-commit hook as part of provisioning nix dev shel
* Ignore the entire `crates/jstz_runtime/tests/api_coverage/main.rs` file when `skip-wpt` is defined. Since the test depends on files pulled on an ad-hoc, `cargo clippy` (via `make lint`) fails to compile
```
make build
make fmt
make lint
```

fix: include git install hooks as part of nix 

---

Cargo.lock
Cargo.toml
crates/jstz_node/Cargo.toml
crates/jstz_node/src/sequencer/inbox/mod.rs

Refactor inbox monitor
Implement `retry_expo` that uses tokio-retry for exponential backoff retry. This function can be reused later for connecting to the block stream in #1193 
cargo test --package jstz_node --test sequencer -- run_sequencer --exact --show-output

refactor(sequencer): extract retry logic

---

Cargo.lock
crates/jstz_core/Cargo.toml
crates/jstz_core/src/event.rs
crates/jstz_core/src/lib.rs
crates/jstz_oracle_node/Cargo.toml
crates/jstz_oracle_node/src/request.rs
crates/jstz_proto/src/lib.rs
crates/jstz_proto/src/runtime/v2/fetch/fetch_handler.rs
crates/jstz_proto/src/runtime/v2/oracle/oracle.rs
crates/jstz_proto/src/runtime/v2/oracle/request.rs

Part of: [807](https://linear.app/tezos/issue/JSTZ-807/event-eventstream)
Closes: [810](https://linear.app/tezos/issue/JSTZ-810/implement-eventeventstream-trait)
* Move `event.rs` to jstz_core
* Refactor the Event trait to implement DeserializedOwned
existing unit test works
manually tested the basic_oracle.js
```
cargo run --bin jstz run jstz://KT1VDAkeKAyhKFHjAypmqs6kB263tUjksW9W/ --network dev -t
[INFO]: Fetching uuid4
[INFO]: Running something else while waiting
[INFO]: UUID: a3d7737c-c411-40c0-bd5c-168698c99fdb
a3d7737c-c411-40c0-bd5c-168698c99fdb
```

refactor(core): move event

---

crates/jstz_node/src/sequencer/worker.rs

Cleaning up feature flags in the sequencer in preparation for the riscv pvm setup.
Replaced two references to the feature flag `v2_runtime` with `oracle`. This should be fine as the only reference to the guarded function `run_event_loop` is also guarded by that `oracle` feature flag.
Before the change was made, there was this warning:
```
$ cd $(git rev-parse --show-toplevel)/crates/jstz_node && cargo clippy --fix --allow-dirty --allow-staged --features v2_runtime
warning: function `run_event_loop` is never used
--> crates/jstz_node/src/sequencer/worker.rs:119:4
|
119 | fn run_event_loop(
|    ^^^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
```
Now it is cleared.

fix(sequencer): clean up feature flag

---

flake.nix

Aligns v8 caged heap to page size to reduce redundant memory request
Depends on https://github.com/jstz-dev/rusty_v8/pull/6
Closes https://linear.app/tezos/issue/JSTZ-839disable-pointer-compression-in-v8
Updates nix to point to the v8 archive that aligns cage heap to page size. See the rusty_v8 related PR for implementation context and details
https://github.com/jstz-dev/rusty_v8/pull/6
To run test
```
make run-manual-test
```
To generate results (linux only). For mac, you can run manual test and open Activity Monitor.
```
./scripts/heaptrack.sh
```
```
total runtime: 3.929000s.
calls to allocation functions: 3516312 (894963/s)
temporary memory allocations: 469705 (119548/s)
peak heap memory consumption: 1.23G
peak RSS (including heaptrack overhead): 5.99G
total memory leaked: 7.85M
```

feat(nix): use v8 with caged heap aligned to page size

---

.gitignore
crates/jstz_tps_bench/run.sh

Allows internal paths to resolve correctly when `jstz_tps_bench/run.sh` from any root path
Sets base directory of relative paths to the directory of the script. Also add kernel compilation as the first step.
```
./crates/jstz_tps_bench/run.sh
```
```
cd crates && ./jstz_tps_bench/run.sh
```
```
cd crates/jstz_tps_bench && ./run.sh
```

fix(tps_bench): bench run uses dirname for path resolution

---

Cargo.lock
Cargo.toml
crates/jstz_core/Cargo.toml
crates/jstz_core/src/event.rs
crates/jstz_core/src/kv/mod.rs
crates/jstz_core/src/kv/storage_update.rs
crates/jstz_proto/src/runtime/v2/oracle/oracle.rs

Part of: [JSTZ-813 – Leak StorageUpdateEvent from kernel](https://linear.app/tezos/issue/JSTZ-813/leak-storageupdateevent-from-kernel)
This PR introduces the`BatchStorageUpdate` event, which will be used to reconstruct storage state in `jstz-node`. The event is published from within transactions, as will be fully integrated in a follow-up PR (#1251).
- **Refactored `event.rs`:**
- The `Event` trait now provides two symmetric methods: `to_string` and `from_str` (with JSON as the default implementation).  
The purpose of `Event` is to leak data from the kernel, and since the only way to do so is via the kernel debug log (which requires string conversion), these methods are appropriate.  This also makes it easy to customize serialization for each event type (e.g, JSON for sf logs event vs …

feat(core): add storage update event

---

crates/jstz_core/src/event.rs
crates/jstz_core/src/kv/storage_update.rs
crates/jstz_core/src/kv/transaction.rs
crates/jstz_proto/src/runtime/v2/fetch/fetch_handler.rs
crates/jstz_proto/src/runtime/v2/oracle/oracle.rs

Closes: [813](https://linear.app/tezos/issue/JSTZ-813/leak-storageupdateevent-from-kernel) 
In the next step, we will add the storage update event consumer in jstz node to sync the storage.
* Publishes storage update event from the final transaction commit. 
* The events are batched in memory and published in the final commit 
* Added `publish_event` method to `BatchStroageUpdate` that publishes itself only if non empty
Added unit test:
```
cargo test --package jstz_core
```

feat(core): publish storage update event from transaction

---

crates/jstz_kernel/src/inbox.rs
crates/jstz_kernel/src/parsing.rs
crates/jstz_kernel/src/riscv_kernel.rs
crates/jstz_kernel/src/wasm_kernel.rs
crates/jstz_node/Cargo.toml
crates/jstz_node/src/sequencer/inbox/mod.rs
crates/jstz_node/src/sequencer/runtime.rs
crates/jstz_node/tests/sequencer.rs
crates/jstz_proto/src/executor/deposit.rs
crates/jstz_proto/src/executor/fa_deposit.rs
crates/jstz_proto/src/operation.rs

Fixes [JSTZ-582](https://linear.app/tezos/issue/JSTZ-582/fix-inbox-id-in-deposit-and-fadeposit)
This PR replaces the `u32` `inbox_id` with a pair of `u32`s, consisting of the level and the original `inbox_id` (unique within a level). Together they define a globally unique ID for a given inbox message.
```
make test
```

fix(proto): inbox_id is not unique (only unique to the level)

---

crates/jstz_node/src/lib.rs
crates/jstz_node/src/services/accounts.rs
crates/jstz_node/src/services/operations.rs
crates/jstz_node/src/services/utils.rs

Part of: [812](https://linear.app/tezos/issue/JSTZ-812/implement-storageupdate-consumer-in-jstz-node)
Next PR: [1264](https://github.com/jstz-dev/jstz/pull/1264)
In the following PR [1264](https://github.com/jstz-dev/jstz/pull/1264), a storage update event consumer is spawned when `storage_sync` is true. This consumer will process the events and update the `storage_sync_db` . In order to read the valyes from the correct place, this PR extends the `StoreWrapper` to account for the `storage_sync_db`.
* `StoreWrapper` now takes `storage_sync` and `storage_sync_db` as a parameter
* `StoreWrapper` becomes the `storage_sync` DB when `storage_sync` is true and on default mode
Added unit test
```
cargo test --package jstz_node
```

feat(jstz_node): add storage_sync_db

---

docs/quick_start.md

To get the install steps to work I had to install git submodules, or else `pnpm i` threw errors.
See also https://github.com/jstz-dev/dev-wallet/pull/36.

fix(docs): install submodules in readme build steps

---

crates/jstz_crypto/src/public_key_hash.rs

Part of JSTZ-804.
[JSTZ-804](https://linear.app/tezos/issue/JSTZ-804/configure-riscv-pvm-in-sequencer)
Implemented methods for converting `tezos_crypto_rs::public_key_hash::PublicKeyHash` and `jstz_crypto::public_key_hash::PublicKeyHash`. This is for #1281.

feat(crypto): convert public key hash

---

Cargo.lock
crates/jstz_oracle_node/src/data_provider.rs
crates/jstz_oracle_node/src/relay.rs
crates/jstz_utils/Cargo.toml
crates/jstz_utils/src/event_stream.rs
crates/jstz_utils/src/filtered_log_stream.rs
crates/jstz_utils/src/lib.rs
crates/jstz_utils/src/retry.rs

Refactoring PR to prepare for #1264 
* Moved `exponential_back_off` & `retry_async` to `jstz_utils`
* Moved `append_async` test utils to `jstz_utils`
* Add test for `retry_async` and `exponential_back_off`

refactor(jstz_utils): move async_retry

---

crates/jstz_core/src/kv/storage_update.rs
crates/jstz_node/src/lib.rs
crates/jstz_node/src/storage_sync.rs

Part of: [812](https://linear.app/tezos/issue/JSTZ-812/implement-storageupdate-consumer-in-jstz-node)
In the next PR, otorageSync will be spawned on the default mode.
* Refactored the tests by moving `append_async` to `jstz_utils` 
* Add `delete` method to the db
* Add `SotorageSync` that processes the given debug file and apply the `StorageUpdate` event to the db
cargo test -p jstz_node

feat(jstz_node): implement storage sync

---

Cargo.lock
Cargo.toml
crates/jstz_cli/src/sandbox/mod.rs
crates/jstz_node/openapi.json
crates/jstz_node/openapi_v1.json
crates/jstz_sdk/Cargo.toml
crates/jstz_sdk/src/lib.rs
crates/jstzd/src/config.rs
examples/get-tez/README.md
examples/show-tez/package-lock.json
examples/show-tez/package.json
examples/show-tez/src/index.ts
package-lock.json
packages/cli/main/package.json
packages/sdk/index.ts
packages/sdk/package.json

Release 0.1.1-alpha.4
* Rebuild jstz_sdk signer and hasher and published. Required because of backward incompatible change in RunFunction due to parsing body from base64 instead of Vec<u8>. jstz_sdk parses the javascript value into a valid operation before performing any actions on it, so I've had to parse it JS into JSON first then JSON into Operation. Tested by pointing to jstz_sdk and jstz_client to local relative path before publising. 
```
make build-sdk-wasm-pkg
```
* Bump version
* Regenerate openapi
* Fixed missing import in jstz_node section that is hidden behind oracle feature flag
`make`
```
cargo run --bin jstz-node --features v2_runtime -- spec -o crates/jstz_node/openapi.json
cargo run --bin jstz-node -- spec -o crates/jstz_node/openapi_v1.json
```
Tested `jstz_sdk` and …

chore(release): 0.1.1-alpha.4

---

crates/jstzd/src/config.rs
crates/jstzd/src/task/oracle_node.rs
crates/jstzd/tests/jstzd_test.rs
crates/jstzd/tests/main_test.rs

Issues missed out in previous commits.
Fixed building oracle config in jstzd.
```
cd $(git rev-parse --show-toplevel)/crates/jstzd && cargo clippy --features v2_runtime,oracle
```

fix(jstzd): fix clippy with oracle feature flag

---

crates/jstz_node/Dockerfile

Part of JSTZ-893.
[JSTZ-893](https://linear.app/tezos/issue/JSTZ-893/build-images-for-nodes-for-private-net)
Updated the docker file for jstz node such that it builds with v2 runtime and oracle.
Built the image locally and ran jstz node from the image without any issue.

chore(jstz_node): update docker file

---

crates/jstz_proto/src/executor/smart_function/run.rs
crates/jstz_proto/src/runtime/v2/fetch/fetch_handler.rs
crates/jstz_proto/src/runtime/v2/fetch/http.rs
docs/functions/tokens.md

Closes https://linear.app/tezos/issue/JSTZ-657/v2-fetch-should-support-transfer-with-noop
Reverts https://github.com/jstz-dev/jstz/pull/1179
Supports transfers to smart function accounts without executing its code. Parity with user account transfers.
Checks for `NOOP_PATH` in smart function flow. 
`cargo nextest run -p jstz_proto --features v2_runtime`
Previous ignored noop tests have been enabled

fix(proto): handle noop transfer for sf in v2 fetch handler

---

crates/jstz_proto/src/context/receipt.rs
crates/jstz_proto/src/error.rs
crates/jstz_proto/src/executor/mod.rs
crates/jstz_proto/src/operation.rs

Closes https://linear.app/tezos/issue/JSTZ-565/operation-receipts-should-not-be-updated
Valid operation receipts should not be overwritten
* Allow verify nonce to return Error::NoncePassed to indicate that a nonce being validated has already passed on the account
* Receipt::write skips writing if Error::NoncePassed and the receipt has already exists
`cargo nextest run -p jstz_proto executor --features v2_runtime`

fix(proto): prevent valid operation receipts from being overwritten

---

Cargo.lock
crates/jstz_node/Cargo.toml
crates/jstz_node/src/sequencer/inbox/api.rs
crates/jstz_node/src/sequencer/inbox/mod.rs
crates/jstz_node/src/sequencer/inbox/store.rs
crates/jstz_node/src/sequencer/inbox/stream.rs

Part of: [696](https://linear.app/tezos/issue/JSTZ-696/implement-sequentialblockstream)
The sequencer monitors the L1 block to process the inbox messages. Currently this monitor isn't resumable as it doesn't keep track of the last processed block level. This PR introduces `SequentialBlockStream`, an abstraction for the sequencer’s inbox monitor. This stream yields block levels in order, automatically handling:
* Gaps in block levels (by filling backlogs)
* Source stream errors and reconnections
* Backoff and retry logic for robustness
In the next PR, we integrate `SequentialBlockStream` into the inbox monitor.
1. **Introduce `SequentialBlockStream`**  
The stream can resume from a checkpoint loaded from persistent storage and provides an API to save checkpoints as progress is made. The …

feat(sequencer): implement sequential stream

---

crates/jstz_kernel/src/inbox.rs
crates/jstz_kernel/src/riscv_kernel.rs
crates/jstz_kernel/src/wasm_kernel.rs
crates/jstz_node/src/sequencer/inbox/mod.rs
crates/jstz_node/src/sequencer/queue.rs
crates/jstz_node/src/services/operations.rs
crates/jstz_riscv_wpt_test_kernel/src/lib.rs

Part of JSTZ-804.
[JSTZ-804](https://linear.app/tezos/issue/JSTZ-804/configure-riscv-pvm-in-sequencer)
Since inbox ID is used to derive operation hashes for deposit operations, inbox ID must be preserved with parsed inbox messages such that the RISCV PVM is aware of this information while loading messages.
Introduced one wrapper struct `ParsedInboxMessageWrapper` that packs the existing `ParsedInboxMessage` and an inbox message's inbox ID. To avoid unnecessary distracting changes, the awkward name `ParsedInboxMessageWrapper` is chosen instead of using `ParsedInboxMessage` and renaming the enum. Renaming can be carried out later on if necessary.
* Unit testing: updated existing tests to cover index IDs

feat(kernel): record inbox id of parsed inbox messages

---

packages/cli/main/install.js
packages/cli/main/package.json

Forcing resolution of optional dependencies that do not exists fails in `yarn add`. See https://tezos.slack.com/archives/C084FG0R466/p1757407576584279 
Remove optional dependencies and comment out dependency resolution lines
`yarn global add file:/<path-to-jstz>/packages/cli/main`
`npm install -g file:/<path-to-jstz>/packages/cli/main`

fix: remove optional dependency from cli npm package temporarily

---

crates/jstz_node/Cargo.toml

[Nightly test](https://github.com/jstz-dev/jstz/actions/runs/18119000488/job/51560749626) failed due to changes in #1332.
Added `jstz_utils/test_utils` as a dependency for sequencer integration tests.
```
cargo test --test sequencer run_riscv_sequencer --features riscv_test --release
```

fix(test): update dependency of sequencer integration tests

---

crates/jstz_cli/src/network.rs
crates/jstz_cli/tests/network.rs

Part of JSTZ-783.
[JSTZ-783](https://linear.app/tezos/issue/JSTZ-783/support-jstz-network-addupdatedelete)
Added one command `network get-default` to CLI to retrieve the current default network from the config file.
* Integration test: added one test

feat(cli): get default network

---

package-lock.json
packages/sdk/package.json

`jstz_sdk@0.1.1-alpha.4` was recently pulled from npm and bumped to `alpha4.1` which causes ["Build Documentation" ci step](https://github.com/jstz-dev/jstz/actions/runs/18321588556/job/52175824323) to fail. This PR fixes that 
`npm ci`

fix: update jstz_sdk dependency version

---

crates/jstz_proto/src/runtime/v2/fetch/error.rs
crates/jstz_proto/src/runtime/v2/parsed_code.rs
crates/jstz_runtime/src/ext/jstz_console/mod.rs
crates/jstz_runtime/src/ext/jstz_fetch/mod.rs
crates/jstz_runtime/src/ext/jstz_kv/mod.rs
crates/jstz_runtime/src/ext/jstz_main/01_errors.js
crates/jstz_runtime/src/ext/jstz_main/98_global_scope.js
crates/jstz_runtime/src/ext/jstz_main/mod.rs
crates/jstz_runtime/src/runtime.rs

Close: [922](https://linear.app/tezos/issue/JSTZ-922/non-built-in-errors-dont-propagate-to-the-receipt)
The op function didn't recognize the custom rust error. This is because we didn't register the error on js side. This PR fixes that.
* Introduced custom errors in ext/jstz_main (RuntimeError)
* 01_error.js now exposes a function that registers custom error given an array of error class name in string
* Removed `ProtocolError` as it is overlapping w `RuntimeError`.
* Fixed `JstzDate.protoype.constructor` typo.
* Added`CompileModuleErr` error.
* Fix/added unit tests
* Manual tests
Made fetch return a `RuntimeError` immediately. This used to return undefined but now the error is being returned and that error is an `instanceof` `RuntimeError` and `Error`

feat(runtime): register custom errors
